Repository cloudforet-io/console, pull requests merged in 2024-09, with the labels that each got.

#4622 fix: fix validation bug of geomap
  apps/web/src/common/modules/widgets/_composables/use-widget-options-complex-validation.ts
  apps/web/src/services/dashboards/components/DashboardToolsetDateDropdown.vue
Labels: pass/signedoff

#4623 fix(data-table): apply legacy-evaluate compatible code
  apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformContents.vue
Labels: pass/signedoff

#4625 fix: add preset values to `variableModel` stat results & apply cost-data-source presetValues to data-table filter
  apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardAddForm.vue
  apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardFilters.vue
  apps/web/src/lib/variable-models/_base/resource-variable-model.ts
  apps/web/src/lib/variable-models/_base/types.ts
Labels: pass/signedoff

#4626 feat: apply page access permission and revert role info
  apps/web/src/schema/identity/token/model.ts
  apps/web/src/services/advanced/components/WorkspaceGroupHeader.vue
  apps/web/src/services/advanced/components/WorkspaceGroupTabGroupUser.vue
  apps/web/src/services/advanced/components/WorkspaceGroupTabWorkspace.vue
  apps/web/src/services/advanced/components/WorkspaceGroupTable.vue
  apps/web/src/services/advanced/pages/admin/AdminWorkspaceGroupPage.vue
  apps/web/src/services/iam/components/RoleManagementTable.vue
  apps/web/src/services/iam/components/UserManagementTabProjects.vue
  apps/web/src/services/iam/components/UserManagementTabWorkspace.vue
  apps/web/src/services/iam/components/UserManagementTable.vue
  apps/web/src/services/iam/constants/role-constant.ts
  apps/web/src/store/modules/user/actions.ts
Labels: pass/signedoff

#4627 feat: merge dashboard-september to master
  apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardAddForm.vue
  apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardFilters.vue
  apps/web/src/lib/variable-models/_base/resource-variable-model.ts
  apps/web/src/lib/variable-models/_base/types.ts
Labels: pass/signedoff

#4630 chore: delete console log
  apps/web/src/store/reference/role-reference-store.ts
Labels: pass/signedoff

#4633 fix: fix widget bugs
  apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldTableDataField.vue
  apps/web/src/common/modules/widgets/_widgets/pie-chart/PieChart.vue
  apps/web/src/services/dashboards/components/DashboardToolsetDateDropdown.vue
Labels: pass/signedoff

#4634 chore: fix minor issue
  apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformFormEvaluate.vue
  apps/web/src/common/modules/widgets/_widgets/table/Table.vue
Labels: pass/signedoff

#4635 feat: merge to master
  apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformFormEvaluate.vue
  apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldTableDataField.vue
  apps/web/src/common/modules/widgets/_widgets/pie-chart/PieChart.vue
  apps/web/src/common/modules/widgets/_widgets/table/Table.vue
  apps/web/src/services/dashboards/components/DashboardToolsetDateDropdown.vue
Labels: pass/signedoff

#4638 fix: fix vercel deploy action
  .github/workflows/dispatch_preview_deploy_with_vercel.yml
  .gitignore
  apps/web/src/lib/config/index.ts
Labels: pass/signedoff

#4639 feat: create `getContrastingColor` util
  packages/utils/src/index.ts
Labels: pass/signedoff

#4641 fix: solve some dashboard QAs
  apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformFormEvaluate.vue
  apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldTableDataField.vue
  apps/web/src/common/modules/widgets/_widgets/table/_component/WidgetDataTable.vue
  apps/web/src/services/dashboards/DashboardsLSB.vue
Labels: pass/signedoff

#4637 feat(cost-report-detail-page): update new feature
  apps/web/src/common/pages/CostReportDetailPage.vue
Labels: pass/signedoff

#4644 chore: update translations
  apps/web/src/services/workspace-home/components/CostSummary.vue
Labels: pass/signedoff

#4646 fix: refactor clear-selection in PSelectDropdown & apply
  apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldTableDataField.vue
  packages/mirinae/src/inputs/dropdown/select-dropdown/PSelectDropdown.mdx
  packages/mirinae/src/inputs/dropdown/select-dropdown/PSelectDropdown.stories.ts
  packages/mirinae/src/inputs/dropdown/select-dropdown/PSelectDropdown.vue
  packages/mirinae/src/inputs/dropdown/select-dropdown/story-helper.ts
Labels: pass/signedoff

#4650 fix(QA): solve some qAs
  apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldDataFieldHeatmapColor.vue
  apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldNumberFormat.vue
  apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldTableColumnWidth.vue
  apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldTableDataField.vue
Labels: pass/signedoff

#4652 feat: add migration code for changed widget fields
  apps/web/src/common/modules/widgets/_widgets/line-chart/LineChart.vue
  apps/web/src/services/dashboards/helpers/widget-migration-helper.ts
  apps/web/src/services/dashboards/stores/dashboard-detail-info-store.ts
Labels: pass/signedoff

#4654 fix: apply sorting to separated date field
  apps/web/src/common/modules/widgets/_constants/widget-components-constant.ts
  apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/ClusteredColumnChart.vue
  apps/web/src/common/modules/widgets/_widgets/heatmap/Heatmap.vue
  apps/web/src/common/modules/widgets/_widgets/line-chart/LineChart.vue
  apps/web/src/common/modules/widgets/_widgets/stacked-area-chart/StackedAreaChart.vue
  apps/web/src/common/modules/widgets/_widgets/stacked-area-chart/widget-config.ts
  apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/StackedColumnChart.vue
  apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/StackedHorizontalBarChart.vue
  apps/web/src/services/dashboards/helpers/widget-migration-helper.ts
Labels: pass/signedoff

#4655 feat: merge to master
  apps/web/src/common/modules/widgets/_constants/widget-components-constant.ts
  apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/ClusteredColumnChart.vue
  apps/web/src/common/modules/widgets/_widgets/heatmap/Heatmap.vue
  apps/web/src/common/modules/widgets/_widgets/line-chart/LineChart.vue
  apps/web/src/common/modules/widgets/_widgets/stacked-area-chart/StackedAreaChart.vue
  apps/web/src/common/modules/widgets/_widgets/stacked-area-chart/widget-config.ts
  apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/StackedColumnChart.vue
  apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/StackedHorizontalBarChart.vue
  apps/web/src/services/dashboards/helpers/widget-migration-helper.ts
Labels: pass/signedoff

#4656 fix: fix xAxis sorting of clusteredColumnChart & table api filter bug
  apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/ClusteredColumnChart.vue
  apps/web/src/common/modules/widgets/_widgets/table/Table.vue
Labels: pass/signedoff

#4657 fix: get full date range when its separated date
  apps/web/src/common/modules/widgets/_helpers/widget-date-helper.ts
  apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/ClusteredColumnChart.vue
  apps/web/src/common/modules/widgets/_widgets/heatmap/Heatmap.vue
  apps/web/src/common/modules/widgets/_widgets/line-chart/LineChart.vue
  apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/StackedColumnChart.vue
  apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/StackedHorizontalBarChart.vue
Labels: pass/signedoff

#4658 fix: fix table api filter bug
  apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/ClusteredColumnChart.vue
  apps/web/src/common/modules/widgets/_widgets/line-chart/LineChart.vue
  apps/web/src/common/modules/widgets/_widgets/table/Table.vue
Labels: pass/signedoff

#4659 feat: get `tableDataField` to stackedColumnChart
  apps/web/src/common/modules/widgets/_constants/widget-config-list-constant.ts
  apps/web/src/common/modules/widgets/_helpers/widget-load-helper.ts
  apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/ClusteredColumnChart.vue
  apps/web/src/common/modules/widgets/_widgets/line-chart/LineChart.vue
  apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/StackedColumnChart.vue
  apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/widget-config.ts
  apps/web/src/services/dashboards/helpers/widget-migration-helper.ts
Labels: pass/signedoff

#4660 feat: apply `tableDataField` to horizontalBarChart
  apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/StackedColumnChart.vue
  apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/StackedHorizontalBarChart.vue
  apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/widget-config.ts
  apps/web/src/services/dashboards/helpers/widget-migration-helper.ts
Labels: pass/signedoff

#4664 feat: apply `tableDataField` to heatmap
  apps/web/src/common/modules/widgets/_widgets/heatmap/Heatmap.vue
  apps/web/src/common/modules/widgets/_widgets/heatmap/widget-config.ts
  apps/web/src/services/dashboards/helpers/widget-migration-helper.ts
Labels: pass/signedoff

#4667 fix: fixed undefined error
  apps/web/src/services/iam/components/AppManagementTable.vue
Labels: pass/signedoff

#4666 feat: apply minor feedback
  apps/web/src/services/cost-explorer/components/CostAnalysisLSB.vue
  apps/web/src/services/iam/components/UserManagementAddUser.vue
  apps/web/src/services/iam/store/user-page-store.ts
Labels: pass/signedoff

#4669 fix: set reference data when export excel
  apps/web/src/services/asset-inventory/components/MetricExplorerDataTable.vue
Labels: pass/signedoff

#4668 feat: apply tableDataField to colorCodedTableHeatmap
  apps/web/src/common/modules/widgets/_widgets/color-coded-table-heatmap/ColorCodedTableHeatmap.vue
  apps/web/src/common/modules/widgets/_widgets/color-coded-table-heatmap/widget-config.ts
  apps/web/src/services/dashboards/helpers/widget-migration-helper.ts
Labels: pass/signedoff

#4671 feat: apply dormant filter at workspace dropdown
  apps/web/src/services/asset-inventory/components/WorkspaceDropdown.vue
  apps/web/src/services/cost-explorer/components/BudgetCreateTargetSelect.vue
  apps/web/src/services/cost-explorer/components/CostAnalysisFiltersPopper.vue
  apps/web/src/services/cost-explorer/components/DataSourceManagementTabLinkedAccountTable.vue
  apps/web/src/services/dashboards/components/DashboardVariableDropdown.vue
  apps/web/src/services/iam/components/UserManagementAddAdminRole.vue
  apps/web/src/services/info/components/NoticeListItem.vue
  apps/web/src/services/info/components/NoticeWorkspaceDropdown.vue
Labels: pass/signedoff

#4670 fix(cloudServiceDetailPage): fix reset bug of query tags
  apps/web/src/services/asset-inventory/pages/CloudServiceDetailPage.vue
Labels: pass/signedoff

#4672 feat: set `is_dormant: false` if it's workspace model
  apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardFilters.vue
  apps/web/src/lib/variable-models/_base/resource-variable-model.ts
  apps/web/src/lib/variable-models/_base/types.ts
  apps/web/src/lib/variable-models/variable-model-menu-handler.ts
  apps/web/src/services/asset-inventory/components/MetricExplorerFiltersPopper.vue
  apps/web/src/services/cost-explorer/components/CostAnalysisFiltersPopper.vue
  apps/web/src/services/dashboards/components/DashboardVariableDropdown.vue
  apps/web/src/services/dashboards/components/DashboardWidgetOptionDropdown.vue
Labels: pass/signedoff

#4675 refactor: apply components folder
  apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2.vue
  apps/web/src/services/dashboards/components/dashboard-create/DashboardCreateScopeForm.vue
  apps/web/src/services/dashboards/components/dashboard-create/DashboardCreateStep1.vue
  apps/web/src/services/dashboards/components/dashboard-create/DashboardCreateStep1SearchFilter.vue
  apps/web/src/services/dashboards/components/dashboard-create/DashboardCreateStep2.vue
  apps/web/src/services/dashboards/components/dashboard-create/DashboardCreateTemplateBoard.vue
  apps/web/src/services/dashboards/components/dashboard-detail/DashboardCloneModal.vue
  apps/web/src/services/dashboards/components/dashboard-detail/DashboardControlButtons.vue
  apps/web/src/services/dashboards/components/dashboard-detail/DashboardDetailHeader.vue
  apps/web/src/services/dashboards/components/dashboard-detail/DashboardLabels.vue
  apps/web/src/services/dashboards/components/dashboard-detail/DashboardLabelsButton.vue
  apps/web/src/services/dashboards/components/dashboard-detail/DashboardNameEditModal.vue
  apps/web/src/services/dashboards/components/dashboard-detail/DashboardRefreshDropdown.vue
  apps/web/src/services/dashboards/components/dashboard-detail/DashboardReorderSidebar.vue
  apps/web/src/services/dashboards/components/dashboard-detail/DashboardShareWithCodeModal.vue
  apps/web/src/services/dashboards/components/dashboard-detail/DashboardToolsetDateCustomModal.vue
  apps/web/src/services/dashboards/components/dashboard-detail/DashboardToolsetDateDropdown.vue
  apps/web/src/services/dashboards/components/dashboard-detail/DashboardVariableDropdown.vue
  apps/web/src/services/dashboards/components/dashboard-detail/DashboardVariablesV2.vue
  apps/web/src/services/dashboards/components/dashboard-detail/DashboardWidgetContainerV2.vue
  apps/web/src/services/dashboards/components/dashboard-main/DashboardMainBoardList.vue
  apps/web/src/services/dashboards/components/legacy/DashboardCostWidgetValueOptionDropdown.vue
  apps/web/src/services/dashboards/components/legacy/DashboardCustomizePageName.vue
  apps/web/src/services/dashboards/components/legacy/DashboardManageVariableForm.vue
  apps/web/src/services/dashboards/components/legacy/DashboardManageVariableOptionsField.vue
  apps/web/src/services/dashboards/components/legacy/DashboardManageVariableOverlay.vue
  apps/web/src/services/dashboards/components/legacy/DashboardManageVariableTable.vue
  apps/web/src/services/dashboards/components/legacy/DashboardVariables.vue
  apps/web/src/services/dashboards/components/legacy/DashboardVariablesMoreButton.vue
  apps/web/src/services/dashboards/components/legacy/DashboardWidgetContainer.vue
  apps/web/src/services/dashboards/components/legacy/DashboardWidgetMoreOptions.vue
  apps/web/src/services/dashboards/components/legacy/DashboardWidgetOptionDropdown.vue
  apps/web/src/services/dashboards/components/legacy/DashboardWidgetOptionsForm.vue
  apps/web/src/services/dashboards/components/legacy/WidgetFullModeModal.vue
  apps/web/src/services/dashboards/composables/use-dashboard-container-width.ts
  apps/web/src/services/dashboards/constants/widget-container-config.ts
  apps/web/src/services/dashboards/helpers/__tests__/widget-width-helper.test.ts
  apps/web/src/services/dashboards/helpers/widget-theme-helper.ts
  apps/web/src/services/dashboards/helpers/widget-width-helper.ts
  apps/web/src/services/dashboards/pages/DashboardCreatePage.vue
  apps/web/src/services/dashboards/pages/DashboardDetailPage.vue
  apps/web/src/services/dashboards/pages/DashboardsMainPage.vue
Labels: pass/signedoff

#4678 feat(table-data-field): Create new version & apply migration code and new design & change field dir structure
  apps/web/src/common/modules/widgets/_constants/widget-field-components-constant.ts
  apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldTableDataField.vue
  apps/web/src/common/modules/widgets/_widget-fields/table-data-field/WidgetFieldTableDataField.vue
  apps/web/src/common/modules/widgets/_widget-fields/table-data-field/type.ts
  apps/web/src/common/modules/widgets/_widgets/table/Table.vue
  apps/web/src/common/modules/widgets/types/widget-field-type.ts
  apps/web/src/common/modules/widgets/types/widget-field-value-type.ts
  apps/web/src/services/dashboards/helpers/widget-migration-helper.ts
  packages/language-pack/en.json
  packages/language-pack/ja.json
  packages/language-pack/ko.json
Labels: pass/signedoff

#4680 fix: apply changed tableDataField value to missed file
  apps/web/src/common/modules/widgets/_composables/use-widget-options-complex-validation.ts
  apps/web/src/common/modules/widgets/_helpers/widget-load-helper.ts
  apps/web/src/common/modules/widgets/_widget-fields/table-data-field/WidgetFieldTableDataField.vue
Labels: pass/signedoff

#4681 fix: apply table-data-field (new version) to Table widget
  apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldComparison.vue
  apps/web/src/common/modules/widgets/_widget-fields/table-data-field/WidgetFieldTableDataField.vue
  apps/web/src/common/modules/widgets/_widgets/table/Table.vue
Labels: pass/signedoff

#4679 feat: connect form state to click-done event & apply search to value dropdown
  apps/web/src/schema/inventory/cloud-service-type/api-verbs/stat.ts
  apps/web/src/services/asset-inventory/components/CollectorAdditionalRule.vue
  apps/web/src/services/asset-inventory/components/CollectorAdditionalRuleForm.vue
  apps/web/src/services/asset-inventory/helpers/cloud-service-analyze-query-helper.ts
  apps/web/src/services/asset-inventory/pages/CollectorDetailPage.vue
  apps/web/src/services/asset-inventory/stores/collector-form-store.ts
  apps/web/src/services/asset-inventory/types/type.ts
  packages/core-lib/src/space-connector/type.ts
Labels: pass/signedoff

#4682 refactor: edit widget field dir structure
  apps/web/src/common/modules/widgets/_constants/widget-field-components-constant.ts
  apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldProgressBar.vue
  apps/web/src/common/modules/widgets/_widget-fields/advanced-format-rules/WidgetFieldAdvancedFormatRules.vue
  apps/web/src/common/modules/widgets/_widget-fields/advanced-format-rules/type.ts
  apps/web/src/common/modules/widgets/_widget-fields/category-by/WidgetFieldCategoryBy.vue
  apps/web/src/common/modules/widgets/_widget-fields/category-by/type.ts
  apps/web/src/common/modules/widgets/_widget-fields/color-schema/WidgetFieldColorSchema.vue
  apps/web/src/common/modules/widgets/_widget-fields/color-schema/type.ts
  apps/web/src/common/modules/widgets/_widget-fields/format-rules/WidgetFieldFormatRules.vue
  apps/web/src/common/modules/widgets/_widget-fields/format-rules/type.ts
  apps/web/src/common/modules/widgets/_widget-fields/table-data-field/type.ts
  apps/web/src/common/modules/widgets/_widgets/color-coded-heatmap/ColorCodedHeatmap.vue
  apps/web/src/common/modules/widgets/_widgets/color-coded-table-heatmap/ColorCodedTableHeatmap.vue
  apps/web/src/common/modules/widgets/_widgets/gauge/Gauge.vue
  apps/web/src/common/modules/widgets/_widgets/heatmap/Heatmap.vue
  apps/web/src/common/modules/widgets/_widgets/treemap/Treemap.vue
  apps/web/src/common/modules/widgets/types/widget-field-type.ts
  apps/web/src/common/modules/widgets/types/widget-field-value-type.ts
Labels: pass/signedoff

#4683 feat: migrate LineChart, ClusteredColumnChart
  apps/web/src/common/modules/widgets/_helpers/widget-date-helper.ts
  apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/ClusteredColumnChart.vue
  apps/web/src/common/modules/widgets/_widgets/line-chart/LineChart.vue
  apps/web/src/services/dashboards/helpers/widget-migration-helper.ts
Labels: pass/signedoff

#4686 feat: apply new data field to widgets
  apps/web/src/common/modules/widgets/_helpers/widget-date-helper.ts
  apps/web/src/common/modules/widgets/_widget-fields/table-data-field/WidgetFieldTableDataField.vue
  apps/web/src/common/modules/widgets/_widgets/color-coded-table-heatmap/ColorCodedTableHeatmap.vue
  apps/web/src/common/modules/widgets/_widgets/heatmap/Heatmap.vue
  apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/StackedColumnChart.vue
  apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/StackedHorizontalBarChart.vue
  apps/web/src/services/dashboards/helpers/widget-migration-helper.ts
Labels: pass/signedoff

#4687 fix: fix `dateRange` for separated date
  apps/web/src/common/modules/widgets/_composables/use-widget-options-complex-validation.ts
  apps/web/src/common/modules/widgets/_helpers/widget-date-helper.ts
  apps/web/src/common/modules/widgets/_helpers/widget-load-helper.ts
  apps/web/src/common/modules/widgets/_widget-fields/table-data-field/WidgetFieldTableDataField.vue
  apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/ClusteredColumnChart.vue
  apps/web/src/common/modules/widgets/_widgets/color-coded-table-heatmap/ColorCodedTableHeatmap.vue
  apps/web/src/common/modules/widgets/_widgets/heatmap/Heatmap.vue
  apps/web/src/common/modules/widgets/_widgets/line-chart/LineChart.vue
  apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/StackedColumnChart.vue
  apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/StackedHorizontalBarChart.vue
Labels: pass/signedoff

#4690 chore: fix select dropdown style
  apps/web/src/services/cost-explorer/components/CostAnalysisDataTypeDropdown.vue
  apps/web/src/services/cost-explorer/components/CostAnalysisQuerySection.vue
Labels: pass/signedoff

#4691 chore: fix typescript error
  apps/web/src/common/modules/widgets/_widgets/line-chart/LineChart.vue
  apps/web/src/common/modules/widgets/_widgets/table/Table.vue
  apps/web/src/common/modules/widgets/_widgets/table/_component/WidgetDataTable.vue
Labels: pass/signedoff

#4692 upload 'ic_microsoft_auth'
  packages/mirinae/src/foundation/icons/icon-assets/ic_microsoft_auth.svg
Labels: pass/signedoff

#4693 upload 'ic_notification-protocol_envelope'
  packages/mirinae/src/foundation/icons/icon-assets/ic_notification-protocol_envelope.svg
Labels: pass/signedoff

#4695 feat(project-detail): create new project detail page & apply new planning
  apps/web/src/services/project/ProjectLSB.vue
  apps/web/src/services/project/components/ProjectMainTree.vue
  apps/web/src/services/project/components/ProjectMemberInviteModal.vue
  apps/web/src/services/project/pages/ProjectDetailPageNew.vue
Labels: pass/signedoff

#4696 feat: create LandingWorkspaceGroupAddUserModal
  apps/web/src/schema/identity/workspace-group-user/api-verbs/add.ts
  apps/web/src/schema/identity/workspace-group-user/model.ts
  apps/web/src/services/advanced/components/WorkspaceGroupAddWorkspacesModal.vue
  apps/web/src/services/landing/components/workspace-landing/LandingAllWorkspaces.vue
  apps/web/src/services/landing/components/workspace-landing/LandingContainer.vue
  apps/web/src/services/landing/components/workspace-landing/LandingContents.vue
  apps/web/src/services/landing/components/workspace-landing/LandingEmptyContents.vue
  apps/web/src/services/landing/components/workspace-landing/LandingHeader.vue
  apps/web/src/services/landing/components/workspace-landing/LandingRecentVisits.vue
  apps/web/src/services/landing/components/workspace-landing/LandingSearch.vue
  apps/web/src/services/landing/components/workspace-landing/LandingWorkspaceRecentList.vue
  apps/web/src/services/landing/components/workspace-landing/landing-group-workspaces/LandingGroupWorkspaces.vue
  apps/web/src/services/landing/components/workspace-landing/landing-group-workspaces/LandingWorkspaceBoard.vue
  apps/web/src/services/landing/components/workspace-landing/landing-group-workspaces/LandingWorkspaceGroupAddUsersModal.vue
  apps/web/src/services/landing/components/workspace-landing/landing-group-workspaces/LandingWorkspaceGroupManageOverlay.vue
  apps/web/src/services/landing/components/workspace-landing/landing-group-workspaces/LandingWorkspaceGroupTab.vue
  apps/web/src/services/landing/components/workspace-landing/landing-group-workspaces/LandingWorkspaceGroupTabGroupUser.vue
  apps/web/src/services/landing/components/workspace-landing/landing-group-workspaces/LandingWorkspaceGroupTabWorkspace.vue
  apps/web/src/services/landing/pages/WorkspaceLandingPage.vue
  apps/web/src/services/landing/routes/routes.ts
Labels: pass/signedoff

#4698 feat: create new project tags modal & add update/move
  apps/web/src/services/project/components/ProjectTagsInputGroup.vue
  apps/web/src/services/project/components/ProjectTagsModal.vue
  apps/web/src/services/project/pages/ProjectDetailPageNew.vue
Labels: pass/signedoff

#4700 feat: create dashboard folder tree & create dashboard-main-page-store
  apps/web/src/services/dashboards/components/dashboard-folder/DashboardFolderTree.vue
  apps/web/src/services/dashboards/components/dashboard-folder/DashboardFolderTreeItem.vue
  apps/web/src/services/dashboards/components/dashboard-folder/DashboardMainFolderFormModal.vue
  apps/web/src/services/dashboards/components/dashboard-main/DashboardMainFolderFormModal.vue
  apps/web/src/services/dashboards/pages/DashboardsMainPage.vue
  apps/web/src/services/dashboards/stores/dashboard-main-page-store.ts
  apps/web/src/services/dashboards/types/dashboard-folder-type.ts
  packages/language-pack/en.json
  packages/language-pack/ja.json
  packages/language-pack/ko.json
Labels: pass/signedoff

#4701 feat: create removeGroupUser modal
  apps/web/src/schema/identity/workspace-group-user/api-verbs/remove.ts
  apps/web/src/services/landing/components/workspace-landing/landing-group-workspaces/LandingWorkspaceGroupRemoveUserModal.vue
  apps/web/src/services/landing/components/workspace-landing/landing-group-workspaces/LandingWorkspaceGroupTabGroupUser.vue
  apps/web/src/services/landing/store/landing-page-store.ts
  packages/language-pack/en.json
  packages/language-pack/ja.json
  packages/language-pack/ko.json
Labels: pass/signedoff

#4703 feat: add workspaceTab to LandingOverlay
  apps/web/src/services/landing/components/workspace-landing/landing-group-workspaces/LandingGroupWorkspaces.vue
  apps/web/src/services/landing/components/workspace-landing/landing-group-workspaces/LandingWorkspaceGroupManageOverlay.vue
  apps/web/src/services/landing/components/workspace-landing/landing-group-workspaces/LandingWorkspaceGroupRemoveUserModal.vue
  apps/web/src/services/landing/components/workspace-landing/landing-group-workspaces/LandingWorkspaceGroupTabGroupUser.vue
  apps/web/src/services/landing/components/workspace-landing/landing-group-workspaces/LandingWorkspaceGroupTabWorkspace.vue
  apps/web/src/services/landing/store/landing-page-store.ts
Labels: pass/signedoff

#4704 fix(admin-workspace-group-page): change the fetch method
  apps/web/src/services/advanced/components/WorkspaceGroupAddUsersModal.vue
  apps/web/src/services/advanced/components/WorkspaceGroupAddWorkspacesModal.vue
  apps/web/src/services/advanced/components/WorkspaceGroupDeleteStatusModal.vue
  apps/web/src/services/advanced/components/WorkspaceGroupTabGroupUser.vue
  apps/web/src/services/advanced/components/WorkspaceGroupTabWorkspace.vue
  apps/web/src/services/advanced/components/WorkspaceGroupTable.vue
  apps/web/src/services/advanced/composables/use-select-drop-down-list.ts
  apps/web/src/services/advanced/pages/admin/AdminWorkspaceGroupPage.vue
  apps/web/src/services/advanced/store/workspace-group-page-store.ts
  apps/web/src/store/reference/workspace-reference-store.ts
Labels: pass/signedoff

#4707 fix: fix workspaceGroup delete modal store logic
  apps/web/src/services/advanced/components/WorkspaceGroupAddUsersModal.vue
  apps/web/src/services/advanced/components/WorkspaceGroupCreateModal.vue
  apps/web/src/services/advanced/components/WorkspaceGroupDeleteModal.vue
  apps/web/src/services/advanced/components/WorkspaceGroupHeader.vue
  apps/web/src/services/advanced/components/WorkspaceGroupTable.vue
  apps/web/src/services/advanced/pages/admin/AdminWorkspaceGroupPage.vue
  apps/web/src/services/advanced/store/workspace-group-page-store.ts
Labels: pass/signedoff

#4709 feat: apply new api "change-folder"
  apps/web/src/schema/dashboard/_types/dashboard-type.ts
  apps/web/src/schema/dashboard/private-dashboard/api-verbs/change-folder.ts
  apps/web/src/schema/dashboard/public-dashboard/api-verbs/change-folder.ts
  apps/web/src/services/dashboards/components/dashboard-folder/DashboardFolderMoveModal.vue
  apps/web/src/services/dashboards/components/dashboard-folder/DashboardFolderTree.vue
Labels: pass/signedoff

#4711 fix: fix user page according to changed RoleBinding api
  apps/web/src/schema/identity/workspace-user/model.ts
  apps/web/src/services/advanced/components/WorkspaceGroupTabWorkspace.vue
  apps/web/src/services/iam/components/UserManagementTab.vue
  apps/web/src/services/iam/components/UserManagementTable.vue
  apps/web/src/services/iam/helpers/role-binding-helpers.ts
  apps/web/src/services/iam/store/user-page-store.ts
Labels: pass/signedoff

#4714 chore: add active condition
  apps/web/src/services/iam/components/AppManagementFormModal.vue
Labels: pass/signedoff

#4715 fix(workspace-group-user-tab): change to console filter
  apps/web/src/schema/identity/workspace-group-user/model.ts
  apps/web/src/services/advanced/components/WorkspaceGroupTabGroupUser.vue
  apps/web/src/services/advanced/components/WorkspaceGroupTabWorkspace.vue
  apps/web/src/services/advanced/store/workspace-group-page-store.ts
Labels: pass/signedoff

#4716 feat: apply access permissions at each pages
  apps/web/src/common/modules/navigations/top-bar/modules/top-bar-header/TopBarWorkspaces.vue
  apps/web/src/lib/access-control/page-access-helper.ts
  apps/web/src/lib/menu/config.ts
  apps/web/src/services/advanced/pages/admin/AdminWorkspacesPage.vue
  apps/web/src/services/dashboards/DashboardsLSB.vue
  apps/web/src/services/dashboards/pages/DashboardsMainPage.vue
  apps/web/src/services/workspace-home/components/WorkspaceInfo.vue
  apps/web/src/store/modules/user/actions.ts
  apps/web/src/store/modules/user/getters.ts
  apps/web/src/store/modules/user/type.ts
Labels: pass/signedoff

#4718 fix: fixed currency store
  apps/web/src/services/advanced/components/WorkspaceGroupTabWorkspace.vue
  apps/web/src/services/advanced/components/WorkspaceManagementTable.vue
  apps/web/src/services/advanced/pages/admin/AdminDomainSettingsAutoDormancyConfigurationPage.vue
  apps/web/src/services/advanced/store/workspace-group-page-store.ts
  apps/web/src/services/advanced/store/workspace-page-store.ts
  apps/web/src/services/asset-inventory/components/ServiceAccountUsageOverview.vue
  apps/web/src/services/asset-inventory/pages/ServiceAccountDetailPage.vue
  apps/web/src/services/asset-inventory/pages/ServiceAccountPage.vue
  apps/web/src/services/asset-inventory/stores/service-account-page-store.ts
Labels: pass/signedoff

#4717 fix: fix TopBarProfile role field
  apps/web/src/common/modules/navigations/top-bar/modules/top-bar-toolset/modules/top-bar-profile/TopBarProfile.vue
  apps/web/src/lib/site-initializer/workspace.ts
  apps/web/src/services/landing/components/workspace-landing/landing-group-workspaces/LandingGroupWorkspaces.vue
  apps/web/src/store/app-context/app-context-store.ts
  apps/web/src/store/app-context/workspace/user-workspace-store.ts
Labels: pass/signedoff

#4719 feat(p-tab): renewal `PTab` component
  packages/mirinae/src/hooks/tab/index.ts
  packages/mirinae/src/navigation/tabs/tab/PTab.mdx
  packages/mirinae/src/navigation/tabs/tab/PTab.stories.ts
  packages/mirinae/src/navigation/tabs/tab/PTab.vue
  packages/mirinae/src/navigation/tabs/tab/story-helper.ts
  packages/mirinae/src/navigation/tabs/tab/type.ts
Labels: pass/signedoff

#4713 feat: create clone modal
  apps/web/src/services/dashboards/components/dashboard-folder/DashboardFolderCloneModal.vue
  apps/web/src/services/dashboards/components/dashboard-folder/DashboardFolderFormModal.vue
  apps/web/src/services/dashboards/components/dashboard-folder/DashboardFolderTree.vue
  apps/web/src/services/dashboards/components/dashboard-main/DashboardMainBoardList.vue
  apps/web/src/services/dashboards/pages/DashboardsMainPage.vue
  apps/web/src/services/dashboards/stores/dashboard-main-page-store.ts
  packages/language-pack/en.json
  packages/utils/src/index.ts
Labels: pass/signedoff

#4721 refactor(folder-tree): use props instead of page store
  apps/web/src/services/dashboards/components/dashboard-folder/DashboardFolderCloneModal.vue
  apps/web/src/services/dashboards/components/dashboard-folder/DashboardFolderDeleteModal.vue
  apps/web/src/services/dashboards/components/dashboard-folder/DashboardFolderMoveModal.vue
  apps/web/src/services/dashboards/components/dashboard-folder/DashboardFolderTree.vue
  apps/web/src/services/dashboards/pages/DashboardsMainPage.vue
  apps/web/src/services/dashboards/stores/dashboard-main-page-store.ts
  apps/web/src/services/dashboards/types/dashboard-folder-type.ts
Labels: pass/signedoff

#4723 chore: add readonly condition
  apps/web/src/services/asset-inventory/components/CloudServiceHistoryDetailNoteTab.vue
Labels: pass/signedoff

#4724 feat(project-dashboard): create project-dashboard tab and page
  apps/web/src/services/project/components/ProjectDetailTab.vue
  apps/web/src/services/project/pages/ProjectDashboardPage.vue
  apps/web/src/services/project/pages/ProjectDetailTabPage.vue
  apps/web/src/services/project/pages/ProjectSummaryPage.vue
  apps/web/src/services/project/routes/routes.ts
  apps/web/src/store/dashboard/dashboard-store.ts
Labels: pass/signedoff

#4726 feat(project-dashboard): apply alert/webhook planning
  apps/web/src/schema/monitoring/webhook/api-verbs/list.ts
  apps/web/src/services/project/pages/ProjectDetailPageNew.vue
Labels: pass/signedoff

#4729 chore(project-dashboard): solve small issues
  apps/web/src/services/project/pages/ProjectDetailPageNew.vue
  apps/web/src/services/project/pages/ProjectDetailTabPage.vue
  apps/web/src/services/project/pages/ProjectSummaryPage.vue
  apps/web/src/services/project/routes/routes.ts
  packages/mirinae/src/navigation/tabs/tab/PTab.vue
Labels: pass/signedoff

#4728 feat: disable buttons by condition
  apps/web/src/services/dashboards/components/dashboard-folder/DashboardFolderCloneModal.vue
  apps/web/src/services/dashboards/components/dashboard-folder/DashboardFolderFormModal.vue
  apps/web/src/services/dashboards/components/dashboard-folder/DashboardFolderMoveModal.vue
  apps/web/src/services/dashboards/components/dashboard-folder/DashboardFolderTree.vue
  apps/web/src/services/dashboards/components/dashboard-folder/DashboardFolderTreeItem.vue
  apps/web/src/services/dashboards/pages/DashboardsMainPage.vue
  apps/web/src/services/dashboards/stores/dashboard-main-page-store.ts
Labels: pass/signedoff

#4730 fix(project-landing): edit project-landing page design
  apps/web/src/services/project/components/ProjectMain.vue
  apps/web/src/services/project/components/ProjectMainProjectCard.vue
  apps/web/src/services/project/components/ProjectMainProjectGroupCard.vue
  apps/web/src/services/project/pages/ProjectMainPage.vue
Labels: pass/signedoff, fail/signedoff

#4731 feat: apply admin mode dashboard
  apps/web/src/services/dashboards/DashboardsLSB.vue
  apps/web/src/services/dashboards/components/dashboard-folder/DashboardFolderFormModal.vue
  apps/web/src/services/dashboards/pages/DashboardsMainPage.vue
  apps/web/src/services/dashboards/stores/dashboard-main-page-store.ts
Labels: pass/signedoff

#4708 chore: Merge branch 'master' into feature-feedback-v2
  apps/web/package.json
  apps/web/src/services/cost-explorer/components/CostAnalysisDataTypeDropdown.vue
  apps/web/src/services/cost-explorer/components/CostAnalysisQuerySection.vue
  package-lock.json
  package.json
  packages/mirinae/package.json
Labels: fail/signedoff

#4735 feat: add mfa type (MS) - only Mark up
  apps/web/src/services/my-page/components/UserAccountMultiFactorAuth.vue
  apps/web/src/services/my-page/components/UserAccountMultiFactorAuthItems.vue
  apps/web/src/services/my-page/components/UserAccountMultiFactorAuthModal.vue
  apps/web/src/services/my-page/components/UserAccountMultiFactorAuthModalEmailInfo.vue
  apps/web/src/services/my-page/components/UserAccountMultiFactorAuthModalFolding.vue
  apps/web/src/services/my-page/types/multi-factor-auth-type.ts
Labels: pass/signedoff

#4733 feat: apply accumulated toggle to cost analysis chart
  apps/web/src/services/cost-explorer/components/CostAnalysisChart.vue
  apps/web/src/services/cost-explorer/components/CostAnalysisStackedColumnChart.vue
Labels: pass/signedoff

#4737 chore: apply minor feedback (style, type)
  apps/web/src/common/modules/favorites/favorite-button/FavoriteButton.vue
  apps/web/src/lib/menu/menu-info.ts
  apps/web/src/services/cost-explorer/components/DataSourceManagementTabLinkedAccountTable.vue
Labels: pass/signedoff

#4738 fix: prevent setting loading to false on api cancellation in CostAnalysisChart
  apps/web/src/services/cost-explorer/components/CostAnalysisChart.vue
  apps/web/src/services/cost-explorer/components/CostAnalysisStackedColumnChart.vue
Labels: pass/signedoff

#4739 fix: update data mapping of user_count field
  apps/web/src/services/advanced/components/WorkspaceManagementTable.vue
  apps/web/src/services/advanced/constants/workspace-constant.ts
  apps/web/src/services/advanced/store/workspace-page-store.ts
Labels: pass/signedoff

#4740 feat: remove added workspace in workspace dropdown menu
  apps/web/src/services/advanced/components/WorkspaceGroupAddUsersModal.vue
  apps/web/src/services/advanced/components/WorkspaceGroupAddWorkspacesModal.vue
  apps/web/src/services/advanced/components/WorkspaceGroupDeleteStatusModal.vue
  apps/web/src/services/advanced/components/WorkspaceGroupTabGroupUser.vue
  apps/web/src/services/advanced/composables/use-select-drop-down-list.ts
  apps/web/src/services/landing/components/workspace-landing/landing-group-workspaces/LandingWorkspaceGroupAddUsersModal.vue
Labels: pass/signedoff

#4742 fix(project-main-page): update project main action(project and project group) structure
  apps/web/src/services/project/components/ProjectFormModal.vue
  apps/web/src/services/project/components/ProjectMainCardList.vue
  apps/web/src/services/project/components/ProjectMainDeleteModal.vue
  apps/web/src/services/project/components/ProjectMainProjectCard.vue
  apps/web/src/services/project/components/ProjectMainProjectGroupDeleteCheckModal.vue
  apps/web/src/services/project/components/ProjectMainProjectTree.vue
  apps/web/src/services/project/components/ProjectMemberTab.vue
  apps/web/src/services/project/pages/ProjectMainPage.vue
  apps/web/src/services/project/pages/ProjectMemberPage.vue
  apps/web/src/services/project/routes/routes.ts
  apps/web/src/services/project/stores/project-page-store.ts
Labels: pass/signedoff

#4743 chore(dashboard): fix minors
  apps/web/src/common/modules/widgets/_helpers/widget-load-helper.ts
  apps/web/src/services/dashboards/DashboardsLSB.vue
  apps/web/src/services/dashboards/components/dashboard-folder/DashboardFolderDeleteModal.vue
Labels: pass/signedoff

#4744 fix(project-main-page): apply global action state to project group
  apps/web/src/services/project/components/ProjectMainDeleteModal.vue
  apps/web/src/services/project/components/ProjectMainProjectCard.vue
  apps/web/src/services/project/components/ProjectMainProjectGroupCard.vue
  apps/web/src/services/project/pages/ProjectMainPage.vue
  apps/web/src/services/project/stores/project-page-store.ts
Labels: pass/signedoff

#4746 feat: create new project detail page & apply new action modals
  apps/web/src/services/project/pages/ProjectDetailPage.vue
  apps/web/src/services/project/pages/ProjectDetailPageLegacy.vue
  apps/web/src/services/project/pages/ProjectDetailPageNew.vue
  apps/web/src/services/project/pages/ProjectMainPage.vue
  apps/web/src/services/project/routes/routes.ts
Labels: pass/signedoff

#4748 fix(project-main): apply new design
  apps/web/src/services/project/ProjectLSB.vue
  apps/web/src/services/project/components/ProjectMain.vue
  packages/mirinae/src/inputs/context-menu/PContextMenu.vue
Labels: pass/signedoff

#4750 chore: change file name
  apps/web/src/schema/dashboard/_types/folder-type.ts
  apps/web/src/services/dashboards/components/dashboard-create/DashboardCreateStep2.vue
  apps/web/src/services/dashboards/components/dashboard-create/DashboardCreateStep2BlankTemplate.vue
  apps/web/src/services/dashboards/components/dashboard-folder/DashboardFolderCloneModal.vue
  apps/web/src/services/dashboards/components/dashboard-folder/DashboardFolderDeleteModal.vue
  apps/web/src/services/dashboards/components/dashboard-folder/DashboardFolderShareModal.vue
  apps/web/src/services/dashboards/components/dashboard-folder/DashboardFolderTree.vue
  apps/web/src/services/dashboards/components/dashboard-folder/DashboardFolderTreeItem.vue
  apps/web/src/services/dashboards/helpers/dashboard-tree-data-helper.ts
  apps/web/src/services/dashboards/pages/DashboardCreatePage.vue
  apps/web/src/services/dashboards/stores/dashboard-main-page-store.ts
  apps/web/src/services/dashboards/types/dashboard-folder-type.ts
  packages/language-pack/en.json
  packages/language-pack/ja.json
  packages/language-pack/ko.json
Labels: pass/signedoff

#4751 refactor: update variable names in dashboard-store
  apps/web/src/common/modules/favorites/favorite-button/FavoriteButton.vue
  apps/web/src/common/modules/navigations/top-bar/modules/top-bar-toolset/modules/top-bar-favorite/modules/TopBarFavoriteContextMenu.vue
  apps/web/src/services/dashboards/DashboardsLSB.vue
  apps/web/src/services/dashboards/components/dashboard-create/DashboardCreateStep1.vue
  apps/web/src/services/dashboards/components/dashboard-create/DashboardCreateStep2SingleCase.vue
  apps/web/src/services/dashboards/components/dashboard-detail/DashboardCloneModal.vue
  apps/web/src/services/dashboards/helpers/dashboard-tree-data-helper.ts
  apps/web/src/services/dashboards/pages/DashboardCreatePage.vue
  apps/web/src/services/dashboards/pages/DashboardsMainPage.vue
  apps/web/src/services/dashboards/stores/dashboard-create-page-store.ts
  apps/web/src/services/dashboards/stores/dashboard-main-page-store.ts
  apps/web/src/services/workspace-home/components/UserConfigRecent.vue
  apps/web/src/store/dashboard/dashboard-store.ts
Labels: pass/signedoff

#4747 fix(collector-detail-page): fix project routing in admin mode
  apps/web/src/services/asset-inventory/components/CollectorAdditionalRuleContent.vue
  apps/web/src/store/reference/project-reference-store.ts
Labels: pass/signedoff

#4753 refactor: move codes to store
  apps/web/src/services/dashboards/components/dashboard-folder/DashboardFolderCloneModal.vue
  apps/web/src/store/dashboard/dashboard-store.ts
Labels: pass/signedoff

#4752 feat(folder): create public folder reference store
  apps/web/src/lib/site-initializer/api-client.ts
  apps/web/src/store/reference/all-reference-store.ts
  apps/web/src/store/reference/public-folder-reference-store.ts
Labels: pass/signedoff

#4755 Feature/sdfs
  apps/web/src/services/dashboards/components/dashboard-create/DashboardCreateStep1.vue
  apps/web/src/services/dashboards/components/dashboard-create/DashboardCreateStep2BundleCase.vue
  apps/web/src/services/dashboards/components/dashboard-create/DashboardCreateStep2SingleCase.vue
  apps/web/src/services/dashboards/components/dashboard-folder/DashboardFolderCloneModal.vue
  apps/web/src/services/dashboards/components/dashboard-folder/DashboardFolderTree.vue
  apps/web/src/services/dashboards/components/dashboard-folder/DashboardFolderTreeItem.vue
Labels: pass/signedoff

#4756 fix: update cost analysis chart legend based on data
  apps/web/src/services/cost-explorer/components/CostAnalysisChart.vue
  apps/web/src/services/cost-explorer/components/CostAnalysisStackedColumnChart.vue
Labels: pass/signedoff

#4757 fix: fix incorrect types and allow favorite updates without reference data
  apps/web/src/common/modules/favorites/favorite-button/FavoriteButton.vue
  apps/web/src/common/modules/favorites/favorite-button/store/favorite-store.ts
  apps/web/src/lib/helper/config-data-helper.ts
Labels: pass/signedoff

#4759 feat(data-table-filter): apply selection of operator to data-table-filter
  apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardAddContents.vue
  apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardAddForm.vue
  apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardFilters.vue
  apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardFiltersItem.vue
  apps/web/src/common/modules/widgets/_constants/data-table-constant.ts
  apps/web/src/common/modules/widgets/types/widget-data-table-type.ts
  apps/web/src/common/modules/widgets/types/widget-model.ts
Labels: pass/signedoff

#4758 feat: show "labels" and add click event to it & etc...
  apps/web/src/services/dashboards/components/dashboard-detail/DashboardDetailHeader.vue
  apps/web/src/services/dashboards/components/dashboard-folder/DashboardFolderTreeItem.vue
  apps/web/src/services/dashboards/components/dashboard-main/DashboardLSBTree.vue
  apps/web/src/services/dashboards/pages/DashboardsMainPage.vue
  apps/web/src/services/dashboards/stores/dashboard-main-page-store.ts
  apps/web/src/store/dashboard/dashboard-store.ts
Labels: pass/signedoff

#4761 chore: apply data-table operator design
  apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardFiltersItem.vue
Labels: pass/signedoff

#4762 chore: fix QA thigns
  apps/web/src/lib/helper/config-data-helper.ts
  apps/web/src/schema/dashboard/_types/dashboard-type.ts
  apps/web/src/services/asset-inventory/components/CollectorPluginContents.vue
  apps/web/src/services/dashboards/components/dashboard-detail/DashboardDetailHeader.vue
  apps/web/src/services/dashboards/components/dashboard-detail/DashboardFolderSingleMoveModal.vue
  apps/web/src/services/dashboards/components/dashboard-detail/DashboardVariablesV2.vue
  apps/web/src/services/dashboards/components/dashboard-detail/DashboardWidgetContainerV2.vue
  apps/web/src/services/dashboards/components/dashboard-folder/DashboardFolderBundleMoveModal.vue
  apps/web/src/services/dashboards/components/dashboard-folder/DashboardFolderCloneModal.vue
  apps/web/src/services/dashboards/components/dashboard-folder/DashboardFolderDeleteModal.vue
  apps/web/src/services/dashboards/components/dashboard-folder/DashboardFolderMoveModal.vue
  apps/web/src/services/dashboards/components/dashboard-folder/DashboardFolderShareModal.vue
  apps/web/src/services/dashboards/components/dashboard-folder/DashboardFolderTree.vue
  apps/web/src/services/dashboards/components/dashboard-folder/DashboardFolderTreeItem.vue
  apps/web/src/services/dashboards/components/dashboard-main/DashboardLSBTree.vue
  apps/web/src/services/dashboards/components/dashboard-main/DashboardMainBoardList.vue
  apps/web/src/services/dashboards/pages/DashboardsMainPage.vue
  apps/web/src/services/dashboards/stores/dashboard-detail-info-store.ts
  apps/web/src/services/dashboards/stores/dashboard-main-page-store.ts
  apps/web/src/services/dashboards/types/dashboard-api-schema-type.ts
  apps/web/src/store/dashboard/dashboard-store.ts
  packages/language-pack/en.json
  packages/language-pack/ja.json
  packages/language-pack/ko.json
  packages/mirinae/src/data-display/label/PLabel.vue
  packages/mirinae/src/feedbacks/modals/button-modal/PButtonModal.vue
Labels: pass/signedoff

#4764 feat: set back button to project detail page
  apps/web/src/common/modules/widgets/_widget-fields/table-data-field/WidgetFieldTableDataField.vue
  apps/web/src/services/dashboards/components/dashboard-create/DashboardCreateStep1.vue
  apps/web/src/services/dashboards/pages/DashboardsMainPage.vue
  apps/web/src/services/dashboards/stores/dashboard-main-page-store.ts
  apps/web/src/services/project/pages/ProjectDetailPage.vue
  apps/web/src/services/project/pages/ProjectMainPage.vue
Labels: pass/signedoff

#4765 feat(data-table): create keyword filter (`contain_in`, `not_contain_in`)
  apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardAddContents.vue
  apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardFilters.vue
  apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardFiltersItem.vue
  apps/web/src/common/modules/widgets/_constants/data-table-constant.ts
Labels: pass/signedoff

#4770 fix(data-table-filter): apply keyword-filter disabled
  apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardFilters.vue
  apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardFiltersItem.vue
  apps/web/src/common/modules/widgets/_constants/data-table-constant.ts
Labels: pass/signedoff

#4767 feat(mirinae): update Popover and fix cost analysis page filter css bugs
  apps/web/src/common/components/buttons/PdfDownloadButton.vue
  apps/web/src/common/components/editor/MenuBar.vue
  apps/web/src/services/asset-inventory/components/MetricExplorerLSB.vue
  apps/web/src/services/asset-inventory/components/MetricExplorerQuerySection.vue
  apps/web/src/services/cost-explorer/components/BudgetDetailInfo.vue
  apps/web/src/services/cost-explorer/components/CostAnalysisQuerySection.vue
  apps/web/src/services/dashboards/components/DashboardLabelsButton.vue
  apps/web/src/services/info/components/NoticeDetail.vue
  apps/web/src/services/landing/components/LandingWorkspaceBoard.vue
  package-lock.json
  packages/mirinae/package.json
  packages/mirinae/src/data-display/popover/PPopover.mdx
  packages/mirinae/src/data-display/popover/PPopover.stories.ts
  packages/mirinae/src/data-display/popover/PPopover.vue
  packages/mirinae/src/data-display/popover/story-helper.ts
Labels: pass/signedoff

#4775 feat: disable workspaces of other workspaceGroup & add ellipsis & tooltip
  apps/web/src/services/advanced/components/WorkspaceGroupAddUsersModal.vue
  apps/web/src/services/advanced/components/WorkspaceGroupAddWorkspacesModal.vue
Labels: pass/signedoff

#4777 feat: add `WidgetCustomLegend` and apply it to widget
  apps/web/src/common/modules/widgets/_components/WidgetCustomLagend.vue
  apps/web/src/common/modules/widgets/_widget-fields/display-annotation/WidgetFieldDisplayAnnotation.vue
  apps/web/src/common/modules/widgets/_widget-fields/number-format/WidgetFieldNumberFormat.vue
  apps/web/src/common/modules/widgets/_widgets/color-coded-heatmap/ColorCodedHeatmap.vue
  apps/web/src/common/modules/widgets/_widgets/color-coded-table-heatmap/ColorCodedTableHeatmap.vue
  apps/web/src/common/modules/widgets/types/widget-legend-typs.ts
Labels: pass/signedoff

#4779 feat: get dashboard from page store
  apps/web/src/common/modules/favorites/favorite-button/FavoriteButton.vue
  apps/web/src/common/modules/navigations/top-bar/modules/top-bar-toolset/modules/top-bar-favorite/modules/TopBarFavoriteContextMenu.vue
  apps/web/src/services/dashboards/DashboardsLSB.vue
  apps/web/src/services/dashboards/components/dashboard-create/DashboardCreateStep1.vue
  apps/web/src/services/dashboards/components/dashboard-folder/DashboardFolderBundleMoveModal.vue
  apps/web/src/services/dashboards/components/dashboard-folder/DashboardFolderCloneModal.vue
  apps/web/src/services/dashboards/components/dashboard-folder/DashboardFolderDeleteModal.vue
  apps/web/src/services/dashboards/components/dashboard-folder/DashboardFolderFormModal.vue
  apps/web/src/services/dashboards/components/dashboard-main/DashboardLSBTree.vue
  apps/web/src/services/dashboards/components/dashboard-main/DashboardMainBoardList.vue
  apps/web/src/services/dashboards/pages/DashboardsMainPage.vue
  apps/web/src/services/dashboards/stores/dashboard-main-page-store.ts
  apps/web/src/services/workspace-home/components/UserConfigRecent.vue
  apps/web/src/store/dashboard/dashboard-store.ts
Labels: pass/signedoff

#4778 fix(project): update usage of form modal (project, projectGroup)
  apps/web/src/services/project/ProjectContainer.vue
  apps/web/src/services/project/ProjectLSB.vue
  apps/web/src/services/project/components/ProjectDetailTabHeader.vue
  apps/web/src/services/project/components/ProjectFormModal.vue
  apps/web/src/services/project/components/ProjectMainProjectGroupCard.vue
  apps/web/src/services/project/components/ProjectMainProjectGroupFormModal.vue
  apps/web/src/services/project/pages/ProjectMainPage.vue
Labels: pass/signedoff

#4781 feat(project-dashboard): add remove users
  apps/web/src/lib/site-initializer/api-client.ts
  apps/web/src/services/project/components/ProjectDetailTabHeader.vue
  apps/web/src/services/project/components/ProjectMemberInviteModal.vue
Labels: pass/signedoff

#4780 fix(user-page-store): update to setup store
  apps/web/src/services/advanced/pages/admin/AdminWorkspacesPage.vue
  apps/web/src/services/iam/components/UserManagementAddModal.vue
  apps/web/src/services/iam/components/UserManagementAddUser.vue
  apps/web/src/services/iam/components/UserManagementFormAdminRole.vue
  apps/web/src/services/iam/components/UserManagementFormInfoForm.vue
  apps/web/src/services/iam/components/UserManagementFormModal.vue
  apps/web/src/services/iam/components/UserManagementFormMultiFactorAuth.vue
  apps/web/src/services/iam/components/UserManagementFormPasswordForm.vue
  apps/web/src/services/iam/components/UserManagementHeader.vue
  apps/web/src/services/iam/components/UserManagementStatusModal.vue
  apps/web/src/services/iam/components/UserManagementTab.vue
  apps/web/src/services/iam/components/UserManagementTabDetail.vue
  apps/web/src/services/iam/components/UserManagementTabProjects.vue
  apps/web/src/services/iam/components/UserManagementTabTag.vue
  apps/web/src/services/iam/components/UserManagementTabWorkspace.vue
  apps/web/src/services/iam/components/UserManagementTable.vue
  apps/web/src/services/iam/components/UserManagementTableToolbox.vue
  apps/web/src/services/iam/pages/UserMainPage.vue
  apps/web/src/services/iam/store/user-page-store.ts
  apps/web/src/services/workspace-home/components/WorkspaceInfo.vue
Labels: pass/signedoff

#4783 fix: do not show project dashboards in workspace mode
  apps/web/src/common/modules/widgets/_widgets/color-coded-table-heatmap/ColorCodedTableHeatmap.vue
  apps/web/src/services/dashboards/DashboardsLSB.vue
  apps/web/src/services/dashboards/components/dashboard-folder/DashboardFolderCloneModal.vue
  apps/web/src/services/dashboards/components/dashboard-folder/DashboardFolderShareModal.vue
  apps/web/src/services/dashboards/components/dashboard-main/DashboardLSBTree.vue
  apps/web/src/services/dashboards/pages/DashboardsMainPage.vue
  apps/web/src/services/dashboards/stores/dashboard-main-page-store.ts
Labels: pass/signedoff

#4785 fix(dashboard-widgets): update widget-migration helper (update -> convert)
  apps/web/src/services/dashboards/helpers/widget-migration-helper.ts
  apps/web/src/services/dashboards/stores/dashboard-detail-info-store.ts
Labels: pass/signedoff

#4788 chore(cloud-service-page): small design fix
  apps/web/src/services/asset-inventory/pages/CloudServicePage.vue
Labels: pass/signedoff

#4787 feat(mirinae): apply floatingUI lib on context-menu-fixed-style hook
  apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardFilters.vue
  apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardSourceForm.vue
  apps/web/src/services/asset-inventory/components/MetricExplorerHeader.vue
  apps/web/src/services/cost-explorer/components/CostAnalysisFiltersAddMoreButton.vue
  apps/web/src/services/cost-explorer/components/CostAnalysisGranularityPeriodDropdown.vue
  apps/web/src/services/cost-explorer/components/CostAnalysisPeriodSelectDropdown.vue
  apps/web/src/services/cost-explorer/components/CostAnalysisQuerySection.vue
  apps/web/src/services/dashboards/components/DashboardCostWidgetValueOptionDropdown.vue
  apps/web/src/services/dashboards/components/DashboardVariablesMoreButton.vue
  apps/web/src/services/dashboards/components/DashboardWidgetMoreOptions.vue
  apps/web/src/services/project/pages/ProjectMainPage.vue
  apps/web/src/services/workspace-home/components/BookmarkHeader.vue
  packages/mirinae/src/data-display/popover/PPopover.vue
  packages/mirinae/src/hooks/context-menu-controller/__tests__/index.test.ts
  packages/mirinae/src/hooks/context-menu-controller/index.ts
  packages/mirinae/src/hooks/context-menu-fixed-style/index.ts
  packages/mirinae/src/inputs/dropdown/filterable-query-dropdown/PFilterableQueryDropdown.vue
  packages/mirinae/src/inputs/dropdown/select-dropdown/PSelectDropdown.stories.ts
  packages/mirinae/src/inputs/dropdown/select-dropdown/PSelectDropdown.vue
  packages/mirinae/src/inputs/dropdown/select-dropdown/story-helper.ts
  packages/mirinae/src/inputs/input/query-input/PQueryInput.vue
  packages/mirinae/src/inputs/search/search/PSearch.vue
  packages/mirinae/src/navigation/breadcrumbs/modules/BreadcrumbsEllipsisItem.vue
Labels: pass/signedoff

#4790 fix(cloud-service): apply new query spec
  apps/web/src/common/modules/widgets/DailyUpdates.vue
  apps/web/src/services/asset-inventory/components/CloudServiceListCard.vue
  apps/web/src/services/asset-inventory/components/CloudServices.vue
  apps/web/src/services/asset-inventory/components/MetricExplorerDataTable.vue
  apps/web/src/services/asset-inventory/constants/cloud-service-constant.ts
  apps/web/src/services/asset-inventory/pages/CloudServicePage.vue
  apps/web/src/services/asset-inventory/types/cloud-service-page-type.ts
  apps/web/src/services/cost-explorer/components/CostAnalysisDataTable.vue
  apps/web/src/services/dashboards/widgets/_composables/use-widget/use-widget-location.ts
  apps/web/src/services/project/components/ProjectSummaryAllSummaryWidget.vue
  apps/web/src/services/project/components/ProjectSummaryAllSummaryWidgetRegionService.vue
  apps/web/src/services/project/components/ProjectSummaryServiceAccountsWidget.vue
  apps/web/src/services/project/components/ProjectSummaryTrustedAdvisorWidget.vue
Labels: pass/signedoff

#4796 feat: merge feature-feedback-v2 and update Popover component(add boundary prop)
  apps/web/src/common/components/buttons/PdfDownloadButton.vue
  apps/web/src/common/components/editor/MenuBar.vue
  apps/web/src/common/modules/favorites/favorite-button/FavoriteButton.vue
  apps/web/src/common/modules/favorites/favorite-button/store/favorite-store.ts
  apps/web/src/common/modules/widgets/DailyUpdates.vue
  apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardFilters.vue
  apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardSourceForm.vue
  apps/web/src/lib/helper/config-data-helper.ts
  apps/web/src/lib/menu/menu-info.ts
  apps/web/src/services/asset-inventory/components/CloudServiceListCard.vue
  apps/web/src/services/asset-inventory/components/CloudServices.vue
  apps/web/src/services/asset-inventory/components/MetricExplorerDataTable.vue
  apps/web/src/services/asset-inventory/components/MetricExplorerHeader.vue
  apps/web/src/services/asset-inventory/components/MetricExplorerLSB.vue
  apps/web/src/services/asset-inventory/components/MetricExplorerQuerySection.vue
  apps/web/src/services/asset-inventory/constants/cloud-service-constant.ts
  apps/web/src/services/asset-inventory/pages/CloudServicePage.vue
  apps/web/src/services/asset-inventory/types/cloud-service-page-type.ts
  apps/web/src/services/cost-explorer/components/BudgetDetailInfo.vue
  apps/web/src/services/cost-explorer/components/CostAnalysisChart.vue
  apps/web/src/services/cost-explorer/components/CostAnalysisDataTable.vue
  apps/web/src/services/cost-explorer/components/CostAnalysisFiltersAddMoreButton.vue
  apps/web/src/services/cost-explorer/components/CostAnalysisGranularityPeriodDropdown.vue
  apps/web/src/services/cost-explorer/components/CostAnalysisPeriodSelectDropdown.vue
  apps/web/src/services/cost-explorer/components/CostAnalysisQuerySection.vue
  apps/web/src/services/cost-explorer/components/CostAnalysisStackedColumnChart.vue
  apps/web/src/services/cost-explorer/components/DataSourceManagementTabLinkedAccountTable.vue
  apps/web/src/services/dashboards/components/dashboard-detail/DashboardLabelsButton.vue
  apps/web/src/services/dashboards/components/legacy/DashboardCostWidgetValueOptionDropdown.vue
  apps/web/src/services/dashboards/components/legacy/DashboardVariablesMoreButton.vue
  apps/web/src/services/dashboards/components/legacy/DashboardWidgetMoreOptions.vue
  apps/web/src/services/dashboards/widgets/_composables/use-widget/use-widget-location.ts
  apps/web/src/services/info/components/NoticeDetail.vue
  apps/web/src/services/landing/components/LandingWorkspaceBoard.vue
  apps/web/src/services/project/components/ProjectSummaryAllSummaryWidget.vue
  apps/web/src/services/project/components/ProjectSummaryAllSummaryWidgetRegionService.vue
  apps/web/src/services/project/components/ProjectSummaryServiceAccountsWidget.vue
  apps/web/src/services/project/components/ProjectSummaryTrustedAdvisorWidget.vue
  apps/web/src/services/workspace-home/components/BookmarkHeader.vue
  package-lock.json
  packages/core-lib/package.json
  packages/mirinae/package.json
  packages/mirinae/src/data-display/popover/PPopover.mdx
  packages/mirinae/src/data-display/popover/PPopover.stories.ts
  packages/mirinae/src/data-display/popover/PPopover.vue
  packages/mirinae/src/data-display/popover/story-helper.ts
  packages/mirinae/src/hooks/context-menu-controller/__tests__/index.test.ts
  packages/mirinae/src/hooks/context-menu-controller/index.ts
  packages/mirinae/src/hooks/context-menu-fixed-style/index.ts
  packages/mirinae/src/inputs/dropdown/filterable-query-dropdown/PFilterableQueryDropdown.vue
  packages/mirinae/src/inputs/dropdown/select-dropdown/PSelectDropdown.stories.ts
  packages/mirinae/src/inputs/dropdown/select-dropdown/PSelectDropdown.vue
  packages/mirinae/src/inputs/dropdown/select-dropdown/story-helper.ts
  packages/mirinae/src/inputs/input/query-input/PQueryInput.vue
  packages/mirinae/src/inputs/search/search/PSearch.vue
  packages/mirinae/src/navigation/breadcrumbs/modules/BreadcrumbsEllipsisItem.vue
  packages/mirinae/src/navigation/tabs/tab/components/FolderTab.vue
Labels: pass/signedoff

#4795 feat: apply cancellable fetcher to table widget
  apps/web/src/common/components/bookmark/BookmarkLinkFormModal.vue
  apps/web/src/common/modules/monitoring/Monitoring.vue
  apps/web/src/common/modules/navigations/top-bar/modules/top-bar-toolset/modules/top-bar-notifications/modules/TopBarNotificationsContextMenu.vue
  apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/ClusteredColumnChart.vue
  apps/web/src/common/modules/widgets/_widgets/color-coded-heatmap/ColorCodedHeatmap.vue
  apps/web/src/common/modules/widgets/_widgets/color-coded-table-heatmap/ColorCodedTableHeatmap.vue
  apps/web/src/common/modules/widgets/_widgets/gauge/Gauge.vue
  apps/web/src/common/modules/widgets/_widgets/geo-map/GeoMap.vue
  apps/web/src/common/modules/widgets/_widgets/heatmap/Heatmap.vue
  apps/web/src/common/modules/widgets/_widgets/line-chart/LineChart.vue
  apps/web/src/common/modules/widgets/_widgets/number-card/NumberCard.vue
  apps/web/src/common/modules/widgets/_widgets/pie-chart/PieChart.vue
  apps/web/src/common/modules/widgets/_widgets/progress-card/ProgressCard.vue
  apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/StackedColumnChart.vue
  apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/StackedHorizontalBarChart.vue
  apps/web/src/common/modules/widgets/_widgets/table/Table.vue
  apps/web/src/common/modules/widgets/_widgets/treemap/Treemap.vue
  apps/web/src/lib/variable-models/_base/resource-variable-model.ts
  apps/web/src/lib/variable-models/managed-model/custom-resource-model/asset-additional-info-key-variable-model.ts
  apps/web/src/lib/variable-models/managed-model/custom-resource-model/asset-data-key-variable-model.ts
  apps/web/src/lib/variable-models/managed-model/custom-resource-model/cost-additional-info-key-variable-model.ts
  apps/web/src/lib/variable-models/managed-model/custom-resource-model/cost-data-key-variable-model.ts
  apps/web/src/lib/variable-models/managed-model/custom-resource-model/cost-tag-key-variable-model.ts
  apps/web/src/lib/variable-models/managed-model/resource-model/project-variable-model.ts
  apps/web/src/services/asset-inventory/components/CloudServiceLogTab.vue
  apps/web/src/services/asset-inventory/components/MetricExplorerChart.vue
  apps/web/src/services/asset-inventory/components/MetricExplorerDataTable.vue
  apps/web/src/services/asset-inventory/pages/CloudServicePage.vue
  apps/web/src/services/asset-inventory/stores/metric-explorer-page-store.ts
  apps/web/src/services/cost-explorer/CostExplorerContainer.vue
  apps/web/src/services/cost-explorer/components/BudgetCreateProviderSelect.vue
  apps/web/src/services/cost-explorer/components/CostAnalysisChart.vue
  apps/web/src/services/cost-explorer/components/CostAnalysisDataTable.vue
  apps/web/src/services/cost-explorer/components/CostAnalysisGroupBy.vue
  apps/web/src/services/cost-explorer/stores/cost-query-set-store.ts
  apps/web/src/services/dashboards/stores/dashboard-detail-info-store.ts
  apps/web/src/services/dashboards/widgets/_base-widgets/base-count-of-findings/BaseCountOfFindingsWidget.vue
  apps/web/src/services/dashboards/widgets/_base-widgets/base-pie/BasePieWidget.vue
  apps/web/src/services/dashboards/widgets/_base-widgets/base-trend/BaseTrendWidget.vue
  apps/web/src/services/dashboards/widgets/asset-widgets/compliance-status/ComplianceStatusWidget.vue
  apps/web/src/services/dashboards/widgets/asset-widgets/severity-status-by-service/SeverityStatusByServiceWidget.vue
  apps/web/src/services/dashboards/widgets/asset-widgets/total-fail-findings-history/TotalFailFindingsHistoryWidget.vue
  apps/web/src/services/dashboards/widgets/asset-widgets/total-fail-findings-status/TotalFailFindingsStatusWidget.vue
  apps/web/src/services/dashboards/widgets/asset-widgets/trend-of-pass-and-fail-findings/TrendOfPassAndFailFindingsWidget.vue
  apps/web/src/services/dashboards/widgets/cost-widgets/budget-status/BudgetStatusWidget.vue
  apps/web/src/services/dashboards/widgets/cost-widgets/budget-usage-by-target/BudgetUsageByTargetWidget.vue
  apps/web/src/services/dashboards/widgets/cost-widgets/budget-usage-summary/BudgetUsageSummaryWidget.vue
  apps/web/src/services/dashboards/widgets/cost-widgets/cost-by-region-multi-fields/CostByRegionMultiFieldsWidget.vue
  apps/web/src/services/dashboards/widgets/cost-widgets/cost-by-region/CostByRegionWidget.vue
  apps/web/src/services/dashboards/widgets/cost-widgets/cost-map/CostMapWidget.vue
  apps/web/src/services/dashboards/widgets/cost-widgets/cost-summary-multi-fields/CostSummaryMultiFieldsWidget.vue
  apps/web/src/services/dashboards/widgets/cost-widgets/monthly-cost/MonthlyCostWidget.vue
  apps/web/src/services/workspace-home/store/workspace-home-page-store.ts
  apps/web/src/store/dashboard/dashboard-store.ts
  apps/web/src/store/modules/user/actions.ts
  packages/core-lib/src/space-connector/cancellable-fetcher.ts
Labels: pass/signedoff

#4797 fix: fix shared project dashboard bug
  apps/web/src/services/dashboards/DashboardsLSB.vue
  apps/web/src/services/dashboards/components/dashboard-main/DashboardLSBTree.vue
  apps/web/src/services/dashboards/stores/dashboard-main-page-store.ts
  apps/web/src/store/dashboard/dashboard-store.ts
Labels: pass/signedoff

#4798 fix: solve saved preset filter item bug & apply cost-data-source metadata enums to cost-analysis page
  apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardFilters.vue
  apps/web/src/services/cost-explorer/components/CostAnalysisFiltersPopper.vue
  apps/web/src/services/cost-explorer/stores/cost-analysis-page-store.ts
Labels: pass/signedoff

#4801 feat: edit minor
  apps/web/src/common/modules/widgets/_widgets/color-coded-heatmap/ColorCodedHeatmap.vue
Labels: pass/signedoff

#4804 fix: fix PTab emit bug
  apps/web/src/common/modules/navigations/top-bar/modules/top-bar-search/modules/top-bar-search-dropdown/TopBarSearchDropdown.vue
  apps/web/src/services/asset-inventory/pages/ServiceAccountPage.vue
Labels: pass/signedoff

#4806 chore: solve dashboard-l-s-b bug
  apps/web/src/services/dashboards/DashboardsLSB.vue
Labels: pass/signedoff

#4803 fix(mirinae): let position set by floatingUI automatically
  apps/web/src/common/modules/widgets/_components/WidgetFrame.vue
  apps/web/src/services/advanced/components/BookmarkManagementDetailTable.vue
  apps/web/src/services/advanced/components/BookmarkManagementTable.vue
  apps/web/src/services/alert-manager/components/AlertDetailNote.vue
  apps/web/src/services/asset-inventory/components/MetricExplorerFiltersPopper.vue
  apps/web/src/services/asset-inventory/components/MetricExplorerHeader.vue
  apps/web/src/services/cost-explorer/components/BudgetCreateTargetSelect.vue
  apps/web/src/services/cost-explorer/components/CostAnalysisFiltersPopper.vue
  apps/web/src/services/cost-explorer/components/CostAnalysisQuerySection.vue
  apps/web/src/services/info/components/NoticeWorkspaceDropdown.vue
  apps/web/src/services/workspace-home/components/BookmarkBoard.vue
  packages/mirinae/src/hooks/context-menu-controller/index.ts
  packages/mirinae/src/hooks/context-menu-fixed-style/index.ts
  packages/mirinae/src/inputs/context-menu/PContextMenu.vue
  packages/mirinae/src/inputs/dropdown/select-dropdown/PSelectDropdown.vue
  packages/mirinae/src/navigation/breadcrumbs/modules/BreadcrumbsEllipsisItem.vue
Labels: pass/signedoff
