Repository cloudforet-io/console, pull requests merged in 2024-07, with the labels that each got.

#4181 fix: solve critical QAs
  apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep1.vue
  apps/web/src/store/reference/project-reference-store.ts
Labels: pass/signedoff

#4184 chore: edit base-on-date helper
  apps/web/src/common/modules/widgets/_helpers/widget-date-helper.ts
Labels: pass/signedoff

#4185 feat: apply qa issue
  apps/web/src/services/workspace-home/components/CostSummary.vue
  apps/web/src/services/workspace-home/pages/WorkspaceHomePage.vue
  apps/web/src/services/workspace-home/store/workspace-home-page-store.ts
  apps/web/src/services/workspace-home/types/workspace-home-type.ts
Labels: pass/signedoff

#4183 fix: fix notice popup bug
  apps/web/src/common/modules/popup/notice/NoticePopup.vue
Labels: pass/signedoff

#4182 fix: fix widget mount bug in widget overlay
  apps/web/src/common/modules/favorites/favorite-button/FavoriteButton.vue
  apps/web/src/common/modules/navigations/top-bar/modules/top-bar-toolset/modules/top-bar-favorite/modules/TopBarFavoriteContextMenu.vue
  apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2.vue
  apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2WidgetForm.vue
  apps/web/src/common/modules/widgets/_composables/use-widget-init-and-refresh.ts
  apps/web/src/common/modules/widgets/_widgets/gauge/Gauge.vue
  apps/web/src/common/modules/widgets/types/widget-display-type.ts
  apps/web/src/services/dashboards/helpers/dashboard-share-helper.ts
  apps/web/src/services/workspace-home/components/UserConfigRecent.vue
  apps/web/src/store/dashboard/dashboard-store.ts
Labels: pass/signedoff

#4186 feat: apply bookmark menu
  apps/web/src/lib/menu/menu-architecture.ts
  apps/web/src/services/preference/routes/admin/routes.ts
Labels: pass/signedoff

#4187 feat: add DASHBOARD_EDIT_DISABLE config
  apps/web/src/common/modules/widgets/_components/WidgetFrame.vue
  apps/web/src/services/dashboards/components/DashboardControlButtons.vue
Labels: pass/signedoff

#4188 fix: fix reorder sidebar bug & fix bug in dashboard create page
  apps/web/src/common/modules/widgets/_helpers/widget-config-helper.ts
  apps/web/src/services/dashboards/components/DashboardCreateScopeForm.vue
  apps/web/src/services/dashboards/components/DashboardCreateStep2.vue
  apps/web/src/services/dashboards/components/DashboardRefreshDropdown.vue
  apps/web/src/services/dashboards/components/DashboardReorderSidebar.vue
  apps/web/src/services/dashboards/components/DashboardToolsetDateDropdown.vue
  apps/web/src/services/dashboards/pages/DashboardCreatePage.vue
  apps/web/src/services/dashboards/stores/dashboard-create-page-store.ts
Labels: pass/signedoff

#4190 fix: replace asset-analysis to metric-explorer
  apps/web/src/services/asset-inventory/AssetInventoryLSB.vue
  apps/web/src/services/asset-inventory/components/MetricExplorerChart.vue
  apps/web/src/services/asset-inventory/components/MetricExplorerChartLegends.vue
  apps/web/src/services/asset-inventory/components/MetricExplorerDataTable.vue
  apps/web/src/services/asset-inventory/components/MetricExplorerDonutChart.vue
  apps/web/src/services/asset-inventory/components/MetricExplorerFiltersPopper.vue
  apps/web/src/services/asset-inventory/components/MetricExplorerGranularityDropdown.vue
  apps/web/src/services/asset-inventory/components/MetricExplorerGroupBy.vue
  apps/web/src/services/asset-inventory/components/MetricExplorerHeader.vue
  apps/web/src/services/asset-inventory/components/MetricExplorerHorizontalColumnChart.vue
  apps/web/src/services/asset-inventory/components/MetricExplorerLSB.vue
  apps/web/src/services/asset-inventory/components/MetricExplorerLSBMetric.vue
  apps/web/src/services/asset-inventory/components/MetricExplorerLSBMetricTree.vue
  apps/web/src/services/asset-inventory/components/MetricExplorerLineChart.vue
  apps/web/src/services/asset-inventory/components/MetricExplorerMapChart.vue
  apps/web/src/services/asset-inventory/components/MetricExplorerNameFormModal.vue
  apps/web/src/services/asset-inventory/components/MetricExplorerOperatorDropdown.vue
  apps/web/src/services/asset-inventory/components/MetricExplorerPeriodDropdown.vue
  apps/web/src/services/asset-inventory/components/MetricExplorerQueryFormSidebar.vue
  apps/web/src/services/asset-inventory/components/MetricExplorerQuerySection.vue
  apps/web/src/services/asset-inventory/pages/MetricExplorerDetailPage.vue
  apps/web/src/services/asset-inventory/pages/MetricExplorerMainPage.vue
  apps/web/src/services/asset-inventory/routes/routes.ts
  apps/web/src/services/asset-inventory/stores/metric-explorer-page-store.ts
Labels: pass/signedoff

#4192 feat: apply asset(size) value formatter to table widget
  apps/web/src/common/modules/widgets/_widgets/table/Table.vue
  apps/web/src/common/modules/widgets/_widgets/table/_component/WidgetDataTable.vue
  apps/web/src/common/modules/widgets/types/widget-data-table-type.ts
Labels: pass/signedoff

#4193 feat: apply size formatter to data-table preview table
  apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardHeaderTitle.vue
  apps/web/src/common/modules/widgets/_components/WidgetFormOverlayPreviewTable.vue
  apps/web/src/common/modules/widgets/_widgets/table/_component/WidgetDataTable.vue
  apps/web/src/services/asset-inventory/components/MetricExplorerDataTable.vue
  apps/web/src/services/asset-inventory/constants/asset-analysis-constant.ts
Labels: pass/signedoff

#4194 feat: add `permissions` to CostDataSourceModel
  apps/web/src/schema/cost-analysis/data-source/model.ts
  apps/web/src/store/reference/cost-data-source-reference-store.ts
Labels: pass/signedoff

#4196 feat(feature-project-workspace-home): merge to master branch
  apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardHeaderTitle.vue
  apps/web/src/common/modules/widgets/_components/WidgetFormOverlayPreviewTable.vue
  apps/web/src/common/modules/widgets/_widgets/table/Table.vue
  apps/web/src/common/modules/widgets/_widgets/table/_component/WidgetDataTable.vue
  apps/web/src/common/modules/widgets/types/widget-data-table-type.ts
  apps/web/src/schema/cost-analysis/data-source/model.ts
  apps/web/src/services/asset-inventory/AssetInventoryLSB.vue
  apps/web/src/services/asset-inventory/components/MetricExplorerChart.vue
  apps/web/src/services/asset-inventory/components/MetricExplorerChartLegends.vue
  apps/web/src/services/asset-inventory/components/MetricExplorerDataTable.vue
  apps/web/src/services/asset-inventory/components/MetricExplorerDonutChart.vue
  apps/web/src/services/asset-inventory/components/MetricExplorerFiltersPopper.vue
  apps/web/src/services/asset-inventory/components/MetricExplorerGranularityDropdown.vue
  apps/web/src/services/asset-inventory/components/MetricExplorerGroupBy.vue
  apps/web/src/services/asset-inventory/components/MetricExplorerHeader.vue
  apps/web/src/services/asset-inventory/components/MetricExplorerHorizontalColumnChart.vue
  apps/web/src/services/asset-inventory/components/MetricExplorerLSB.vue
  apps/web/src/services/asset-inventory/components/MetricExplorerLSBMetric.vue
  apps/web/src/services/asset-inventory/components/MetricExplorerLSBMetricTree.vue
  apps/web/src/services/asset-inventory/components/MetricExplorerLineChart.vue
  apps/web/src/services/asset-inventory/components/MetricExplorerMapChart.vue
  apps/web/src/services/asset-inventory/components/MetricExplorerNameFormModal.vue
  apps/web/src/services/asset-inventory/components/MetricExplorerOperatorDropdown.vue
  apps/web/src/services/asset-inventory/components/MetricExplorerPeriodDropdown.vue
  apps/web/src/services/asset-inventory/components/MetricExplorerQueryFormSidebar.vue
  apps/web/src/services/asset-inventory/components/MetricExplorerQuerySection.vue
  apps/web/src/services/asset-inventory/constants/asset-analysis-constant.ts
  apps/web/src/services/asset-inventory/pages/MetricExplorerDetailPage.vue
  apps/web/src/services/asset-inventory/pages/MetricExplorerMainPage.vue
  apps/web/src/services/asset-inventory/routes/routes.ts
  apps/web/src/services/asset-inventory/stores/metric-explorer-page-store.ts
  apps/web/src/store/reference/cost-data-source-reference-store.ts
Labels: pass/signedoff

#4197 fix: set proper filter to full data link in metadata
  apps/web/src/common/modules/widgets/_composables/use-widget-frame.ts
  apps/web/src/services/asset-inventory/pages/MetricExplorerDetailPage.vue
  apps/web/src/services/asset-inventory/stores/metric-explorer-page-store.ts
  apps/web/src/services/asset-inventory/types/metric-explorer-url-query-type.ts
Labels: pass/signedoff

#4199 feat: table detail - workspace col, name col, loading
  apps/web/src/common/components/bookmark/BookmarkLinkFormModal.vue
  apps/web/src/services/preference/components/BookmarkManagementTable.vue
  apps/web/src/services/preference/store/bookmark-page-store.ts
Labels: pass/signedoff

#4202 feat(feature-project-workspace-home): merge to master branch
  apps/web/src/common/modules/widgets/_composables/use-widget-frame.ts
  apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldTableDataField.vue
  apps/web/src/common/modules/widgets/_widgets/heatmap/Heatmap.vue
  apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/StackedColumnChart.vue
  apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/StackedHorizontalBarChart.vue
  apps/web/src/services/asset-inventory/pages/MetricExplorerDetailPage.vue
  apps/web/src/services/asset-inventory/stores/metric-explorer-page-store.ts
  apps/web/src/services/asset-inventory/types/metric-explorer-url-query-type.ts
Labels: fail/signedoff

#4203 chore: minor changed for refactor
  apps/web/src/services/preference/components/BookmarkContainer.vue
  apps/web/src/services/preference/components/BookmarkManagementTable.vue
  apps/web/src/services/preference/components/BookmarkTree.vue
  apps/web/src/services/preference/composables/bookmark-data-helper.ts
  apps/web/src/services/preference/routes/admin/routes.ts
  apps/web/src/services/preference/routes/route-constant.ts
Labels: pass/signedoff

#4205 feat: apply new cost unit & apply compact formatter and fix small issues
  apps/web/src/common/modules/widgets/_components/WidgetFormCostDataSourcePopper.vue
  apps/web/src/common/modules/widgets/_components/WidgetFormDataSourcePopover.vue
  apps/web/src/common/modules/widgets/_components/WidgetFormOverlay.vue
  apps/web/src/common/modules/widgets/_components/WidgetFormOverlayPreviewTable.vue
  apps/web/src/common/modules/widgets/_widgets/table/_component/WidgetDataTable.vue
  packages/mirinae/src/data-display/tooltips/PTooltip.pcss
Labels: pass/signedoff

#4208 feat: apply changed transform name planning
  apps/web/src/common/modules/widgets/_components/WidgetFormDataSourcePopover.vue
  apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardHeaderTitle.vue
  apps/web/src/common/modules/widgets/_helpers/widget-data-table-helper.ts
  apps/web/src/common/modules/widgets/_store/widget-generate-store.ts
Labels: pass/signedoff

#4209 chore: apply changed cost alias
  apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardAddContents.vue
  apps/web/src/services/cost-explorer/components/CostAnalysisDataTypeDropdown.vue
Labels: pass/signedoff

#4210 chore: hide loading msg
  apps/web/src/services/info/pages/admin/AdminNoticeDetailPage.vue
Labels: pass/signedoff

#4211 chore: fix notice update bug
  apps/web/src/services/info/components/NoticeForm.vue
Labels: pass/signedoff

#4213 refactor: only code refactor (route, component)
  apps/web/src/services/preference/components/BookmarkDetailContainer.vue
  apps/web/src/services/preference/components/BookmarkTree.vue
  apps/web/src/services/preference/pages/admin/AdminBookmarkDetailPage.vue
  apps/web/src/services/preference/routes/admin/routes.ts
  apps/web/src/services/preference/routes/route-constant.ts
Labels: pass/signedoff

#4214 feat: metric explorer is coming to admin mode! & fix admin widget full data link
  apps/web/src/common/modules/widgets/_components/WidgetFormDataSourcePopover.vue
  apps/web/src/common/modules/widgets/_composables/use-widget-frame.ts
  apps/web/src/lib/menu/menu-architecture.ts
  apps/web/src/services/asset-inventory/components/MetricExplorerLSBMetric.vue
  apps/web/src/services/asset-inventory/pages/MetricExplorerDetailPage.vue
  apps/web/src/services/asset-inventory/routes/admin/routes.ts
  apps/web/src/store/modules/display/getters.ts
Labels: pass/signedoff

#4218 feat: apply minor notice qa
  apps/web/src/services/info/components/NoticeForm.vue
  apps/web/src/services/info/pages/admin/AdminNoticeDetailPage.vue
Labels: pass/signedoff

#4219 feat: apply folder detail page api and header button
  apps/web/src/services/preference/components/BookmarkDetailContainer.vue
  apps/web/src/services/preference/pages/admin/AdminBookmarkDetailPage.vue
  apps/web/src/services/preference/store/bookmark-page-store.ts
Labels: pass/signedoff

#4220 feat: do not load unless widget has all required fields
  apps/web/src/common/modules/widgets/_components/WidgetFrame.vue
  apps/web/src/common/modules/widgets/_composables/use-widget-frame.ts
  apps/web/src/common/modules/widgets/_composables/use-widget-init-and-refresh.ts
  apps/web/src/common/modules/widgets/_helpers/widget-date-helper.ts
  apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/ClusteredColumnChart.vue
  apps/web/src/common/modules/widgets/_widgets/gauge/Gauge.vue
  apps/web/src/common/modules/widgets/_widgets/geo-map/GeoMap.vue
  apps/web/src/common/modules/widgets/_widgets/heatmap/Heatmap.vue
  apps/web/src/common/modules/widgets/_widgets/line-chart/LineChart.vue
  apps/web/src/common/modules/widgets/_widgets/number-card/NumberCard.vue
  apps/web/src/common/modules/widgets/_widgets/pie-chart/PieChart.vue
  apps/web/src/common/modules/widgets/_widgets/progress-card/ProgressCard.vue
  apps/web/src/common/modules/widgets/_widgets/stacked-area-chart/StackedAreaChart.vue
  apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/StackedColumnChart.vue
  apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/StackedHorizontalBarChart.vue
  apps/web/src/common/modules/widgets/_widgets/table/Table.vue
  apps/web/src/common/modules/widgets/_widgets/treemap/Treemap.vue
Labels: pass/signedoff

#4222 fix: apply project to admin dashboard
  apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardAddForm.vue
  apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardFilters.vue
Labels: pass/signedoff

#4223 fix: check null, undefined, '' of widget options
  apps/web/src/common/modules/widgets/_helpers/widget-date-helper.ts
  apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldFormatRules.vue
  apps/web/src/common/modules/widgets/_widgets/gauge/widget-config.ts
Labels: pass/signedoff

#4224 fix: fix favorite in dashboard LSB
  apps/web/src/services/dashboards/DashboardsLSB.vue
Labels: pass/signedoff

#4225 fix(table-widget): apply reference label to table field
  apps/web/src/common/modules/widgets/_widgets/table/_component/WidgetDataTable.vue
Labels: pass/signedoff

#4227 chore: add missing changes
  apps/web/src/common/modules/widgets/_components/WidgetFormOverlayPreviewTable.vue
  apps/web/src/common/modules/widgets/_widgets/table/_component/WidgetDataTable.vue
Labels: pass/signedoff

#4230 fix: remove setting project dashboard variables and variable schema
  apps/web/src/services/dashboards/stores/dashboard-detail-info-store.ts
Labels: pass/signedoff

#4229 fix: fix the dashboard create step1 UI bug
  apps/web/src/services/dashboards/components/DashboardCreateStep1.vue
  apps/web/src/services/dashboards/constants/dashboard-labels.ts
Labels: pass/signedoff

#4231 feat: add charts
  apps/web/src/common/modules/monitoring/MetricChart.vue
  apps/web/src/common/modules/monitoring/Monitoring.vue
  apps/web/src/services/project/components/ProjectSummaryAllSummaryWidget.vue
  apps/web/src/services/project/components/ProjectSummaryAllSummaryWidgetRegionService.vue
  apps/web/src/services/project/components/ProjectSummaryBillingWidget.vue
  apps/web/src/services/project/pages/ProjectDashboardPage.vue
Labels: pass/signedoff

#4228 feat: apply heading function for detail page
  apps/web/src/common/components/bookmark/BookmarkDeleteModal.vue
  apps/web/src/common/components/bookmark/BookmarkFolderFormModal.vue
  apps/web/src/common/components/bookmark/BookmarkLinkFormModal.vue
  apps/web/src/common/components/bookmark/store/bookmark-store.ts
  apps/web/src/services/preference/components/BookmarkContainer.vue
  apps/web/src/services/preference/components/BookmarkDetailContainer.vue
  apps/web/src/services/preference/components/BookmarkManagementDetailTable.vue
  apps/web/src/services/preference/components/BookmarkManagementTable.vue
  apps/web/src/services/preference/pages/admin/AdminBookmarkPage.vue
  apps/web/src/services/preference/store/bookmark-page-store.ts
Labels: pass/signedoff

#4233 chore: fixed link
  apps/web/src/services/cost-explorer/pages/admin/AdminDataSourcePage.vue
  apps/web/src/services/landing/components/DomainLandingRecommendation.vue
  apps/web/src/services/landing/components/DomainLandingTitle.vue
  apps/web/src/services/workspace-home/components/Welcome.vue
Labels: pass/signedoff

#4232 chore: apply changed project dashboard planning
  apps/web/src/services/dashboards/stores/dashboard-detail-info-store.ts
Labels: pass/signedoff

#4236 chore: solve small issues
  apps/web/src/common/modules/navigations/lsb/modules/LSBCollapsibleMenuItem.vue
  apps/web/src/common/modules/widgets/_components/WidgetFormCostDataSourcePopper.vue
  apps/web/src/common/modules/widgets/_components/WidgetFormDataSourcePopover.vue
Labels: pass/signedoff

#4235 feat: apply breadcrumbs, tree, col-name at table
  apps/web/src/services/preference/components/BookmarkManagementDetailTable.vue
  apps/web/src/services/preference/components/BookmarkTree.vue
Labels: pass/signedoff

#4237 feat: add `disableManageButtons` to dashboard-detail-info-store, widget frame
  apps/web/src/common/modules/widgets/_components/WidgetFrame.vue
  apps/web/src/common/modules/widgets/_composables/use-widget-frame.ts
  apps/web/src/common/modules/widgets/_widgets/line-chart/LineChart.vue
  apps/web/src/common/modules/widgets/_widgets/stacked-area-chart/StackedAreaChart.vue
  apps/web/src/common/modules/widgets/types/widget-display-type.ts
  apps/web/src/common/modules/widgets/types/widget-frame-type.ts
  apps/web/src/services/dashboards/components/DashboardControlButtons.vue
  apps/web/src/services/dashboards/components/DashboardDetailHeader.vue
  apps/web/src/services/dashboards/components/DashboardRefreshDropdown.vue
  apps/web/src/services/dashboards/components/DashboardToolsetDateDropdown.vue
  apps/web/src/services/dashboards/components/DashboardWidgetContainerV2.vue
  apps/web/src/services/dashboards/pages/DashboardDetailPage.vue
  apps/web/src/services/dashboards/stores/dashboard-detail-info-store.ts
  apps/web/src/store/dashboard/dashboard-store.ts
Labels: pass/signedoff

#4238 fix: update deprecated menuItem rules
  apps/web/src/services/dashboards/DashboardsLSB.vue
Labels: pass/signedoff

#4241 feat: apply widget state to model and parameters
  apps/web/src/common/modules/widgets/types/widget-model.ts
  apps/web/src/schema/dashboard/private-widget/api-verbs/create.ts
  apps/web/src/schema/dashboard/private-widget/api-verbs/update.ts
  apps/web/src/schema/dashboard/private-widget/model.ts
  apps/web/src/schema/dashboard/public-widget/api-verbs/create.ts
  apps/web/src/schema/dashboard/public-widget/api-verbs/update.ts
  apps/web/src/schema/dashboard/public-widget/model.ts
Labels: pass/signedoff

#4244 chore: edit widget state type name & create status getter
  apps/web/src/common/modules/widgets/_store/widget-generate-store.ts
  apps/web/src/common/modules/widgets/types/widget-model.ts
  apps/web/src/schema/dashboard/private-widget/api-verbs/create.ts
  apps/web/src/schema/dashboard/private-widget/api-verbs/update.ts
  apps/web/src/schema/dashboard/private-widget/model.ts
  apps/web/src/schema/dashboard/public-widget/api-verbs/create.ts
  apps/web/src/schema/dashboard/public-widget/api-verbs/update.ts
  apps/web/src/schema/dashboard/public-widget/model.ts
Labels: pass/signedoff

#4246 feat: apply search at LSB, tables
  apps/web/src/services/preference/components/BookmarkLSB.vue
  apps/web/src/services/preference/components/BookmarkManagementDetailTable.vue
  apps/web/src/services/preference/components/BookmarkManagementTable.vue
  apps/web/src/services/preference/composables/bookmark-data-helper.ts
  apps/web/src/services/preference/constants/bookmark-constant.ts
  apps/web/src/services/preference/store/bookmark-page-store.ts
Labels: pass/signedoff

#4245 feat: update widget `state` when changing or updating dataTable
  apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardAddContents.vue
  apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardHeaderTitle.vue
  apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformContents.vue
  apps/web/src/common/modules/widgets/_components/WidgetFormOverlay.vue
  apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2.vue
  apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2WidgetForm.vue
  apps/web/src/common/modules/widgets/_store/widget-generate-store.ts
Labels: pass/signedoff

#4251 feat: get proper date range even if user select wrong date range
  apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2.vue
  apps/web/src/common/modules/widgets/_helpers/widget-date-helper.ts
  apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/ClusteredColumnChart.vue
  apps/web/src/common/modules/widgets/_widgets/heatmap/Heatmap.vue
  apps/web/src/common/modules/widgets/_widgets/line-chart/LineChart.vue
  apps/web/src/common/modules/widgets/_widgets/pie-chart/PieChart.vue
  apps/web/src/common/modules/widgets/_widgets/stacked-area-chart/StackedAreaChart.vue
  apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/StackedColumnChart.vue
  apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/StackedHorizontalBarChart.vue
  apps/web/src/common/modules/widgets/_widgets/treemap/Treemap.vue
Labels: pass/signedoff

#4249 feat: update the lineByField to optional
  apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldLineBy.vue
Labels: pass/signedoff

#4254 fix: fix dashboard clone bug
  apps/web/src/services/dashboards/components/DashboardCloneModal.vue
Labels: pass/signedoff

#4253 fix: fix mount bug in widget overlay & fix etc bug in clursteredColumnChart
  apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2.vue
  apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/ClusteredColumnChart.vue
Labels: pass/signedoff

#4247 feat: create PolicyRuleCard (only markup)
  apps/web/src/services/cost-explorer/components/AnomalyDetectionPolicyRuleCard.vue
  apps/web/src/services/cost-explorer/pages/AnomalyDetectionPolicyPage.vue
  apps/web/src/services/cost-explorer/stores/anomaly-detection-policy-page-store.ts
Labels: pass/signedoff

#4256 fix: remove dynamic import in WIDGET_FIELD_COMPONENT
  apps/web/src/common/modules/widgets/_constants/widget-field-components-constant.ts
Labels: pass/signedoff

#4257 fix: fix comparing object value in overlay step2
  apps/web/src/common/modules/widgets/_components/WidgetFormOverlay.vue
  apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2.vue
  apps/web/src/common/modules/widgets/_components/WidgetFrame.vue
  apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldTableDataField.vue
  apps/web/src/services/dashboards/components/DashboardWidgetContainerV2.vue
Labels: pass/signedoff

#4258 feat: implement `state` to dashboard widgets
  apps/web/src/common/modules/widgets/_components/WidgetFormDataSourcePopover.vue
  apps/web/src/common/modules/widgets/_components/WidgetFormOverlay.vue
  apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2.vue
  apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2WidgetForm.vue
  apps/web/src/common/modules/widgets/_components/WidgetFrame.vue
  apps/web/src/common/modules/widgets/_store/widget-generate-store.ts
  apps/web/src/services/dashboards/components/DashboardCreateStep2.vue
  apps/web/src/services/dashboards/components/DashboardCreateTemplateBoard.vue
  apps/web/src/services/dashboards/components/DashboardWidgetContainerV2.vue
  apps/web/src/services/dashboards/helpers/dashboard-share-helper.ts
  apps/web/src/services/dashboards/stores/dashboard-create-page-store.ts
Labels: pass/signedoff

#4260 chore: fix minor
  apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2.vue
  apps/web/src/common/modules/widgets/_composables/use-widget-frame.ts
  apps/web/src/common/modules/widgets/_helpers/widget-date-helper.ts
  apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/ClusteredColumnChart.vue
  apps/web/src/common/modules/widgets/_widgets/gauge/Gauge.vue
  apps/web/src/common/modules/widgets/_widgets/geo-map/GeoMap.vue
  apps/web/src/common/modules/widgets/_widgets/heatmap/Heatmap.vue
  apps/web/src/common/modules/widgets/_widgets/line-chart/LineChart.vue
  apps/web/src/common/modules/widgets/_widgets/number-card/NumberCard.vue
  apps/web/src/common/modules/widgets/_widgets/pie-chart/PieChart.vue
  apps/web/src/common/modules/widgets/_widgets/progress-card/ProgressCard.vue
  apps/web/src/common/modules/widgets/_widgets/stacked-area-chart/StackedAreaChart.vue
  apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/StackedColumnChart.vue
  apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/StackedHorizontalBarChart.vue
  apps/web/src/common/modules/widgets/_widgets/table/Table.vue
  apps/web/src/common/modules/widgets/_widgets/treemap/Treemap.vue
  apps/web/src/common/modules/widgets/types/widget-frame-type.ts
  apps/web/src/services/dashboards/components/DashboardCreateStep2.vue
  apps/web/src/services/dashboards/stores/dashboard-create-page-store.ts
Labels: pass/signedoff

#4263 refactor: refactor bookmark store
  apps/web/src/common/components/bookmark/BookmarkDeleteModal.vue
  apps/web/src/common/components/bookmark/BookmarkFolderFormModal.vue
  apps/web/src/common/components/bookmark/BookmarkLinkFormModal.vue
  apps/web/src/common/components/bookmark/store/bookmark-store.ts
  apps/web/src/services/preference/components/BookmarkContainer.vue
  apps/web/src/services/preference/components/BookmarkDetailContainer.vue
  apps/web/src/services/preference/components/BookmarkManagementTable.vue
  apps/web/src/services/preference/components/BookmarkTree.vue
  apps/web/src/services/preference/pages/admin/AdminBookmarkPage.vue
  apps/web/src/services/preference/store/bookmark-page-store.ts
  apps/web/src/services/workspace-home/components/Bookmark.vue
  apps/web/src/services/workspace-home/components/BookmarkBoard.vue
  apps/web/src/services/workspace-home/components/BookmarkFullMode.vue
  apps/web/src/services/workspace-home/components/BookmarkHeader.vue
  apps/web/src/services/workspace-home/pages/WorkspaceHomePage.vue
  apps/web/src/services/workspace-home/store/workspace-home-page-store.ts
Labels: pass/signedoff

#4265 Minor CSS issues
  apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardAddForm.vue
  apps/web/src/common/modules/widgets/_components/WidgetFormOverlayPreviewTable.vue
  apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2WidgetForm.vue
Labels: pass/signedoff

#4264 feat: create `getInitialSelectedMenuItem` for widget field
  apps/web/src/common/modules/widgets/_components/WidgetFieldDropdownAndMax.vue
  apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2WidgetForm.vue
  apps/web/src/common/modules/widgets/_helpers/widget-field-helper.ts
  apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldDataField.vue
  apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldGroupBy.vue
  apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldTableDataField.vue
  apps/web/src/common/modules/widgets/_widgets/heatmap/Heatmap.vue
  apps/web/src/common/modules/widgets/_widgets/pie-chart/widget-config.ts
  apps/web/src/common/modules/widgets/types/widget-field-value-type.ts
Labels: pass/signedoff

#4267 fix: solve small issues
  apps/web/src/common/modules/widgets/_constants/widget-components-constant.ts
  apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldTableDataField.vue
  apps/web/src/common/modules/widgets/_widgets/table/Table.vue
  apps/web/src/common/modules/widgets/_widgets/table/_component/WidgetDataTable.vue
Labels: pass/signedoff

#4268 fix: apply static table sorting
  apps/web/src/common/modules/widgets/_widgets/table/Table.vue
Labels: pass/signedoff

#4269 fix: revert table sorting
  apps/web/src/common/modules/widgets/_widgets/table/Table.vue
Labels: pass/signedoff

#4270 fix: initValue in dataField & sorting
  apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldDataField.vue
  apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldGroupBy.vue
  apps/web/src/common/modules/widgets/_widgets/heatmap/Heatmap.vue
  apps/web/src/common/modules/widgets/_widgets/line-chart/LineChart.vue
  apps/web/src/common/modules/widgets/_widgets/pie-chart/PieChart.vue
  apps/web/src/common/modules/widgets/_widgets/stacked-area-chart/StackedAreaChart.vue
  apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/StackedColumnChart.vue
  apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/StackedHorizontalBarChart.vue
Labels: pass/signedoff

#4271 feat: merge to master
  apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldDataField.vue
  apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldGroupBy.vue
  apps/web/src/common/modules/widgets/_widgets/heatmap/Heatmap.vue
  apps/web/src/common/modules/widgets/_widgets/line-chart/LineChart.vue
  apps/web/src/common/modules/widgets/_widgets/pie-chart/PieChart.vue
  apps/web/src/common/modules/widgets/_widgets/stacked-area-chart/StackedAreaChart.vue
  apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/StackedColumnChart.vue
  apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/StackedHorizontalBarChart.vue
  apps/web/src/common/modules/widgets/_widgets/table/Table.vue
Labels: pass/signedoff

#4272 chore: fix minor
  apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2.vue
Labels: pass/signedoff

#4273 feat: apply admin bookmark at user mode (UI)
  apps/web/src/services/preference/components/BookmarkManagementDetailTable.vue
  apps/web/src/services/preference/components/BookmarkManagementTable.vue
  apps/web/src/services/workspace-home/components/BookmarkBoard.vue
  apps/web/src/services/workspace-home/components/BookmarkHeader.vue
  apps/web/src/services/workspace-home/store/workspace-home-page-store.ts
Labels: pass/signedoff

#4274 chore: small issues
  apps/web/src/common/modules/widgets/_components/WidgetFormOverlayPreviewTable.vue
  apps/web/src/common/modules/widgets/_constants/data-table-constant.ts
  apps/web/src/common/modules/widgets/_store/widget-generate-store.ts
  apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldDataField.vue
  apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldGroupBy.vue
  apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldTableDataField.vue
Labels: pass/signedoff

#4275 fix: fix wrong trigger in widget...
  apps/web/src/common/modules/widgets/_components/WidgetFrame.vue
  apps/web/src/common/modules/widgets/_composables/use-widget-init-and-refresh.ts
  apps/web/src/services/asset-inventory/pages/MetricExplorerDetailPage.vue
Labels: pass/signedoff

#4259 feat: update mirinae repo settings for npm publish
  package-lock.json
  packages/mirinae/README.md
  packages/mirinae/package.json
  turbo.json
Labels: pass/signedoff

#4276 fix: add clearing data table when CREATING widget deleted
  apps/web/src/common/modules/widgets/_components/WidgetFormOverlay.vue
Labels: pass/signedoff

#4277 feat: create a default bookmark when creating a workspace
  apps/web/src/common/components/bookmark/store/bookmark-store.ts
  apps/web/src/services/preference/components/WorkspacesCreateModal.vue
Labels: pass/signedoff

#4279 feat: update design of dashboard list and detail page
  apps/web/src/common/modules/widgets/_composables/use-widget-frame.ts
  apps/web/src/services/dashboards/components/DashboardDetailHeader.vue
  apps/web/src/services/dashboards/components/DashboardMainBoardList.vue
  apps/web/src/services/dashboards/components/DashboardMainSelectFilter.vue
  apps/web/src/services/dashboards/components/DashboardWidgetContainerV2.vue
  apps/web/src/services/dashboards/pages/DashboardsMainPage.vue
  packages/mirinae/src/data-display/badge/PBadge.vue
  packages/mirinae/src/data-display/badge/type.ts
Labels: pass/signedoff

#4285 feat: apply minor qa and fix bugs
  apps/web/src/common/components/bookmark/BookmarkDeleteModal.vue
  apps/web/src/services/preference/components/BookmarkContainer.vue
  apps/web/src/services/preference/components/BookmarkDetailContainer.vue
  apps/web/src/services/preference/components/BookmarkManagementDetailTable.vue
  apps/web/src/services/preference/components/BookmarkManagementTable.vue
  apps/web/src/services/preference/components/BookmarkTree.vue
  apps/web/src/services/preference/constants/bookmark-constant.ts
  apps/web/src/services/preference/pages/admin/AdminBookmarkPage.vue
  apps/web/src/services/preference/store/bookmark-page-store.ts
  packages/language-pack/en.json
  packages/language-pack/ja.json
  packages/language-pack/ko.json
  packages/mirinae/src/data-display/tables/data-table/PDataTable.vue
Labels: pass/signedoff

#4286 fix: small fix
  apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformContents.vue
  apps/web/src/common/modules/widgets/_components/WidgetFormOverlayPreviewTable.vue
  apps/web/src/common/modules/widgets/_store/widget-generate-store.ts
  apps/web/src/common/modules/widgets/_widgets/table/widget-config.ts
Labels: pass/signedoff

#4280 feat: update project feedback issue
  apps/web/src/services/project/components/ProjectAlertEventRuleConditionForm.vue
  apps/web/src/services/project/components/ProjectWebhookTab.vue
  packages/mirinae/.gitignore
Labels: pass/signedoff

#4288 feat: apply qa issue
  apps/web/src/common/components/bookmark/type/type.ts
  apps/web/src/services/preference/components/BookmarkManagementTable.vue
  apps/web/src/services/preference/store/bookmark-page-store.ts
  apps/web/src/services/workspace-home/components/BookmarkBoard.vue
Labels: pass/signedoff

#4291 fix: update useGranularityMenuItems hook
  apps/web/src/common/modules/widgets/_composables/use-granularity-menu-items.ts
Labels: pass/signedoff

#4290 fix: solve array value field changed-validation issue
  apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2.vue
Labels: pass/signedoff

#4292 fix: apply widget sorting policy
  apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/StackedHorizontalBarChart.vue
Labels: pass/signedoff

#4293 fix: apply widget sorting policy (clusterd-column-chart)
  apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/ClusteredColumnChart.vue
Labels: pass/signedoff

#4294 fix: apply clustered-column-chart sorting
  apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/ClusteredColumnChart.vue
Labels: pass/signedoff

#4295 fix: apply table widget sorting
  apps/web/src/common/modules/widgets/_widgets/table/Table.vue
Labels: pass/signedoff

#4298 fix: apply metric/metric-example favorite button to metric tree item
  apps/web/src/services/asset-inventory/components/MetricExplorerLSBMetricTree.vue
Labels: pass/signedoff

#4297 fix: add load-metric in selecting namespace
  apps/web/src/common/modules/navigations/lsb/type.ts
  apps/web/src/services/asset-inventory/components/MetricExplorerLSB.vue
  apps/web/src/services/asset-inventory/components/MetricExplorerLSBMetric.vue
Labels: pass/signedoff

#4303 chore: solve data-table dropdown context menu style issue
  apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardFilters.vue
  apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardSourceForm.vue
Labels: pass/signedoff

#4304 fix(data-source): apply cost-data-source meta data to cost name & small fix
  apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardHeaderTitle.vue
  apps/web/src/services/cost-explorer/components/DataSourceManagementTabAccessRestriction.vue
  apps/web/src/services/cost-explorer/stores/data-sources-page-store.ts
  apps/web/src/services/cost-explorer/types/data-sources-type.ts
Labels: pass/signedoff

#4305 refactor: add project-group reference store to project-reference store
  apps/web/src/store/reference/project-reference-store.ts
Labels: pass/signedoff

#4306 feat: update cost analysis groupby
  apps/web/src/common/modules/widgets/_components/WidgetFrame.vue
  apps/web/src/services/cost-explorer/components/CostAnalysisFiltersAddMoreButton.vue
  apps/web/src/services/cost-explorer/components/CostAnalysisGroupBy.vue
  apps/web/src/services/cost-explorer/stores/cost-analysis-page-store.ts
  packages/mirinae/src/inputs/dropdown/select-dropdown/PSelectDropdown.stories.mdx
  packages/mirinae/src/inputs/dropdown/select-dropdown/PSelectDropdown.vue
  packages/mirinae/src/inputs/dropdown/select-dropdown/components/dropdown-button.vue
  packages/mirinae/src/inputs/dropdown/select-dropdown/story-helper.ts
  packages/mirinae/src/inputs/dropdown/select-dropdown/type.ts
Labels: pass/signedoff

#4307 feat: apply qa issue
  apps/web/src/services/preference/components/BookmarkManagementDetailTable.vue
  apps/web/src/services/preference/components/BookmarkManagementTable.vue
  apps/web/src/services/preference/composables/bookmark-data-helper.ts
  apps/web/src/services/preference/store/bookmark-page-store.ts
Labels: pass/signedoff

#4308 feat: changed design
  apps/web/public/images/domain-settings/img_auto-dormancy-configuration_cost-threshold-chart.png
  apps/web/public/images/domain-settings/img_auto-dormancy-configuration_cost-threshold-chart@2x.png
  apps/web/public/images/domain-settings/img_auto-dormancy-configuration_cost-threshold-chart@3x.png
  apps/web/src/lib/menu/config.ts
  apps/web/src/lib/menu/menu-info.ts
  apps/web/src/services/preference/components/DomainSettingsContainer.vue
  apps/web/src/services/preference/components/DomainSettingsLSB.vue
  apps/web/src/services/preference/pages/admin/AdminDomainSettingsAppearancePage.vue
  apps/web/src/services/preference/pages/admin/AdminDomainSettingsAutoDormancyConfigurationPage.vue
  apps/web/src/services/preference/pages/admin/AdminDomainSettingsBaseInformationPage.vue
  apps/web/src/services/preference/pages/admin/AdminDomainSettingsBrandAssetsPage.vue
  apps/web/src/services/preference/pages/admin/AdminDomainSettingsDomainInformationPage.vue
  apps/web/src/services/preference/pages/admin/AdminDomainSettingsTimezoneAndLanguagePage.vue
  apps/web/src/services/preference/routes/admin/routes.ts
  apps/web/src/services/preference/routes/route-constant.ts
  packages/language-pack/en.json
  packages/language-pack/ja.json
  packages/language-pack/ko.json
Labels: pass/signedoff

#4309 fix: solve table total freeze issue & apply default table total field freeze
  apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldSubTotal.vue
  apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldTotal.vue
  apps/web/src/common/modules/widgets/_widgets/table/Table.vue
  apps/web/src/common/modules/widgets/_widgets/table/widget-config.ts
Labels: pass/signedoff

#4310 refactor: change from amcharts to echarts
  apps/web/src/common/components/custom-date-modal/CustomDateModal.vue
  apps/web/src/common/modules/widgets/_helpers/widget-date-helper.ts
  apps/web/src/services/asset-inventory/components/MetricExplorerChart.vue
  apps/web/src/services/asset-inventory/components/MetricExplorerDataTable.vue
  apps/web/src/services/asset-inventory/components/MetricExplorerDonutChart.vue
  apps/web/src/services/asset-inventory/components/MetricExplorerHorizontalColumnChart.vue
  apps/web/src/services/asset-inventory/components/MetricExplorerLineChart.vue
  apps/web/src/services/asset-inventory/components/MetricExplorerMapChart.vue
Labels: pass/signedoff

#4313 feat: changed domain config name
  apps/web/src/services/preference/pages/admin/AdminDomainSettingsAutoDormancyConfigurationPage.vue
  apps/web/src/services/preference/types/domain-settings-type.ts
  apps/web/src/store/domain-settings/domain-settings-store.ts
Labels: pass/signedoff

#4312 fix(widget-overlay): add overlay warning modal trigger (options changed case) & fix project reference store bug
  apps/web/src/common/modules/widgets/_components/WidgetFormOverlay.vue
  apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2.vue
  apps/web/src/store/reference/project-reference-store.ts
Labels: pass/signedoff

#4315 fix: edit number card default optional field value & refactor icon/comparison field
  apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldComparison.vue
  apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldIcon.vue
  apps/web/src/common/modules/widgets/_widgets/number-card/widget-config.ts
  apps/web/src/common/modules/widgets/types/widget-field-type.ts
  apps/web/src/common/modules/widgets/types/widget-field-value-type.ts
Labels: pass/signedoff

#4316 fix: apply table widget feedback (header sticky, overlay close planning)
  apps/web/src/common/modules/widgets/_components/WidgetFormOverlay.vue
  apps/web/src/common/modules/widgets/_widgets/table/_component/WidgetDataTable.vue
Labels: pass/signedoff

#4320 chore: style fix
  apps/web/src/common/modules/widgets/_components/WidgetFormDataSourcePopover.vue
  apps/web/src/services/project/pages/ProjectDetailPage.vue
  apps/web/src/services/project/pages/ProjectDetailTabPage.vue
Labels: pass/signedoff

#4321 chore: changed mirinae
  apps/web/src/services/cost-explorer/components/AnomalyDetectionConfigurationInformation.vue
  apps/web/src/services/cost-explorer/components/AnomalyDetectionConfigurationInformationForm.vue
  apps/web/src/services/cost-explorer/components/AnomalyDetectionConfigurationRecipients.vue
  apps/web/src/services/cost-explorer/components/AnomalyDetectionConfigurationRecipientsForm.vue
  apps/web/src/services/cost-explorer/components/AnomalyDetectionConfigurationTable.vue
  apps/web/src/services/cost-explorer/components/AnomalyDetectionConfigurationTrend.vue
  apps/web/src/services/cost-explorer/components/AnomalyDetectionHistoryDetail.vue
  apps/web/src/services/cost-explorer/components/AnomalyDetectionHistoryTable.vue
  apps/web/src/services/cost-explorer/components/AnomalyDetectionPolicyRuleCard.vue
  apps/web/src/services/cost-explorer/components/CostAnalysisLSB.vue
  apps/web/src/services/cost-explorer/constants/anomaly-detection-constant.ts
  apps/web/src/services/cost-explorer/pages/AnomalyDetectionConfigurationCreatePage.vue
  apps/web/src/services/cost-explorer/pages/AnomalyDetectionConfigurationDetailPage.vue
  apps/web/src/services/cost-explorer/pages/AnomalyDetectionConfigurationPage.vue
  apps/web/src/services/cost-explorer/pages/AnomalyDetectionHistoryDetailPage.vue
  apps/web/src/services/cost-explorer/pages/AnomalyDetectionHistoryPage.vue
  apps/web/src/services/cost-explorer/pages/AnomalyDetectionPolicyPage.vue
  apps/web/src/services/preference/components/BookmarkDetailContainer.vue
  apps/web/src/services/preference/components/BookmarkManagementDetailTable.vue
  apps/web/src/services/preference/components/BookmarkManagementTable.vue
  apps/web/src/services/preference/components/DomainSettingsContainer.vue
  apps/web/src/services/preference/composables/bookmark-data-helper.ts
  apps/web/src/services/preference/constants/workspace-constant.ts
  apps/web/src/services/preference/pages/admin/AdminBookmarkPage.vue
  apps/web/src/services/preference/pages/admin/AdminDomainSettingsAutoDormancyConfigurationPage.vue
Labels: pass/signedoff

#4323 fix: apply cost-data-source metadata additional_info
  apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardAddForm.vue
Labels: pass/signedoff

#4325 fix: apply cost-data-source metadata additional label
  apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardAddForm.vue
Labels: pass/signedoff

#4333 chore: fixed minor bug
  apps/web/src/services/preference/pages/admin/AdminDomainSettingsDomainInformationPage.vue
Labels: pass/signedoff

#4335 chore: add favorite button to project detail header
  apps/web/src/services/project/pages/ProjectDetailPage.vue
Labels: pass/signedoff

#4336 chore: small fix
  apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardFilters.vue
Labels: pass/signedoff

#4334 feat: apply cost data source metadata additional_info
  apps/web/src/services/cost-explorer/components/CostAnalysisGroupBy.vue
  apps/web/src/services/cost-explorer/stores/cost-analysis-page-store.ts
Labels: pass/signedoff

#4338 chore: edit margin of context menu icon
  apps/web/src/services/dashboards/components/DashboardWidgetContainerV2.vue
  packages/mirinae/src/inputs/context-menu/context-menu-item/PContextMenuItem.vue
Labels: pass/signedoff

#4337 chore: apply pr review
  apps/web/src/services/asset-inventory/components/ServiceAccountAttachedGeneralAccounts.vue
  apps/web/src/services/asset-inventory/components/ServiceAccountBaseInformationDetail.vue
  apps/web/src/services/asset-inventory/helpers/dynamic-ui-schema-generator/dynamic-layout-schema-template.ts
  apps/web/src/services/asset-inventory/pages/ServiceAccountDetailPage.vue
  apps/web/src/services/asset-inventory/pages/ServiceAccountPage.vue
  apps/web/src/services/iam/components/UserManagementTabWorkspace.vue
  apps/web/src/services/preference/components/WorkspaceManagementTable.vue
Labels: pass/signedoff

#4344 chore: changed css
  apps/web/src/services/workspace-home/components/BookmarkBoard.vue
Labels: pass/signedoff

#4343 feat(table-widget): add total data to comparison field & apply date-field helper to comparison field
  apps/web/src/common/modules/widgets/_helpers/widget-field-helper.ts
  apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldComparison.vue
  apps/web/src/common/modules/widgets/_widgets/table/Table.vue
Labels: pass/signedoff

#4345 fix: apply multi unit to sub_total & translation
  apps/web/src/common/modules/widgets/_widgets/table/_component/WidgetDataTable.vue
  packages/language-pack/ja.json
  packages/language-pack/ko.json
Labels: pass/signedoff

#4351 chore: change colorset of echarts
  apps/web/src/common/modules/widgets/_components/WidgetFrame.vue
  apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/ClusteredColumnChart.vue
  apps/web/src/common/modules/widgets/_widgets/line-chart/LineChart.vue
  apps/web/src/common/modules/widgets/_widgets/pie-chart/PieChart.vue
  apps/web/src/common/modules/widgets/_widgets/stacked-area-chart/StackedAreaChart.vue
  apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/StackedColumnChart.vue
  apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/StackedHorizontalBarChart.vue
  apps/web/src/common/modules/widgets/_widgets/treemap/Treemap.vue
  apps/web/src/services/asset-inventory/components/MetricExplorerLineChart.vue
  apps/web/src/services/asset-inventory/pages/MetricExplorerDetailPage.vue
  apps/web/src/services/dashboards/components/DashboardReorderSidebar.vue
  apps/web/src/styles/colorsets.ts
Labels: pass/signedoff

#4352 feat: add sorting to table widget
  apps/web/src/common/modules/widgets/_widgets/table/Table.vue
  apps/web/src/common/modules/widgets/_widgets/table/_component/WidgetDataTable.vue
Labels: pass/signedoff

#4354 feat: apply account summary
  apps/web/public/images/home/img_workspace-home_account-summary_empty-state-background.png
  apps/web/src/services/preference/pages/admin/AdminDomainSettingsAutoDormancyConfigurationPage.vue
  apps/web/src/services/workspace-home/components/AccountSummary.vue
  apps/web/src/services/workspace-home/components/EmptySummaryData.vue
  apps/web/src/services/workspace-home/components/Summaries.vue
  apps/web/src/services/workspace-home/composables/use-workspace-home.ts
  apps/web/src/services/workspace-home/constants/workspace-home-constant.ts
Labels: pass/signedoff

#4353 fix: refactor accessToken process & fix cost-report bug
  apps/web/src/App.vue
  apps/web/src/lib/site-initializer/sso.ts
  apps/web/src/router/constant.ts
  apps/web/src/router/external-routes.ts
  apps/web/src/router/helpers/route-helper.ts
  apps/web/src/router/index.ts
  apps/web/src/router/integral-routes.ts
Labels: pass/signedoff

#4355 fix: remove unnecessary argument of loadWidget & edit loadWidget type
  apps/web/src/common/modules/widgets/_composables/use-widget-init-and-refresh.ts
  apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/ClusteredColumnChart.vue
  apps/web/src/common/modules/widgets/_widgets/gauge/Gauge.vue
  apps/web/src/common/modules/widgets/_widgets/geo-map/GeoMap.vue
  apps/web/src/common/modules/widgets/_widgets/heatmap/Heatmap.vue
  apps/web/src/common/modules/widgets/_widgets/line-chart/LineChart.vue
  apps/web/src/common/modules/widgets/_widgets/number-card/NumberCard.vue
  apps/web/src/common/modules/widgets/_widgets/pie-chart/PieChart.vue
  apps/web/src/common/modules/widgets/_widgets/progress-card/ProgressCard.vue
  apps/web/src/common/modules/widgets/_widgets/stacked-area-chart/StackedAreaChart.vue
  apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/StackedColumnChart.vue
  apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/StackedHorizontalBarChart.vue
  apps/web/src/common/modules/widgets/_widgets/treemap/Treemap.vue
  apps/web/src/common/modules/widgets/types/widget-display-type.ts
Labels: pass/signedoff

#4356 chore: apply tooltip
  apps/web/src/services/workspace-home/components/AccountSummary.vue
Labels: pass/signedoff

#4358 feat: apply pagination to table widget
  apps/web/src/common/modules/widgets/_widgets/table/Table.vue
  apps/web/src/common/modules/widgets/_widgets/table/_component/WidgetDataTable.vue
Labels: pass/signedoff

#4361 fix(cost-report): set pageStart, pageLimit on init
  apps/web/src/services/cost-explorer/components/CostReportReportsTab.vue
Labels: pass/signedoff

#4360 feat: add dashboard count to dashboard LSB & add lsb item spec (subText, showSubItemCount)
  apps/web/src/common/modules/navigations/lsb/modules/LSBCollapsibleMenuItem.vue
  apps/web/src/common/modules/navigations/lsb/modules/LSBTopTitleMenuItem.vue
  apps/web/src/common/modules/navigations/lsb/type.ts
  apps/web/src/services/dashboards/DashboardsLSB.vue
Labels: pass/signedoff

#4362 feat: apply project dashboard mechanically
  apps/web/src/services/project/pages/ProjectDashboardPage.vue
  apps/web/src/store/dashboard/dashboard-store.ts
Labels: pass/signedoff

#4364 feat: update menu highlight tag
  apps/web/src/lib/menu/menu-info.ts
Labels: pass/signedoff

#4363 fix: apply Y-Axis desc display
  apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/StackedHorizontalBarChart.vue
Labels: pass/signedoff

#4366 chore: small fix
  apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2.vue
  apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2WidgetForm.vue
  apps/web/src/common/modules/widgets/_widgets/table/Table.vue
Labels: pass/signedoff

#4367 feat: create alertPublicDetailPage component
  apps/web/src/common/pages/AlertPublicDetailPage.vue
  apps/web/src/router/constant.ts
  apps/web/src/router/external-routes.ts
  apps/web/src/services/alert-manager/components/AlertDetailInfoTable.vue
  apps/web/src/services/alert-manager/constants/alert-constant.ts
Labels: pass/signedoff

#4368 feat: set resizer to step2
  apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep1.vue
  apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2.vue
  apps/web/src/services/dashboards/components/DashboardReorderSidebar.vue
Labels: pass/signedoff

#4369 refactor: change from am5 to echarts
  apps/web/src/common/modules/widgets/_helpers/widget-date-helper.ts
  apps/web/src/common/pages/CostReportDetailPage.vue
  apps/web/src/services/asset-inventory/components/MetricExplorerLineChart.vue
  apps/web/src/services/asset-inventory/helpers/asset-analysis-data-table-helper.ts
  apps/web/src/services/cost-explorer/components/CostAnalysisChart.vue
  apps/web/src/services/cost-explorer/components/CostAnalysisGroupBy.vue
  apps/web/src/services/cost-explorer/components/CostAnalysisStackedColumnChart.vue
  apps/web/src/services/cost-explorer/components/CostReportMonthlyTotalAmountSummaryCard.vue
  apps/web/src/services/cost-explorer/components/CostReportOverviewCostTrendChart.vue
  apps/web/src/services/cost-explorer/helpers/cost-explorer-chart-data-helper.ts
  apps/web/src/services/cost-explorer/types/cost-analyze-type.ts
Labels: pass/signedoff

#4371 chore: change default value of pie chart type & revert
  apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep1.vue
  apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2.vue
  apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldLineBy.vue
  apps/web/src/common/modules/widgets/_widget-fields/WidgetFieldPieChartType.vue
  apps/web/src/common/modules/widgets/_widgets/pie-chart/PieChart.vue
  apps/web/src/common/modules/widgets/_widgets/pie-chart/widget-config.ts
Labels: pass/signedoff, fail/signedoff

#4372 feat: create project dashboard contents
  apps/web/src/services/project/pages/ProjectDashboardPage.vue
  apps/web/src/store/dashboard/dashboard-store.ts
Labels: pass/signedoff

#4373 refactor: change from svg to png
  apps/web/src/common/modules/navigations/top-bar/modules/top-bar-toolset/modules/top-bar-profile/TopBarProfile.vue
  apps/web/src/services/my-page/pages/UserAccountPage.vue
  packages/mirinae/src/data-display/board/mock.ts
  packages/mirinae/src/foundation/icons/icon-assets/ic_provider-azure.svg
  packages/mirinae/src/foundation/icons/icon-assets/img_avatar_admin.svg
  packages/mirinae/src/foundation/icons/icon-assets/img_avatar_no-role.svg
  packages/mirinae/src/foundation/icons/icon-assets/img_avatar_project-admin.svg
  packages/mirinae/src/foundation/icons/icon-assets/img_avatar_root-account.svg
  packages/mirinae/src/foundation/icons/icon-assets/img_avatar_system-admin.svg
  packages/mirinae/src/foundation/icons/icon-assets/img_avatar_user.svg
  packages/mirinae/src/foundation/icons/icon-assets/img_avatar_workspace-member.svg
  packages/mirinae/src/foundation/icons/icon-assets/img_avatar_workspace-owner.svg
  packages/mirinae/src/foundation/icons/icon-assets/img_resource_default.svg
  packages/mirinae/src/foundation/icons/icon-assets/img_resource_server.svg
  packages/mirinae/src/foundation/icons/p-icons/ic_provider-azure.js
  packages/mirinae/src/foundation/icons/p-icons/img_avatar_admin.js
  packages/mirinae/src/foundation/icons/p-icons/img_avatar_no-role.js
  packages/mirinae/src/foundation/icons/p-icons/img_avatar_project-admin.js
  packages/mirinae/src/foundation/icons/p-icons/img_avatar_root-account.js
  packages/mirinae/src/foundation/icons/p-icons/img_avatar_system-admin.js
  packages/mirinae/src/foundation/icons/p-icons/img_avatar_user.js
  packages/mirinae/src/foundation/icons/p-icons/img_avatar_workspace-member.js
  packages/mirinae/src/foundation/icons/p-icons/img_avatar_workspace-owner.js
  packages/mirinae/src/foundation/icons/p-icons/img_resource_default.js
  packages/mirinae/src/foundation/icons/p-icons/img_resource_server.js
  packages/mirinae/src/foundation/icons/p-icons/index.js
  packages/mirinae/src/inputs/select-card/story-helper.ts
Labels: pass/signedoff

#4374 feat: set project dashboard variables
  apps/web/src/services/dashboards/components/DashboardVariablesV2.vue
  apps/web/src/services/project/pages/ProjectDashboardPage.vue
Labels: pass/signedoff

#4375 fix: fix minor issue
  apps/web/src/common/components/scoped-notification/ScopedNotification.vue
  apps/web/src/services/cost-explorer/components/CostAnalysisStackedColumnChart.vue
Labels: pass/signedoff

#4376 refactor(budget): change from am5 to echarts
  apps/web/src/services/cost-explorer/components/BudgetDetailSummaryChart.vue
Labels: pass/signedoff

#4380 feat: set `unit` to widget tooltip
  apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2.vue
  apps/web/src/common/modules/widgets/_components/WidgetFrame.vue
  apps/web/src/common/modules/widgets/_composables/use-widget-frame.ts
  apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/ClusteredColumnChart.vue
  apps/web/src/common/modules/widgets/_widgets/geo-map/GeoMap.vue
  apps/web/src/common/modules/widgets/_widgets/heatmap/Heatmap.vue
  apps/web/src/common/modules/widgets/_widgets/line-chart/LineChart.vue
  apps/web/src/common/modules/widgets/_widgets/pie-chart/PieChart.vue
  apps/web/src/common/modules/widgets/_widgets/stacked-area-chart/StackedAreaChart.vue
  apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/StackedColumnChart.vue
  apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/StackedHorizontalBarChart.vue
  apps/web/src/common/modules/widgets/_widgets/treemap/Treemap.vue
  apps/web/src/common/modules/widgets/types/widget-frame-type.ts
Labels: pass/signedoff

#4382 feat: apply project vars to project dashboard
  apps/web/src/services/dashboards/stores/dashboard-detail-info-store.ts
  apps/web/src/services/project/pages/ProjectDashboardPage.vue
Labels: pass/signedoff

#4385 chore: handle no-reference-name case in data table preview
  apps/web/src/common/modules/widgets/_components/WidgetFormOverlayPreviewTable.vue
Labels: pass/signedoff

#4387 fix: apply project_id filter and disable-management to project dashboard
  apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2.vue
  apps/web/src/services/dashboards/stores/dashboard-detail-info-store.ts
  apps/web/src/services/project/pages/ProjectDashboardPage.vue
Labels: pass/signedoff

#4390 fix: fix domain config value bug
  apps/web/src/services/preference/pages/admin/AdminDomainSettingsAnomalyDetectionConfigurationPage.vue
Labels: pass/signedoff

#4395 feat: apply New timediff
  apps/web/src/common/modules/widgets/_components/WidgetFormOverlayPreviewTable.vue
  apps/web/src/common/modules/widgets/_helpers/widget-helper.ts
  apps/web/src/common/modules/widgets/_store/widget-generate-store.ts
  apps/web/src/common/modules/widgets/_widgets/table/_component/WidgetDataTable.vue
  apps/web/src/common/modules/widgets/types/widget-model.ts
Labels: pass/signedoff

#4397 fix: solve widget form valid-map issue
  apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2WidgetForm.vue
  apps/web/src/common/modules/widgets/_store/widget-generate-store.ts
Labels: pass/signedoff

#4400 chore(widget-form): solve small issues
  apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2WidgetForm.vue
  apps/web/src/common/modules/widgets/_widgets/table/Table.vue
Labels: pass/signedoff

#4401 chore: Add translation - from [English] to [Korean/Japanese]
  packages/language-pack/console-translation-2.8.babel
  packages/language-pack/ja.json
  packages/language-pack/ko.json
Labels: pass/signedoff

#4399 fix: fix minor changes in AlertDetailPage
  apps/web/src/schema/monitoring/alert/model.ts
  apps/web/src/services/alert-manager/components/AlertDetailInfoTable.vue
  apps/web/src/services/alert-manager/components/AlertDetailResponder.vue
  apps/web/src/services/alert-manager/components/AlertDetailTabs.vue
  apps/web/src/services/alert-manager/components/AlertMainDataTable.vue
  apps/web/src/services/project/components/ProjectAlertSettingsTab.vue
Labels: pass/signedoff

#4402 chore: apply new widget title to widget-clone & small fix
  apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2WidgetForm.vue
  apps/web/src/services/dashboards/components/DashboardWidgetContainerV2.vue
Labels: pass/signedoff

#4403 feat: preparation for API integration
  apps/web/src/schema/monitoring/webhook/model.ts
  apps/web/src/services/project/components/ProjectAlertEventRuleConditionForm.vue
  apps/web/src/services/project/components/ProjectAlertEventRuleForm.vue
  apps/web/src/services/project/components/ProjectAlertWebhookTab.vue
  apps/web/src/services/project/pages/ProjectDetailTabPage.vue
Labels: pass/signedoff

#4405 feat: apply new plan about timediff (day is deprecated)
  apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardAddForm.vue
  apps/web/src/common/modules/widgets/types/widget-model.ts
Labels: pass/signedoff

#4412 feat: remove scan job in dev_build workflow
  .github/workflows/dispatch_dev_build.yaml
Labels: pass/signedoff

#4408 feat: apply changed design
  apps/web/src/services/project/components/ProjectAlertWebhookCreateStep2.vue
  apps/web/src/services/project/components/ProjectAlertWebhookUpdateModal.vue
  apps/web/src/services/project/pages/ProjectDetailTabPage.vue
Labels: pass/signedoff

#4414 feat: remove email format when adding users
  apps/web/src/services/iam/components/UserManagementAddModal.vue
  apps/web/src/services/iam/components/UserManagementAddPassword.vue
  apps/web/src/services/iam/components/UserManagementAddUser.vue
  apps/web/src/services/iam/constants/user-constant.ts
  apps/web/src/services/iam/types/user-type.ts
Labels: pass/signedoff

#4415 chore: hide metadata option_schema
  apps/web/src/services/project/components/ProjectAlertWebhookCreateStep2.vue
Labels: pass/signedoff

#4417 feat: delete `DASHBOARD_EDITABLE_DOMAINS` config
  apps/web/src/services/asset-inventory/components/MetricExplorerDonutChart.vue
  apps/web/src/services/asset-inventory/components/MetricExplorerHorizontalColumnChart.vue
  apps/web/src/services/asset-inventory/components/MetricExplorerLineChart.vue
  apps/web/src/services/asset-inventory/components/MetricExplorerMapChart.vue
  apps/web/src/services/dashboards/components/DashboardDetailHeader.vue
  apps/web/src/services/dashboards/stores/dashboard-detail-info-store.ts
Labels: pass/signedoff

#4418 fix: fix metric chart bug
  apps/web/src/services/asset-inventory/components/MetricExplorerDonutChart.vue
  apps/web/src/services/asset-inventory/components/MetricExplorerHorizontalColumnChart.vue
  apps/web/src/services/asset-inventory/components/MetricExplorerLineChart.vue
  apps/web/src/services/asset-inventory/components/MetricExplorerMapChart.vue
Labels: pass/signedoff

#4419 feat: apply new timediff expression plan
  apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardAddContents.vue
  apps/web/src/common/modules/widgets/_components/WidgetFormOverlayPreviewTable.vue
  apps/web/src/common/modules/widgets/_widgets/table/_component/WidgetDataTable.vue
  apps/web/src/services/dashboards/components/DashboardWidgetContainerV2.vue
Labels: pass/signedoff
