Repository cloudforet-io/console, pull requests merged in 2025-05, with the labels that each got.

#5832 feat(vue-query-devtools): install custom vue-query devtools sdk
  apps/web/package.json
  apps/web/src/App.vue
  package-lock.json
Labels: pass/signedoff, self_approved/review

#5836 feat: update service landing page - pagination as service_healthy
  apps/web/src/schema/alert-manager/service/constants.ts
  apps/web/src/schema/alert-manager/service/model.ts
  apps/web/src/schema/alert-manager/service/type.ts
  apps/web/src/services/alert-manager/v2/components/ServiceDetailHeader.vue
  apps/web/src/services/alert-manager/v2/components/ServiceList.vue
  apps/web/src/services/alert-manager/v2/stores/service-list-page-store.ts
Labels: pass/signedoff, self_approved/review

#5837 Feat: update service landing page - pagination as service_healthy
  apps/web/src/schema/alert-manager/service/constants.ts
  apps/web/src/schema/alert-manager/service/model.ts
  apps/web/src/schema/alert-manager/service/type.ts
  apps/web/src/services/alert-manager/v2/components/ServiceDetailHeader.vue
  apps/web/src/services/alert-manager/v2/components/ServiceList.vue
  apps/web/src/services/alert-manager/v2/stores/service-list-page-store.ts
Labels: pass/signedoff, self_approved/review

#5843 feat: update model of report adjustment
  apps/web/src/api-clients/_common/constants/api-doc-constant.ts
  apps/web/src/api-clients/cost-analysis/report-adjustment-policy/composables/use-report-adjustment-policy-api.ts
  apps/web/src/api-clients/cost-analysis/report-adjustment-policy/schema/api-verbs/change-order.ts
  apps/web/src/api-clients/cost-analysis/report-adjustment-policy/schema/api-verbs/create.ts
  apps/web/src/api-clients/cost-analysis/report-adjustment-policy/schema/api-verbs/delete.ts
  apps/web/src/api-clients/cost-analysis/report-adjustment-policy/schema/api-verbs/get.ts
  apps/web/src/api-clients/cost-analysis/report-adjustment-policy/schema/api-verbs/list.ts
  apps/web/src/api-clients/cost-analysis/report-adjustment-policy/schema/api-verbs/update.ts
  apps/web/src/api-clients/cost-analysis/report-adjustment-policy/schema/model.ts
  apps/web/src/api-clients/cost-analysis/report-adjustment-policy/schema/type.ts
  apps/web/src/api-clients/cost-analysis/report-adjustment/composables/use-report-adjustment-api.ts
  apps/web/src/api-clients/cost-analysis/report-adjustment/schema/api-verbs/change-order.ts
  apps/web/src/api-clients/cost-analysis/report-adjustment/schema/api-verbs/create.ts
  apps/web/src/api-clients/cost-analysis/report-adjustment/schema/api-verbs/delete.ts
  apps/web/src/api-clients/cost-analysis/report-adjustment/schema/api-verbs/get.ts
  apps/web/src/api-clients/cost-analysis/report-adjustment/schema/api-verbs/list.ts
  apps/web/src/api-clients/cost-analysis/report-adjustment/schema/api-verbs/update.ts
  apps/web/src/api-clients/cost-analysis/report-adjustment/schema/model.ts
  apps/web/src/api-clients/cost-analysis/report-adjustment/schema/type.ts
Labels: pass/signedoff

#5844 chore: markup adjustment form
  apps/web/src/services/cost-explorer/components/AdvancedSettingsAdjustmentForm.vue
  apps/web/src/services/cost-explorer/components/AdvancedSettingsSetAdjustmentsOverlay.vue
Labels: pass/signedoff

#5848 feat(alert-service-list): update service list pagination improvement
  apps/web/src/services/alert-manager/v2/components/ServiceList.vue
Labels: pass/signedoff, self_approved/review

#5853 chore(alert-service): update service main page pagination
  apps/web/src/services/alert-manager/v2/components/ServiceDetailHeader.vue
  apps/web/src/services/alert-manager/v2/components/ServiceList.vue
Labels: pass/signedoff, self_approved/review

#5854 chore: apply jp at ops-flow
  apps/web/src/services/ops-flow/task-management-templates/translations/ja.json
Labels: pass/signedoff, self_approved/review

#5855 feat: changed excel export API
  apps/web/src/services/alert-manager/v2/components/AlertsManagementTable.vue
Labels: pass/signedoff, self_approved/review

#5856 refactor: use vuequery rather than api list
  apps/web/src/services/cost-explorer/components/AdvancedSettingsAdjustmentGroupForm.vue
  apps/web/src/services/cost-explorer/components/AdvancedSettingsSetAdjustmentsOverlay.vue
  apps/web/src/services/cost-explorer/composables/queries/use-report-adjustment-policy-query.ts
  apps/web/src/services/cost-explorer/composables/queries/use-report-adjustment-query.ts
  apps/web/src/services/cost-explorer/stores/advanced-settings-page-store.ts
  apps/web/src/services/cost-explorer/types/report-adjustment-type.ts
Labels: pass/signedoff

#5857 feat(service-pagination): update service main page pagination
  apps/web/src/services/alert-manager/v2/components/ServiceDetailHeader.vue
  apps/web/src/services/alert-manager/v2/components/ServiceList.vue
Labels: pass/signedoff, self_approved/review

#5858 feat: remove unnecessary console log
  apps/web/src/services/alert-manager/v2/components/ServiceList.vue
Labels: pass/signedoff, self_approved/review

#5860 chore: edit random-reviewer-assignment CI
  .github/workflows/pull_request_random_reviewer_assignment.yaml
Labels: pass/signedoff, self_approved/review

#5867 fix: fix timezone-aware time bug
  apps/web/src/services/alert-manager/v2/composables/alert-table-data.ts
Labels: pass/signedoff

#5865 chore(service-pagination): fix bug about queryTag with pagination
  apps/web/src/services/alert-manager/v2/components/ServiceDetailHeader.vue
  apps/web/src/services/alert-manager/v2/components/ServiceList.vue
  apps/web/src/services/alert-manager/v2/stores/service-list-page-store.ts
Labels: pass/signedoff

#5868 feat: merge to master
  .github/workflows/pull_request_random_reviewer_assignment.yaml
  apps/web/src/services/alert-manager/v2/composables/alert-table-data.ts
Labels: fail/signedoff, self_approved/review

#5870 fix: fixed time bug
  apps/web/src/services/service-account/components/ServiceAccountAttachedGeneralAccounts.vue
Labels: pass/signedoff

#5873 feat: add column at service account attached general accounts table
  apps/web/src/services/service-account/components/ServiceAccountAttachedGeneralAccounts.vue
Labels: pass/signedoff

#5874 feat: create/update/delete/change-order adjustment items
  apps/web/src/api-clients/cost-analysis/report-adjustment/schema/type.ts
  apps/web/src/services/cost-explorer/components/AdvancedSettingsAdjustmentsForm.vue
  apps/web/src/services/cost-explorer/components/AdvancedSettingsSetAdjustmentsOverlay.vue
  apps/web/src/services/cost-explorer/composables/queries/use-report-adjustment-query.ts
  apps/web/src/services/cost-explorer/stores/advanced-settings-page-store.ts
  apps/web/src/services/cost-explorer/types/report-adjustment-type.ts
Labels: pass/signedoff

#5879 feat: apply vue-query to alert api
  apps/web/src/services/alert-manager/v2/components/AlertDetailDeleteModal.vue
  apps/web/src/services/alert-manager/v2/components/AlertDetailEditModal.vue
  apps/web/src/services/alert-manager/v2/components/AlertDetailInfoTable.vue
  apps/web/src/services/alert-manager/v2/components/AlertDetailInfoTableDescription.vue
  apps/web/src/services/alert-manager/v2/components/AlertDetailNote.vue
  apps/web/src/services/alert-manager/v2/components/AlertDetailSummary.vue
  apps/web/src/services/alert-manager/v2/components/AlertDetailTabsDetails.vue
  apps/web/src/services/alert-manager/v2/components/AlertDetailTabsTimeline.vue
  apps/web/src/services/alert-manager/v2/components/AlertDetailTabsTimelineModal.vue
  apps/web/src/services/alert-manager/v2/components/AlertsDetailHeader.vue
  apps/web/src/services/alert-manager/v2/components/AlertsManagementTable.vue
  apps/web/src/services/alert-manager/v2/components/ServiceDetailTabsOverviewStatusTable.vue
  apps/web/src/services/alert-manager/v2/composables/use-alert-get-query.ts
  apps/web/src/services/alert-manager/v2/composables/use-alert-list-query.ts
  apps/web/src/services/alert-manager/v2/composables/use-alert-update-mutation.ts
  apps/web/src/services/alert-manager/v2/pages/AlertsDetailPage.vue
  apps/web/src/services/alert-manager/v2/stores/alert-detail-page-store.ts
  apps/web/src/services/asset-inventory/components/CloudServiceAlertsTab.vue
Labels: pass/signedoff, self_approved/review

#5877 feat(reference-model): create integrated `Reference Model`
  apps/web/src/query/query-key/_helpers/query-key-helper.ts
  apps/web/src/query/query-key/use-reference-query-key.ts
  apps/web/src/query/query-key/use-service-query-key.ts
  apps/web/src/query/reference/core/common/use-reference-model-sync.ts
  apps/web/src/query/reference/core/common/use-watched-query-cache.ts
  apps/web/src/query/reference/core/reference-list/use-reference-full-list.ts
  apps/web/src/query/reference/core/reference-map/use-batched-reference-fetch.ts
  apps/web/src/query/reference/core/reference-map/use-reference-map.ts
  apps/web/src/query/reference/core/reference-query/use-reference-query-list.ts
  apps/web/src/query/reference/core/reference-query/use-reference-query-stat.ts
  apps/web/src/query/reference/core/reference-query/use-reference-query.ts
  apps/web/src/query/reference/core/use-reference-model.ts
  apps/web/src/query/reference/helpers/reference-model-menu-handler.ts
  apps/web/src/query/reference/metric/config.ts
  apps/web/src/query/reference/reference-config.ts
  apps/web/src/query/reference/types/reference-data-type.ts
  apps/web/src/query/reference/types/reference-query-type.ts
  apps/web/src/query/reference/types/reference-type.ts
Labels: pass/signedoff

#5889 feat: set sort(created_at/asc) to cost-report-config/list
  apps/web/src/services/advanced/pages/admin/AdminDomainSettingsAutoDormancyConfigurationPage.vue
  apps/web/src/services/advanced/store/workspace-group-page-store.ts
  apps/web/src/services/advanced/store/workspace-page-store.ts
  apps/web/src/services/cost-explorer/composables/queries/use-cost-report-config-query.ts
  apps/web/src/services/cost-explorer/stores/cost-report-page-store.ts
  apps/web/src/services/service-account/stores/service-account-page-store.ts
  apps/web/src/services/workspace-home/shared/composables/use-cost-report-config-query.ts
Labels: pass/signedoff

#5890 refactor: refactor code
  apps/web/src/common/pages/CostReportDetailPage.vue
Labels: pass/signedoff

#5892 feat: update provider section
  apps/web/src/common/pages/CostReportDetailPage.vue
Labels: pass/signedoff

#5888 fix(dashboard): edit admin dashboard workspace vars-filter scenario
  apps/web/src/services/_shared/dashboard/dashboard-detail/components/DashboardToolsetScope.vue
  apps/web/src/services/_shared/dashboard/dashboard-detail/stores/dashboard-detail-info-store.ts
Labels: pass/signedoff, self_approved/review

#5891 fix: apply minor feedback
  apps/web/src/lib/site-initializer/index.ts
  apps/web/src/services/asset-inventory/components/CollectorHistoryJobStatusChart.vue
Labels: pass/signedoff

#5896 fix: fixed project id filter bug
  apps/web/src/services/project/v2/components/ProjectOverview.vue
  apps/web/src/services/project/v2/composables/queries/use-project-children-list-query.ts
  apps/web/src/services/workspace-home/shared/composables/use-project-ids-from-group.ts
Labels: pass/signedoff

#5895 feat(budget): update mutation of budget detail page - heading with vue query
  apps/web/src/services/cost-explorer/components/BudgetDeleteCheckModal.vue
  apps/web/src/services/cost-explorer/components/BudgetDetailDeleteModal.vue
  apps/web/src/services/cost-explorer/components/BudgetDetailHeading.vue
  apps/web/src/services/cost-explorer/components/BudgetMainList.vue
  apps/web/src/services/cost-explorer/components/BudgetNameEditModal.vue
  apps/web/src/services/cost-explorer/composables/use-budget-delete-mutation.ts
  apps/web/src/services/cost-explorer/composables/use-budget-get-query.ts
  apps/web/src/services/cost-explorer/composables/use-budget-query.ts
  apps/web/src/services/cost-explorer/composables/use-budget-set-notification-mutation.ts
  apps/web/src/services/cost-explorer/composables/use-budget-update-mutation.ts
  apps/web/src/services/cost-explorer/pages/BudgetDetailPage.vue
  apps/web/src/services/cost-explorer/routes/admin/routes.ts
Labels: pass/signedoff
