Repository cloudforet-io/console, pull requests merged in 2025-01, with the labels that each got.

#5372 fix: solve widget drawChart bug
  apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/ClusteredColumnChart.vue
  apps/web/src/common/modules/widgets/_widgets/gauge/Gauge.vue
  apps/web/src/common/modules/widgets/_widgets/geo-map/GeoMap.vue
  apps/web/src/common/modules/widgets/_widgets/heatmap/Heatmap.vue
  apps/web/src/common/modules/widgets/_widgets/line-chart/LineChart.vue
  apps/web/src/common/modules/widgets/_widgets/pie-chart/PieChart.vue
  apps/web/src/common/modules/widgets/_widgets/sankey-chart/SankeyChart.vue
  apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/StackedColumnChart.vue
  apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/StackedHorizontalBarChart.vue
  apps/web/src/common/modules/widgets/_widgets/treemap/Treemap.vue
Labels: pass/signedoff

#5373 chore: set series name to clustered chart tooltip & reverse order of horizontal bar chart
  apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/ClusteredColumnChart.vue
  apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/StackedHorizontalBarChart.vue
Labels: pass/signedoff

#5377 chore: add sankey icon
  apps/web/src/common/modules/widgets/_constants/widget-components-constant.ts
  packages/mirinae/src/foundation/icons/icon-assets/ic_chart-sankey-chart.svg
  packages/mirinae/src/foundation/icons/p-icons/ic_chart-sankey-chart.js
  packages/mirinae/src/foundation/icons/p-icons/index.js
Labels: pass/signedoff

#5378 chore: edit sankey tooltip
  apps/web/src/common/modules/widgets/_widgets/sankey-chart/SankeyChart.vue
Labels: pass/signedoff

#5376 feat: add DataSelector component for improved menu selection functionality
  apps/web/src/common/components/select/DataSelector.vue
  apps/web/src/common/components/select/type.ts
  apps/web/src/common/modules/widgets/_components/WidgetFormCostDataSourcePopper.vue
  apps/web/src/lib/variable-models/variable-model-menu-handler.ts
  packages/mirinae/src/controls/dropdown/select-dropdown/type.ts
  packages/mirinae/src/hooks/index.ts
  packages/mirinae/src/hooks/use-context-menu-attach/UseContextMenuAttach.mdx
  packages/mirinae/src/hooks/use-context-menu-attach/story-helper.ts
  packages/mirinae/src/hooks/use-context-menu-attach/use-context-menu-attach.stories.ts
  packages/mirinae/src/hooks/use-context-menu-attach/use-context-menu-attach.ts
  packages/mirinae/src/hooks/use-context-menu-controller/UseContextMenuController.mdx
  packages/mirinae/src/hooks/use-context-menu-controller/story-helper.ts
  packages/mirinae/src/hooks/use-context-menu-controller/use-context-menu-controller.stories.ts
  packages/mirinae/src/hooks/use-context-menu-controller/use-context-menu-controller.ts
  packages/mirinae/src/hooks/use-context-menu-items/UseContextMenuItems.mdx
  packages/mirinae/src/hooks/use-context-menu-items/story-helper.ts
  packages/mirinae/src/hooks/use-context-menu-items/use-context-menu-items.stories.ts
  packages/mirinae/src/hooks/use-context-menu-items/use-context-menu-items.ts
  packages/mirinae/src/hooks/use-context-menu-style/UseContextMenuStyle.mdx
  packages/mirinae/src/hooks/use-context-menu-style/story-helper.ts
  packages/mirinae/src/hooks/use-context-menu-style/use-context-menu-style.stories.ts
  packages/mirinae/src/hooks/use-context-menu-style/use-context-menu-style.ts
Labels: pass/signedoff

#5382 chore: changed css
  apps/web/src/services/alert-manager/components/ServiceDetailTabsOverviewStatusTable.vue
Labels: pass/signedoff

#5384 feat(pivot): prevent selection of pivot when trying transform & apply new pivot planning
  apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformDataTableDropdown.vue
  apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformPivotForm.vue
  apps/web/src/common/modules/widgets/_components/WidgetFormOverlayPreviewTable.vue
Labels: pass/signedoff

#5389 fix(widget-load): update widget load data type
  apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/ClusteredColumnChart.vue
  apps/web/src/common/modules/widgets/_widgets/color-coded-heatmap/ColorCodedHeatmap.vue
  apps/web/src/common/modules/widgets/_widgets/color-coded-table-heatmap/ColorCodedTableHeatmap.vue
  apps/web/src/common/modules/widgets/_widgets/gauge/Gauge.vue
  apps/web/src/common/modules/widgets/_widgets/geo-map/GeoMap.vue
  apps/web/src/common/modules/widgets/_widgets/heatmap/Heatmap.vue
  apps/web/src/common/modules/widgets/_widgets/line-chart/LineChart.vue
  apps/web/src/common/modules/widgets/_widgets/number-card/NumberCard.vue
  apps/web/src/common/modules/widgets/_widgets/pie-chart/PieChart.vue
  apps/web/src/common/modules/widgets/_widgets/sankey-chart/SankeyChart.vue
  apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/StackedColumnChart.vue
  apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/StackedHorizontalBarChart.vue
  apps/web/src/common/modules/widgets/_widgets/table/Table.vue
  apps/web/src/common/modules/widgets/_widgets/treemap/Treemap.vue
  apps/web/src/common/modules/widgets/types/widget-data-type.ts
  apps/web/src/schema/dashboard/private-data-table/model.ts
  apps/web/src/schema/dashboard/public-data-table/model.ts
Labels: pass/signedoff

#5392 fix(pivot): apply new pivot planning to table widget and widget form
  apps/web/src/common/modules/widgets/_components/WidgetFormOverlayPreviewTable.vue
  apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2WidgetForm.vue
  apps/web/src/common/modules/widgets/_widget-field-value-manager/constant/default-value-registry.ts
  apps/web/src/common/modules/widgets/_widget-fields/data-field/WidgetFieldDataField.vue
  apps/web/src/common/modules/widgets/_widget-fields/sub-total/WidgetFieldSubTotal.vue
  apps/web/src/common/modules/widgets/_widget-fields/table-column-comparison/WidgetFieldTableColumnComparison.vue
  apps/web/src/common/modules/widgets/_widgets/table/Table.vue
  apps/web/src/common/modules/widgets/_widgets/table/widget-config.ts
Labels: pass/signedoff

#5390 feat: refactor xy charts with pivot data
  apps/web/src/common/modules/widgets/_composables/use-widget-frame.ts
  apps/web/src/common/modules/widgets/_helpers/widget-load-helper.ts
  apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/ClusteredColumnChart.vue
  apps/web/src/common/modules/widgets/_widgets/color-coded-heatmap/ColorCodedHeatmap.vue
  apps/web/src/common/modules/widgets/_widgets/color-coded-table-heatmap/ColorCodedTableHeatmap.vue
  apps/web/src/common/modules/widgets/_widgets/gauge/Gauge.vue
  apps/web/src/common/modules/widgets/_widgets/line-chart/LineChart.vue
  apps/web/src/common/modules/widgets/_widgets/pie-chart/PieChart.vue
  apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/StackedColumnChart.vue
  apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/StackedHorizontalBarChart.vue
  apps/web/src/common/modules/widgets/_widgets/treemap/Treemap.vue
  apps/web/src/services/dashboards/components/dashboard-folder/DashboardFolderTreeItem.vue
  apps/web/src/services/dashboards/components/dashboard-main/DashboardLSBTree.vue
Labels: pass/signedoff

#5387 Feat: Alert Manager v2 - IAM QA 2
  apps/web/src/schema/identity/user-group/constants.ts
  apps/web/src/schema/identity/user-group/type.ts
  apps/web/src/services/iam/components/SelectChannelCard.vue
  apps/web/src/services/iam/components/UserAssignToGroupModal.vue
  apps/web/src/services/iam/components/UserGroupChannelAddFormData.vue
  apps/web/src/services/iam/components/UserGroupChannelCreateModal.vue
  apps/web/src/services/iam/components/UserGroupChannelSetInputForm.vue
  apps/web/src/services/iam/components/UserGroupChannelSetModal.vue
  apps/web/src/services/iam/components/UserGroupDeleteDoubleCheckModal.vue
  apps/web/src/services/iam/components/UserGroupManagementAddUsersModal.vue
  apps/web/src/services/iam/components/UserGroupManagementTabNotificationChannel.vue
  apps/web/src/services/iam/components/UserGroupManagementTabUsers.vue
  apps/web/src/services/iam/components/UserGroupManagementTable.vue
  apps/web/src/services/iam/components/UserManagementHeader.vue
  apps/web/src/services/iam/components/UserManagementStatusModal.vue
  apps/web/src/services/iam/components/UserManagementTable.vue
  apps/web/src/services/iam/constants/user-group-constant.ts
  apps/web/src/services/iam/store/notification-channel-create-form-store.ts
Labels: pass/signedoff

#5396 fix: display user-add Modal after creating workspace and add condition
  apps/web/src/services/advanced/pages/admin/AdminWorkspacesPage.vue
  apps/web/src/services/iam/components/UserManagementAddUser.vue
Labels: pass/signedoff

#5398 fix: display user-add Modal after creating workspace and add conditio…
  apps/web/src/services/advanced/pages/admin/AdminWorkspacesPage.vue
  apps/web/src/services/iam/components/UserManagementAddUser.vue
Labels: pass/signedoff

#5401 feat: apply user select dropdown at opsFlow
  apps/web/src/common/modules/user/UserSelectDropdown.vue
  apps/web/src/router/alert-manager-v1-admin-routes.ts
  apps/web/src/router/alert-manager-v1-workspace-routes.ts
  apps/web/src/services/ops-flow/components/BoardTaskFilters.vue
  apps/web/src/services/ops-flow/components/TaskTypeForm.vue
  apps/web/src/services/ops-flow/task-fields-form/field-templates/UserTaskField.vue
Labels: pass/signedoff

#5397 fix: fix resize bug in heatmap table
  apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/ClusteredColumnChart.vue
  apps/web/src/common/modules/widgets/_widgets/color-coded-table-heatmap/ColorCodedTableHeatmap.vue
  apps/web/src/common/modules/widgets/_widgets/heatmap/Heatmap.vue
  apps/web/src/common/modules/widgets/_widgets/line-chart/LineChart.vue
  apps/web/src/common/modules/widgets/_widgets/number-card/NumberCard.vue
  apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/StackedColumnChart.vue
  apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/StackedHorizontalBarChart.vue
Labels: pass/signedoff

#5399 Refactor/service account create
  apps/web/src/services/asset-inventory/components/ServiceAccountBaseInformationForm.vue
  apps/web/src/services/asset-inventory/pages/ServiceAccountAddPage.vue
Labels: pass/signedoff

#5402 fix(sub-total): apply new subTotal planning
  apps/web/src/common/modules/widgets/_constants/widget-field-constant.ts
  apps/web/src/common/modules/widgets/_helpers/widget-load-helper.ts
  apps/web/src/common/modules/widgets/_widget-fields/custom-table-column-width/WidgetFieldCustomTableColumnWidth.vue
  apps/web/src/common/modules/widgets/_widget-fields/data-field/WidgetFieldDataField.vue
  apps/web/src/common/modules/widgets/_widget-fields/sub-total/WidgetFieldSubTotal.vue
  apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/ClusteredColumnChart.vue
  apps/web/src/common/modules/widgets/_widgets/color-coded-table-heatmap/ColorCodedTableHeatmap.vue
  apps/web/src/common/modules/widgets/_widgets/heatmap/Heatmap.vue
  apps/web/src/common/modules/widgets/_widgets/line-chart/LineChart.vue
  apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/StackedColumnChart.vue
  apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/StackedHorizontalBarChart.vue
  apps/web/src/common/modules/widgets/_widgets/table/Table.vue
  apps/web/src/common/modules/widgets/_widgets/table/_component/WidgetDataTable.vue
Labels: pass/signedoff

#5404 fix(number-format): apply new pivot planning to number format
  apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2.vue
  apps/web/src/common/modules/widgets/_helpers/widget-helper.ts
  apps/web/src/common/modules/widgets/_widget-field-value-manager/constant/default-value-registry.ts
  apps/web/src/common/modules/widgets/_widget-fields/number-format/WidgetFieldNumberFormat.vue
  apps/web/src/common/modules/widgets/_widget-fields/number-format/type.ts
  apps/web/src/common/modules/widgets/_widget-fields/sub-total/WidgetFieldSubTotal.vue
  apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/ClusteredColumnChart.vue
  apps/web/src/common/modules/widgets/_widgets/color-coded-table-heatmap/ColorCodedTableHeatmap.vue
  apps/web/src/common/modules/widgets/_widgets/gauge/Gauge.vue
  apps/web/src/common/modules/widgets/_widgets/line-chart/LineChart.vue
  apps/web/src/common/modules/widgets/_widgets/number-card/NumberCard.vue
  apps/web/src/common/modules/widgets/_widgets/pie-chart/PieChart.vue
  apps/web/src/common/modules/widgets/_widgets/sankey-chart/SankeyChart.vue
  apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/StackedColumnChart.vue
  apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/StackedHorizontalBarChart.vue
  apps/web/src/common/modules/widgets/_widgets/table/_component/WidgetDataTable.vue
  apps/web/src/common/modules/widgets/_widgets/treemap/Treemap.vue
Labels: pass/signedoff

#5407 feat: apply empty data at user select dropdown
  apps/web/src/common/modules/user/UserSelectDropdown.vue
Labels: pass/signedoff

#5405 chore: fix minor in sankey & apply reference label to charts
  apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/ClusteredColumnChart.vue
  apps/web/src/common/modules/widgets/_widgets/color-coded-table-heatmap/ColorCodedTableHeatmap.vue
  apps/web/src/common/modules/widgets/_widgets/heatmap/Heatmap.vue
  apps/web/src/common/modules/widgets/_widgets/line-chart/LineChart.vue
  apps/web/src/common/modules/widgets/_widgets/sankey-chart/SankeyChart.vue
  apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/StackedColumnChart.vue
  apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/StackedHorizontalBarChart.vue
Labels: pass/signedoff

#5408 feat: apply drag at escalation policy rule card
  apps/web/src/services/alert-manager/components/ServiceDetailTabsSettingsEscalationPolicyForm.vue
Labels: pass/signedoff

#5409 fix: apply reference field name to tale widget
  apps/web/src/common/modules/widgets/_widgets/table/Table.vue
  apps/web/src/common/modules/widgets/_widgets/table/_component/WidgetDataTable.vue
Labels: pass/signedoff

#5410 fix: apply reference label to sankey
  apps/web/src/common/modules/widgets/_components/WidgetFormDataSourcePopover.vue
  apps/web/src/common/modules/widgets/_widgets/sankey-chart/SankeyChart.vue
  packages/mirinae/src/foundation/icons/icon-assets/ic_db-additional-labels.svg
  packages/mirinae/src/foundation/icons/icon-assets/ic_db-dimensions.svg
  packages/mirinae/src/foundation/icons/icon-assets/ic_db-pivot-table.svg
  packages/mirinae/src/foundation/icons/icon-assets/ic_db-value-mapping.svg
  packages/mirinae/src/foundation/icons/p-icons/ic_db-additional-labels.js
  packages/mirinae/src/foundation/icons/p-icons/ic_db-dimensions.js
  packages/mirinae/src/foundation/icons/p-icons/ic_db-pivot-table.js
  packages/mirinae/src/foundation/icons/p-icons/ic_db-value-mapping.js
  packages/mirinae/src/foundation/icons/p-icons/index.js
Labels: pass/signedoff

#5411 chore: fix groupBy field bug
  apps/web/src/common/modules/widgets/_widget-field-value-manager/constant/default-value-registry.ts
Labels: pass/signedoff

#5413 fix: fix gauge data format
  apps/web/src/common/modules/widgets/_widgets/gauge/Gauge.vue
Labels: pass/signedoff

#5416 chore: minor style issue
  apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardAddForm.vue
  apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformFormWrapper.vue
Labels: pass/signedoff

#5417 chore: set proper code
  apps/web/src/common/modules/widgets/_widgets/gauge/Gauge.vue
  apps/web/src/common/modules/widgets/_widgets/number-card/NumberCard.vue
Labels: pass/signedoff

#5418 fix(value-mapping): apply changed value-mapping schema
  apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformValueMapping.vue
  apps/web/src/common/modules/widgets/_constants/data-table-constant.ts
  apps/web/src/common/modules/widgets/types/widget-model.ts
Labels: pass/signedoff

#5419 chore: do not show 0 on series label
  apps/web/src/common/modules/widgets/_widgets/line-chart/LineChart.vue
  apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/StackedColumnChart.vue
  apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/StackedHorizontalBarChart.vue
Labels: pass/signedoff

#5423 chore: add missing transform operator to dashboard-share code
  apps/web/src/services/dashboards/helpers/dashboard-share-helper.ts
Labels: pass/signedoff

#5415 chore: Add translation - from [English] to [Korean/Japanese]
  packages/language-pack/en.json
  packages/language-pack/ja.json
  packages/language-pack/ko.json
Labels: pass/signedoff

#5424 Feat: apply qa issue
  apps/web/src/services/iam/components/UserGroupChannelSetInputForm.vue
  apps/web/src/services/iam/components/UserGroupDeleteDoubleCheckModal.vue
  apps/web/src/services/iam/components/UserGroupManagementAddUsersModal.vue
  apps/web/src/services/iam/components/UserGroupManagementTabNotificationChannel.vue
  apps/web/src/services/iam/components/UserGroupManagementTabUsers.vue
  apps/web/src/services/iam/components/UserGroupManagementTable.vue
  apps/web/src/services/iam/components/UserPerGroupRemoveDoubleCheckModal.vue
  apps/web/src/services/iam/composables/user-data-helper.ts
  apps/web/src/services/iam/constants/user-group-constant.ts
  apps/web/src/services/iam/pages/UserGroupMainPage.vue
  apps/web/src/services/iam/store/user-group-page-store.ts
Labels: pass/signedoff

#5426 fix: fix widget clone
  apps/web/src/services/dashboards/components/dashboard-detail/DashboardWidgetContainerV2.vue
  apps/web/src/services/dashboards/helpers/dashboard-share-helper.ts
Labels: pass/signedoff

#5428 fix(widget): improve query-key with referenced dataTable map & apply refetching scenario & solve bugs
  apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformPivotForm.vue
  apps/web/src/common/modules/widgets/_components/WidgetFormOverlayPreviewTable.vue
  apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2.vue
  apps/web/src/common/modules/widgets/_helpers/global-variable-helper.ts
  apps/web/src/common/modules/widgets/_helpers/widget-data-table-helper.ts
  apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/ClusteredColumnChart.vue
  apps/web/src/common/modules/widgets/_widgets/color-coded-heatmap/ColorCodedHeatmap.vue
  apps/web/src/common/modules/widgets/_widgets/color-coded-table-heatmap/ColorCodedTableHeatmap.vue
  apps/web/src/common/modules/widgets/_widgets/gauge/Gauge.vue
  apps/web/src/common/modules/widgets/_widgets/geo-map/GeoMap.vue
  apps/web/src/common/modules/widgets/_widgets/heatmap/Heatmap.vue
  apps/web/src/common/modules/widgets/_widgets/line-chart/LineChart.vue
  apps/web/src/common/modules/widgets/_widgets/number-card/NumberCard.vue
  apps/web/src/common/modules/widgets/_widgets/pie-chart/PieChart.vue
  apps/web/src/common/modules/widgets/_widgets/sankey-chart/SankeyChart.vue
  apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/StackedColumnChart.vue
  apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/StackedHorizontalBarChart.vue
  apps/web/src/common/modules/widgets/_widgets/table/Table.vue
  apps/web/src/common/modules/widgets/_widgets/table/_component/WidgetDataTable.vue
  apps/web/src/common/modules/widgets/_widgets/treemap/Treemap.vue
  apps/web/src/common/modules/widgets/types/widget-display-type.ts
  apps/web/src/services/dashboards/components/dashboard-detail/DashboardWidgetContainerV2.vue
Labels: pass/signedoff

#5429 chore(widget): add defensive code
  apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/ClusteredColumnChart.vue
  apps/web/src/common/modules/widgets/_widgets/color-coded-table-heatmap/ColorCodedTableHeatmap.vue
  apps/web/src/common/modules/widgets/_widgets/heatmap/Heatmap.vue
  apps/web/src/common/modules/widgets/_widgets/line-chart/LineChart.vue
  apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/StackedColumnChart.vue
  apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/StackedHorizontalBarChart.vue
Labels: pass/signedoff

#5430 fix(dashboard-widget): update missing UI
  apps/web/src/common/modules/widgets/_components/WidgetFormOverlayPreviewTable.vue
  apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2WidgetForm.vue
  apps/web/src/common/modules/widgets/_widget-fields/date-range/WidgetFieldDateRange.vue
Labels: pass/signedoff

#5432 fix(pivot): allowed pivot even if there is only one label field case
  apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformPivotForm.vue
  apps/web/src/common/modules/widgets/_widget-field-value-manager/constant/default-value-registry.ts
  apps/web/src/common/modules/widgets/_widget-field-value-manager/constant/validator-registry.ts
  apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/widget-config.ts
  apps/web/src/common/modules/widgets/_widgets/color-coded-heatmap/widget-config.ts
  apps/web/src/common/modules/widgets/_widgets/heatmap/widget-config.ts
  apps/web/src/common/modules/widgets/_widgets/line-chart/widget-config.ts
  apps/web/src/common/modules/widgets/_widgets/pie-chart/widget-config.ts
  apps/web/src/common/modules/widgets/_widgets/stacked-area-chart/widget-config.ts
  apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/widget-config.ts
Labels: pass/signedoff

#5435 refactor(storybook): update config exports and tailwind setup
  apps/storybook/.eslintrc.js
  apps/storybook/tailwind.config.js
Labels: pass/signedoff

#5436 fix(dashboard): solve QAs (data-source-popover, color-coded-heatmap)
  apps/web/src/common/modules/widgets/_components/WidgetFormDataSourcePopover.vue
  apps/web/src/common/modules/widgets/_widget-field-value-manager/constant/validator-registry.ts
  apps/web/src/common/modules/widgets/_widget-field-value-manager/index.ts
  apps/web/src/common/modules/widgets/_widget-fields/format-rules/WidgetFieldFormatRules.vue
  apps/web/src/common/modules/widgets/_widget-fields/format-rules/type.ts
  apps/web/src/common/modules/widgets/_widgets/color-coded-heatmap/widget-config.ts
Labels: pass/signedoff

#5437 chore(dashboard): apply custom design (select-card)
  apps/web/src/common/modules/widgets/_components/WidgetFormDataSourcePopover.vue
Labels: pass/signedoff

#5439 fix: added event occurrence logic when clicking user in the workspace list
  apps/web/src/services/iam/components/UserManagementAddModal.vue
  apps/web/src/services/iam/components/UserManagementAddUser.vue
Labels: pass/signedoff

#5440 fix: added event occurrence logic when clicking user in the workspace list
  apps/web/src/services/iam/components/UserManagementAddModal.vue
  apps/web/src/services/iam/components/UserManagementAddUser.vue
Labels: pass/signedoff

#5441 fix(dashboard): solve dashboard QAs (pivot, number-card, table)
  apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2WidgetForm.vue
  apps/web/src/common/modules/widgets/_constants/widget-constant.ts
  apps/web/src/common/modules/widgets/_widget-field-value-manager/constant/default-value-registry.ts
  apps/web/src/common/modules/widgets/_widgets/number-card/NumberCard.vue
  apps/web/src/common/modules/widgets/_widgets/table/_component/WidgetDataTable.vue
Labels: pass/signedoff

#5434 Feat: apply qa issue
  apps/web/src/services/iam/components/UserGroupChannelSetModal.vue
  apps/web/src/services/iam/components/UserGroupDeleteDoubleCheckModal.vue
  apps/web/src/services/iam/components/UserGroupManagementTable.vue
  apps/web/src/services/iam/components/UserManagementStatusModal.vue
  apps/web/src/store/reference/service-reference-store.ts
Labels: pass/signedoff

#5447 fix(dashboard): solve dashboard bugs
  apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformPivotForm.vue
  apps/web/src/common/modules/widgets/_components/WidgetFormOverlayPreviewTable.vue
  apps/web/src/common/modules/widgets/_composables/use-widget-date-range.ts
  apps/web/src/common/modules/widgets/_widget-fields/header/WidgetHeaderField.vue
  apps/web/src/common/modules/widgets/_widgets/table/_component/WidgetDataTable.vue
Labels: pass/signedoff

#5448 fix(editor-content-transformer): update editor content transformer and notice popup item to update only changed
  apps/web/src/common/composables/editor-content-transformer/index.ts
  apps/web/src/common/modules/popup/notice/modules/NoticePopupItem.vue
  apps/web/src/services/info/components/NoticeDetail.vue
  apps/web/src/services/info/components/NoticeForm.vue
Labels: pass/signedoff, fail/signedoff

#5450 feat: enhance CloudService models with improved handling
  apps/web/src/lib/variable-models/_base/resource-variable-model.ts
  apps/web/src/lib/variable-models/managed-model/resource-model/cloud-service-variable-model.ts
  apps/web/src/services/ops-flow/components/BoardLSB.vue
  apps/web/src/services/ops-flow/task-fields-form/field-templates/AssetTaskField.vue
  packages/core-lib/src/query/index.ts
  packages/language-pack/en.json
  packages/language-pack/ko.json
Labels: pass/signedoff

#5452 fix(notice-detail-store): prevent duplicate requests while loading data
  apps/web/src/common/modules/navigations/top-bar/modules/TopBarSuggestionList.vue
  apps/web/src/lib/file-manager/index.ts
  apps/web/src/services/info/stores/notice-detail-store.ts
Labels: pass/signedoff

#5458 Refactor: changing resizer line to fatter when it hoverd
  packages/mirinae/src/layouts/vertical-layout/PVerticalLayout.vue
Labels: pass/signedoff

#5459 Feature/mypage upd
  apps/web/src/common/components/schedule-setting-form/ScheduleSettingForm.vue
  apps/web/src/services/iam/components/UserAssignToGroupModal.vue
  apps/web/src/services/iam/components/UserGroupManagementAddUsersModal.vue
  apps/web/src/services/iam/components/UserManagementStatusModal.vue
Labels: pass/signedoff

#5460 feat: self qa issue & escalation-policy-reference-store update
  apps/web/src/services/iam/components/UserGroupDeleteDoubleCheckModal.vue
  apps/web/src/services/iam/components/UserManagementStatusModal.vue
  apps/web/src/store/reference/escalation-policy-reference-store.ts
Labels: pass/signedoff

#5464 fix: fixed time display bug
  apps/web/src/services/alert-manager/components/ServiceDetailTabsNotificationsDetailTabs.vue
Labels: pass/signedoff

#5463 fix: handle optional chaining for lsbVisible in OpsFlowContainer.vue
  apps/web/src/services/ops-flow/OpsFlowContainer.vue
  apps/web/tsconfig.json
Labels: pass/signedoff

#5473 Feat: update AlertManager API-V2 at myPage notification & apply minor qa issue
  apps/web/src/common/modules/user/UserSelectDropdown.vue
  apps/web/src/schema/alert-manager/user-channel/api-verbs/update.ts
  apps/web/src/schema/alert-manager/user-channel/type.ts
  apps/web/src/services/iam/components/UserManagementTab.vue
  apps/web/src/services/my-page/components/NotificationAddForm.vue
  apps/web/src/services/my-page/components/NotificationAddFormData.vue
  apps/web/src/services/my-page/components/NotificationAddSchedule.vue
  apps/web/src/services/my-page/components/NotificationChannelItem.vue
  apps/web/src/services/my-page/components/NotificationChannelItemData.vue
  apps/web/src/services/my-page/components/NotificationChannelItemLevel.vue
  apps/web/src/services/my-page/components/NotificationChannelItemName.vue
  apps/web/src/services/my-page/components/NotificationChannelItemSchedule.vue
  apps/web/src/services/my-page/components/NotificationChannelItemTopic.vue
  apps/web/src/services/my-page/components/NotificationChannelList.vue
  apps/web/src/services/my-page/composables/notification-item.ts
  apps/web/src/services/my-page/types/notification-channel-item-type.ts
Labels: pass/signedoff

#5476 feat: apply notification icon at escalation policy channel dropdown
  apps/web/src/services/alert-manager/components/ServiceDetailTabsSettingsEscalationPolicyFormChannelDropdown.vue
Labels: pass/signedoff

#5475 Feat: apply qa issue
  apps/web/src/lib/site-initializer/api-client.ts
  apps/web/src/services/iam/components/UserAssignToGroupModal.vue
  apps/web/src/services/iam/components/UserGroupManagementAddUsersModal.vue
Labels: pass/signedoff

#5478 fix: fixed new user route bug
  apps/web/src/schema/alert-manager/alert/constants.ts
  apps/web/src/services/alert-manager/components/AlertDetailTabsTimeline.vue
  apps/web/src/services/landing/components/workspace-landing/landing-group-workspaces/LandingWorkspaceBoard.vue
Labels: pass/signedoff

#5480 feat: fixed new user route bug
  apps/web/src/schema/alert-manager/alert/constants.ts
  apps/web/src/services/alert-manager/components/AlertDetailTabsTimeline.vue
  apps/web/src/services/landing/components/workspace-landing/landing-group-workspaces/LandingWorkspaceBoard.vue
Labels: pass/signedoff

#5479 Revert "fix: fixed new user route bug"
  apps/web/src/schema/alert-manager/alert/constants.ts
  apps/web/src/services/alert-manager/components/AlertDetailTabsTimeline.vue
  apps/web/src/services/landing/components/workspace-landing/landing-group-workspaces/LandingWorkspaceBoard.vue
Labels: fail/signedoff

#5482 fix: fixed gnb bug (cost explorer landing item)
  apps/web/src/common/modules/navigations/gnb/GNBNavigationRail.vue
  apps/web/src/schema/alert-manager/alert/constants.ts
  apps/web/src/services/alert-manager/components/AlertDetailTabsTimeline.vue
  apps/web/src/services/landing/components/workspace-landing/landing-group-workspaces/LandingWorkspaceBoard.vue
Labels: pass/signedoff

#5483 Feat: apply qa issue (#5481)
  apps/web/src/services/iam/components/UserGroupDeleteDoubleCheckModal.vue
  apps/web/src/services/iam/components/UserGroupManagementTabNotificationChannel.vue
  apps/web/src/services/iam/components/UserManagementStatusModal.vue
  apps/web/src/services/my-page/components/NotificationChannelItemSchedule.vue
Labels: pass/signedoff

#5490 fix(console): refactor source code with security vulnerability
  apps/web/playwright.config.ts
  apps/web/src/common/components/editor/extensions/image/helper.ts
  apps/web/src/common/modules/project/ProjectSelectDropdown.vue
  apps/web/src/common/modules/widgets/_helpers/__tests__/widget-chart-data-helper.test.ts
  apps/web/src/common/modules/widgets/_helpers/widget-data-table-helper.ts
  apps/web/src/lib/random-id-generator.ts
  apps/web/src/services/asset-inventory-v1/components/MetricExplorerHeader.vue
  apps/web/src/services/dashboards/widgets/_helpers/__tests__/widget-chart-data-helper.test.ts
  apps/web/src/services/iam/helpers/generate-helper.ts
  apps/web/src/services/iam/helpers/user-management-form-validations.ts
  apps/web/tests/asset-inventory/collector/collector-create/create-collector-case1.spec.ts
  apps/web/tests/asset-inventory/collector/collector-details/edit-collector.spec.ts
  apps/web/tests/dashboards/view-dashboard/variables/check-updated-variables.spec.ts
Labels: pass/signedoff

#5491 fix(console): refactor lottie.js(app/web) with security vulnerability
  apps/web/public/lottie.js
Labels: pass/signedoff, fail/signedoff

#5493 ci: add pr random reviewer workflow
  .github/workflows/pull_request_random_reviewer_assignment.yaml
Labels: pass/signedoff

#5495 fix(text-input): add `skipMaskToggleTabIndex` props and apply
  apps/web/src/services/auth/authenticator/local/template/ID_PW.vue
  packages/mirinae/src/controls/input/text-input/PTextInput.stories.ts
  packages/mirinae/src/controls/input/text-input/PTextInput.vue
  packages/mirinae/src/controls/input/text-input/story-helper.ts
Labels: pass/signedoff

#5494 ci: move environment variables into job definition for clarity
  .github/workflows/pull_request_random_reviewer_assignment.yaml
Labels: pass/signedoff

#5497 ci: remove 'reopened' event from pull request reviewer assignment workflow
  .github/workflows/pull_request_random_reviewer_assignment.yaml
Labels: pass/signedoff

#5498 ci: remove 'reopened' event from pull request reviewer assignment workflow
  .github/workflows/pull_request_random_reviewer_assignment.yaml
Labels: pass/signedoff

#5499 chore: remove unnecessary whitespace in workflow file for test ci
  .github/workflows/pull_request_random_reviewer_assignment.yaml
Labels: pass/signedoff

#5501 chore: solve biased random number issue
  apps/web/src/services/iam/helpers/generate-helper.ts
Labels: pass/signedoff

#5503 chore(Dockerfile): apply non-root user setting
  apps/web/Dockerfile
Labels: pass/signedoff

#5484 feat: fix bug of badge in double check table modal
  apps/web/src/services/iam/components/UserGroupDeleteDoubleCheckModal.vue
  apps/web/src/services/iam/components/UserManagementStatusModal.vue
Labels: pass/signedoff

#5504 chore(Dockerfile): apply non-root user setting (change user switching)
  apps/web/Dockerfile
Labels: pass/signedoff

#5500 chore: add newline at the end of pull_request_random_reviewer_assignment.yaml for ci test
  .github/workflows/pull_request_random_reviewer_assignment.yaml
  .github/workflows/pull_request_review.yaml
Labels: pass/signedoff

#5505 ci: test PR for random pick reviewer
  .github/workflows/pull_request_random_reviewer_assignment.yaml
Labels: pass/signedoff

#5506 ci: fix status of random reviewer picker
  .github/workflows/pull_request_random_reviewer_assignment.yaml
Labels: pass/signedoff

#5508 chore: add newline at the end of pull_request_random_reviewer_assignment for test
  .github/workflows/pull_request_random_reviewer_assignment.yaml
Labels: pass/signedoff

#5509 fix: update status check for adding reviewers in pull_request_random_reviewer_assignment.yaml
  .github/workflows/pull_request_random_reviewer_assignment.yaml
Labels: pass/signedoff

#5510 fix: response status check for reviewer assignment workflow
  .github/workflows/pull_request_random_reviewer_assignment.yaml
Labels: pass/signedoff

#5511 ci: improve error handling in random reviewer assignment workflow
  .github/workflows/pull_request_random_reviewer_assignment.yaml
Labels: pass/signedoff

#5512 ci: fix to use pr number for adding label
  .github/workflows/pull_request_random_reviewer_assignment.yaml
Labels: pass/signedoff

#5515 feat: apply hide spin button at text-input
  packages/mirinae/src/controls/input/text-input/PTextInput.stories.ts
  packages/mirinae/src/controls/input/text-input/PTextInput.vue
  packages/mirinae/src/controls/input/text-input/story-helper.ts
Labels: pass/signedoff

#5513 chore: add newline at the end of pull_request_random_reviewer_assignment.yaml for ci test
  .github/workflows/pull_request_random_reviewer_assignment.yaml
Labels: pass/signedoff

#5516 ci: update label name in pull_request_random_reviewer_assignment.yaml
  .github/workflows/pull_request_random_reviewer_assignment.yaml
Labels: pass/signedoff

#5517 ci: remove unnecessary newline at the end of pull_request_random_reviewer_assignment.yaml for test
  .github/workflows/pull_request_random_reviewer_assignment.yaml
Labels: pass/signedoff

#5519 docs: update pull request template for clarity on review process
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/pull_request_review_labeler.yaml
Labels: pass/signedoff, pending/review

#5520 ci: add pr reviewer random picker & labeler & label cleaner workflows
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/pull_request_random_reviewer_assignment.yaml
  .github/workflows/pull_request_review.yaml
  .github/workflows/pull_request_review_label_cleanup.yaml
  .github/workflows/pull_request_review_labeler.yaml
Labels: pass/signedoff

#5521 ci: add check for PR author organization membership and assign them
  .github/workflows/pull_request_random_reviewer_assignment.yaml
  .github/workflows/pull_request_review_labeler.yaml
Labels: pass/signedoff

#5522 chore: ci test
  .github/workflows/pull_request_review_labeler.yaml
Labels: pass/signedoff, pending/review

#5525 chore(Dockerfile): solve nginx dir permission issue
  apps/web/Dockerfile
Labels: pass/signedoff, pending/review

#5524 feat: apply mobile responsive design to the event rules page
  apps/web/src/services/alert-manager/components/ServiceDetailTabsSettingsEventRule.vue
  apps/web/src/services/alert-manager/components/ServiceDetailTabsSettingsEventRuleActionForm.vue
  apps/web/src/services/alert-manager/components/ServiceDetailTabsSettingsEventRuleCard.vue
  apps/web/src/services/alert-manager/components/ServiceDetailTabsSettingsEventRuleConditionForm.vue
  apps/web/src/services/alert-manager/components/ServiceDetailTabsSettingsEventRuleFormCard.vue
  apps/web/src/services/alert-manager/components/ServiceDetailTabsSettingsEventRuleSidebar.vue
Labels: pass/signedoff

#5526 chore(dockerfile): solve dockerfile user permission issue
  apps/web/Dockerfile
Labels: pass/signedoff, pending/review

#5528 chore(dockerfile): set log file write permission
  apps/web/Dockerfile
Labels: pass/signedoff, pending/review

#5529 chore(dockerfile): give user local custom permission
  apps/web/Dockerfile
Labels: pass/signedoff, pending/review

#5534 feat: update mobile responsive design of event rules page
  apps/web/src/services/alert-manager/components/ServiceDetailTabsSettingsEventRuleActionAsset.vue
  apps/web/src/services/alert-manager/components/ServiceDetailTabsSettingsEventRuleCard.vue
  apps/web/src/services/alert-manager/components/ServiceDetailTabsSettingsEventRuleSidebar.vue
Labels: pass/signedoff

#5536 fix(reference-store): correct logic for selecting fetcher based on version
  apps/web/src/store/reference/collector-reference-store.ts
  apps/web/src/store/reference/region-reference-store.ts
Labels: pass/signedoff, self_approved/review

#5537 chore: changed css
  apps/web/src/services/alert-manager/components/ServiceDetailTabsSettingsEventRuleActionAsset.vue
Labels: pass/signedoff, self_approved/review

#5539 feat: apply alert manager
  .github/workflows/pull_request_random_reviewer_assignment.yaml
  .github/workflows/pull_request_review_labeler.yaml
  apps/web/src/services/alert-manager/components/ServiceDetailTabsSettingsEventRuleActionAsset.vue
  apps/web/src/store/reference/collector-reference-store.ts
  apps/web/src/store/reference/region-reference-store.ts
Labels: pass/signedoff, self_approved/review

#5540 feat: apply alert manager (#5539)
  .github/workflows/pull_request_random_reviewer_assignment.yaml
  .github/workflows/pull_request_review_labeler.yaml
  apps/web/src/services/alert-manager/components/ServiceDetailTabsSettingsEventRuleActionAsset.vue
  apps/web/src/store/reference/collector-reference-store.ts
  apps/web/src/store/reference/region-reference-store.ts
Labels: pass/signedoff, pending/review, self_approved/review

#5541 chore(user-account-page): remove unnecessary button in external user case
  apps/web/src/services/my-page/pages/UserAccountPage.vue
Labels: pass/signedoff, pending/review, self_approved/review

#5542 build: update nginx conf & set custom nginx user permission
  apps/web/Dockerfile
  apps/web/pkg/proxy.conf
Labels: pass/signedoff, pending/review, self_approved/review

#5543 build(nginx): update nginx image version
  apps/web/Dockerfile
Labels: pass/signedoff, self_approved/review

#5544 build(nginx): remove adduser addgroup
  apps/web/Dockerfile
Labels: pass/signedoff, self_approved/review

#5545 build(dockerfile-nginx): set port 80 without root user permission
  apps/web/Dockerfile
Labels: self_approved/review

#5547 build(nginx): set proper permission to nginx
  apps/web/Dockerfile
  apps/web/pkg/nginx.conf
Labels: pass/signedoff, self_approved/review

#5548 build: rollback Dockerfile to 2.0.dev285
  apps/web/Dockerfile
Labels: self_approved/review

#5549 chore(user-account-page): edit some design changes
  apps/web/src/services/my-page/components/UserAccountBaseInformation.vue
  apps/web/src/services/my-page/components/UserAccountChangePassword.vue
Labels: pass/signedoff, self_approved/review

#5550 feat(security-vulnerability): merge to develop
  apps/web/package.json
  apps/web/pkg/nginx.conf
  apps/web/pkg/proxy.conf
  apps/web/src/services/my-page/components/UserAccountBaseInformation.vue
  apps/web/src/services/my-page/components/UserAccountChangePassword.vue
  package-lock.json
  package.json
Labels: pass/signedoff, self_approved/review

#5554 fix: fixed qa bug
  apps/web/src/services/alert-manager/components/AlertDetailTabsTimeline.vue
  apps/web/src/services/alert-manager/components/AlertDetailTabsTimelineModal.vue
  apps/web/src/services/alert-manager/components/ServiceDetailTabsSettingsEventRuleFormCard.vue
  apps/web/src/services/alert-manager/components/ServiceDetailTabsWebhookDetail.vue
  apps/web/src/services/alert-manager/constants/alert-table-constant.ts
  apps/web/src/services/alert-manager/constants/webhook-table-constant.ts
Labels: pass/signedoff, self_approved/review

#5555 chore: apply sort
  apps/web/src/services/alert-manager/components/ServiceDetailTabsWebhookDetail.vue
Labels: pass/signedoff, self_approved/review

#5523 ci: update pr template and labeling workflow
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/pull_request_random_reviewer_assignment.yaml
  .github/workflows/pull_request_review_labeler.yaml
  .github/workflows/pull_request_review_state_label_cleanup.yaml
  .github/workflows/pull_request_review_state_labeler.yaml
Labels: pass/signedoff, fail/signedoff

#5558 fix(dashboard): solve dashboard QAs
  apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformValueMapping.vue
  apps/web/src/common/modules/widgets/_widget-fields/group-by/WidgetFieldGroupBy.vue
  apps/web/src/common/modules/widgets/_widgets/sankey-chart/widget-config.ts
Labels: pass/signedoff, self_approved/review

#5559 fix(widget): solve widget QAs
  apps/web/src/common/modules/widgets/_components/WidgetFormOverlayPreviewTable.vue
  apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/ClusteredColumnChart.vue
  apps/web/src/common/modules/widgets/_widgets/color-coded-heatmap/ColorCodedHeatmap.vue
  apps/web/src/common/modules/widgets/_widgets/color-coded-table-heatmap/ColorCodedTableHeatmap.vue
  apps/web/src/common/modules/widgets/_widgets/gauge/Gauge.vue
  apps/web/src/common/modules/widgets/_widgets/geo-map/GeoMap.vue
  apps/web/src/common/modules/widgets/_widgets/heatmap/Heatmap.vue
  apps/web/src/common/modules/widgets/_widgets/line-chart/LineChart.vue
  apps/web/src/common/modules/widgets/_widgets/number-card/NumberCard.vue
  apps/web/src/common/modules/widgets/_widgets/pie-chart/PieChart.vue
  apps/web/src/common/modules/widgets/_widgets/sankey-chart/SankeyChart.vue
  apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/StackedColumnChart.vue
  apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/StackedHorizontalBarChart.vue
  apps/web/src/common/modules/widgets/_widgets/table/Table.vue
  apps/web/src/common/modules/widgets/_widgets/treemap/Treemap.vue
Labels: pass/signedoff, self_approved/review

#5561 chore(event-rule): apply 'hasReadWriteAccess' at order button
  apps/web/src/services/alert-manager/components/ServiceDetailTabsSettingsEventRuleSidebar.vue
Labels: pass/signedoff, self_approved/review

#5560 feat(dashboard-middle-qa): merge to develop
  apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformValueMapping.vue
  apps/web/src/common/modules/widgets/_components/WidgetFormOverlayPreviewTable.vue
  apps/web/src/common/modules/widgets/_widget-fields/group-by/WidgetFieldGroupBy.vue
  apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/ClusteredColumnChart.vue
  apps/web/src/common/modules/widgets/_widgets/color-coded-heatmap/ColorCodedHeatmap.vue
  apps/web/src/common/modules/widgets/_widgets/color-coded-table-heatmap/ColorCodedTableHeatmap.vue
  apps/web/src/common/modules/widgets/_widgets/gauge/Gauge.vue
  apps/web/src/common/modules/widgets/_widgets/geo-map/GeoMap.vue
  apps/web/src/common/modules/widgets/_widgets/heatmap/Heatmap.vue
  apps/web/src/common/modules/widgets/_widgets/line-chart/LineChart.vue
  apps/web/src/common/modules/widgets/_widgets/number-card/NumberCard.vue
  apps/web/src/common/modules/widgets/_widgets/pie-chart/PieChart.vue
  apps/web/src/common/modules/widgets/_widgets/sankey-chart/SankeyChart.vue
  apps/web/src/common/modules/widgets/_widgets/sankey-chart/widget-config.ts
  apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/StackedColumnChart.vue
  apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/StackedHorizontalBarChart.vue
  apps/web/src/common/modules/widgets/_widgets/table/Table.vue
  apps/web/src/common/modules/widgets/_widgets/treemap/Treemap.vue
  apps/web/src/services/dashboards/components/dashboard-detail/DashboardVariablesMoreButton.vue
  apps/web/src/services/dashboards/components/dashboard-detail/DashboardVariablesV2.vue
Labels: pass/signedoff, pending/review

#5562 feat(dashboard-qa): merge to master
  apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformValueMapping.vue
  apps/web/src/common/modules/widgets/_components/WidgetFormOverlayPreviewTable.vue
  apps/web/src/common/modules/widgets/_widget-fields/group-by/WidgetFieldGroupBy.vue
  apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/ClusteredColumnChart.vue
  apps/web/src/common/modules/widgets/_widgets/color-coded-heatmap/ColorCodedHeatmap.vue
  apps/web/src/common/modules/widgets/_widgets/color-coded-table-heatmap/ColorCodedTableHeatmap.vue
  apps/web/src/common/modules/widgets/_widgets/gauge/Gauge.vue
  apps/web/src/common/modules/widgets/_widgets/geo-map/GeoMap.vue
  apps/web/src/common/modules/widgets/_widgets/heatmap/Heatmap.vue
  apps/web/src/common/modules/widgets/_widgets/line-chart/LineChart.vue
  apps/web/src/common/modules/widgets/_widgets/number-card/NumberCard.vue
  apps/web/src/common/modules/widgets/_widgets/pie-chart/PieChart.vue
  apps/web/src/common/modules/widgets/_widgets/sankey-chart/SankeyChart.vue
  apps/web/src/common/modules/widgets/_widgets/sankey-chart/widget-config.ts
  apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/StackedColumnChart.vue
  apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/StackedHorizontalBarChart.vue
  apps/web/src/common/modules/widgets/_widgets/table/Table.vue
  apps/web/src/common/modules/widgets/_widgets/treemap/Treemap.vue
  apps/web/src/services/dashboards/components/dashboard-detail/DashboardVariablesMoreButton.vue
  apps/web/src/services/dashboards/components/dashboard-detail/DashboardVariablesV2.vue
Labels: pass/signedoff, pending/review

#5563 feat: apply reference store data at service item, alert detail summary
  apps/web/src/services/alert-manager/components/AlertDetailSummary.vue
  apps/web/src/services/alert-manager/components/ServiceList.vue
  apps/web/src/services/alert-manager/components/ServiceListContent.vue
  apps/web/src/services/project-v1/components/ProjectAlertSettingsEscalationPolicyChangeModal.vue
Labels: pass/signedoff, self_approved/review

#5565 chore(reset-password): apply new update password api to reset-password page
  apps/web/src/schema/identity/user-profile/api-verbs/update-password.ts
  apps/web/src/services/auth/pages/PasswordPage.vue
  apps/web/src/services/my-page/components/UserAccountChangePassword.vue
Labels: pass/signedoff, pending/review

#5564 feat: apply escalation policy link
  apps/web/src/services/alert-manager/components/AlertDetailSummary.vue
  apps/web/src/services/alert-manager/components/ServiceDetailTabsSettings.vue
Labels: pass/signedoff, self_approved/review

#5566 feat: apply master to develop
  apps/web/package.json
  apps/web/src/schema/identity/user-profile/api-verbs/update-password.ts
  apps/web/src/services/alert-manager/components/AlertDetailSummary.vue
  apps/web/src/services/alert-manager/components/ServiceDetailTabsSettings.vue
  apps/web/src/services/alert-manager/components/ServiceDetailTabsSettingsEventRuleSidebar.vue
  apps/web/src/services/alert-manager/components/ServiceList.vue
  apps/web/src/services/alert-manager/components/ServiceListContent.vue
  apps/web/src/services/auth/pages/PasswordPage.vue
  apps/web/src/services/my-page/components/UserAccountChangePassword.vue
  apps/web/src/services/project-v1/components/ProjectAlertSettingsEscalationPolicyChangeModal.vue
  package-lock.json
  package.json
Labels: fail/signedoff, self_approved/review

#5569 feat: apply qa issue
  apps/web/src/services/alert-manager/components/ServiceDetailTabsSettingsEscalationPolicy.vue
  apps/web/src/services/alert-manager/constants/escalation-policy-table-constant.ts
  apps/web/src/services/iam/components/UserAssignToGroupModal.vue
Labels: pass/signedoff, pending/review

#5553 Refactor/pcollapsiblepanel logic
  apps/web/src/services/ops-flow/components/BoardTaskDescriptionField.vue
  apps/web/src/services/ops-flow/components/BoardTaskNameField.vue
  packages/mirinae/src/data-display/collapsible/collapsible-list/PCollapsibleList.vue
  packages/mirinae/src/data-display/collapsible/collapsible-list/type.ts
  packages/mirinae/src/data-display/collapsible/collapsible-panel/PCollapsiblePanel.mdx
  packages/mirinae/src/data-display/collapsible/collapsible-panel/PCollapsiblePanel.stories.ts
  packages/mirinae/src/data-display/collapsible/collapsible-panel/PCollapsiblePanel.vue
  packages/mirinae/src/data-display/collapsible/collapsible-panel/composables/use-text-clamper.ts
  packages/mirinae/src/data-display/collapsible/collapsible-panel/story-helper.ts
Labels: pass/signedoff, pending/review

#5573 fix(cost-analysis): add project-group filter
  apps/web/src/services/cost-explorer/constants/cost-explorer-constant.ts
Labels: pass/signedoff, self_approved/review

#5574 Refactor: changing resizer line to fatter when it hoverd (#5458)
  packages/mirinae/src/layouts/vertical-layout/PVerticalLayout.vue
Labels: pass/signedoff, self_approved/review

#5575 fix: reflect the latest changes in composable to the queryInput
  packages/mirinae/src/controls/input/query-input/PQueryInput.vue
Labels: pass/signedoff, approved/review

#5576 fix: reflect the latest changes in composable to the queryInput
  packages/mirinae/src/controls/input/query-input/PQueryInput.vue
Labels: fail/signedoff, self_approved/review

#5577 feat(project-group-filter): apply project-group filter to metric-explorer/cost-analysis/dashboard
  apps/web/src/common/composables/data-source/use-cost-data-source-filter-menu-items.ts
  apps/web/src/services/asset-inventory-v1/components/MetricExplorerGroupBy.vue
  apps/web/src/services/cost-explorer/constants/cost-explorer-constant.ts
  apps/web/src/services/cost-explorer/constants/managed-cost-analysis-query-sets.ts
  apps/web/src/services/dashboards/components/dashboard-detail/DashboardVariablesV2.vue
  apps/web/src/services/dashboards/constants/dashboard-vars-schema-preset.ts
Labels: pass/signedoff, pending/review, self_approved/review

#5581 ci: fix random reviewer assignment workflow job execution condition
  .github/workflows/pull_request_random_reviewer_assignment.yaml
Labels: pass/signedoff, pending/review

#5582 fix: fixed convert function bug
  apps/web/src/common/components/forms/pairs-input-group/PairsInputGroup.vue
Labels: pass/signedoff, self_approved/review

#5586 fix(project-group-filter): apply project group filter (data-table, metric-explorer)
  apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardAddForm.vue
  apps/web/src/services/asset-inventory-v1/components/MetricExplorerFiltersPopper.vue
  apps/web/src/services/asset-inventory-v1/components/MetricExplorerGroupBy.vue
  apps/web/src/services/asset-inventory-v1/constants/asset-analysis-constant.ts
  apps/web/src/services/cost-explorer/constants/cost-explorer-constant.ts
  apps/web/src/services/dashboards/constants/dashboard-vars-schema-preset.ts
Labels: pass/signedoff, self_approved/review

#5587 feat(project-group): merge to develop
  apps/web/src/common/composables/data-source/use-cost-data-source-filter-menu-items.ts
  apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardAddForm.vue
  apps/web/src/services/asset-inventory-v1/components/MetricExplorerFiltersPopper.vue
  apps/web/src/services/asset-inventory-v1/constants/asset-analysis-constant.ts
  apps/web/src/services/cost-explorer/constants/cost-explorer-constant.ts
  apps/web/src/services/cost-explorer/constants/managed-cost-analysis-query-sets.ts
  apps/web/src/services/dashboards/components/dashboard-detail/DashboardVariablesV2.vue
  apps/web/src/services/dashboards/constants/dashboard-vars-schema-preset.ts
Labels: pass/signedoff, self_approved/review

#5584 feat: apply qa issue
  apps/web/src/common/components/schedule-setting-form/ScheduleSettingForm.vue
  apps/web/src/services/iam/components/UserAssignToGroupModal.vue
  apps/web/src/services/iam/components/UserGroupManagementAddUsersModal.vue
  apps/web/src/services/iam/components/UserGroupManagementEditModal.vue
Labels: pass/signedoff, self_approved/review

#5588 refactor: add component props type
  packages/mirinae/src/data-display/collapsible/collapsible-panel/PCollapsiblePanel.vue
  packages/mirinae/src/data-display/collapsible/collapsible-panel/type.ts
Labels: pass/signedoff, self_approved/review

#5592 chore(admin-route): solve wrong inventory-v2 route bug
  apps/web/src/router/admin-routes.ts
  apps/web/src/services/dashboards/helpers/dashboard-global-variables-helper.ts
Labels: pass/signedoff, self_approved/review

#5593 fix: fixed qa bug
  apps/web/src/services/alert-manager/components/AlertsManagementTable.vue
  apps/web/src/services/alert-manager/components/ServiceDetailTabsSettingsContainer.vue
Labels: pass/signedoff, self_approved/review

#5594 chore(dashboard-variable): add project group variable
  apps/web/src/services/dashboards/constants/dashboard-global-variable-preset.ts
  apps/web/src/services/dashboards/helpers/dashboard-global-variables-helper.ts
Labels: pass/signedoff, self_approved/review

#5595 feat: apply qa issue
  apps/web/src/common/pages/AlertPublicDetailPage.vue
Labels: pass/signedoff, self_approved/review

#5596 chore: apply immediate at watch
  apps/web/src/services/alert-manager/components/ServiceDetailTabsSettingsContainer.vue
Labels: pass/signedoff, self_approved/review

#5597 feat: apply minor qa issue
  apps/web/src/common/pages/AlertPublicDetailPage.vue
  apps/web/src/services/alert-manager/components/AlertsManagementTable.vue
  apps/web/src/services/alert-manager/components/ServiceDetailTabsSettingsContainer.vue
Labels: pass/signedoff, self_approved/review

#5598 merge to master (alert manager v2)
  apps/web/src/common/pages/AlertPublicDetailPage.vue
  apps/web/src/services/alert-manager/components/AlertsManagementTable.vue
  apps/web/src/services/alert-manager/components/ServiceDetailTabsSettingsContainer.vue
Labels: fail/signedoff, self_approved/review

#5600 chore(data-table): apply design detail to dropdown (transform-data-table)
  apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformPivotForm.vue
  apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformValueMapping.vue
Labels: pass/signedoff, self_approved/review

#5601 chore(reference-store): remove wrong branching code (inventory v2)
  apps/web/src/store/reference/collector-reference-store.ts
  apps/web/src/store/reference/region-reference-store.ts
Labels: pass/signedoff, self_approved/review

#5602 chore(dashboard): apply new sorting policy to dashboard and dashboard-folder
  apps/web/src/store/dashboard/dashboard-store.ts
Labels: pass/signedoff, fail/signedoff, self_approved/review

#5604 chore(dashboard): apply new sorting policy to dashboard and dashboard-folder
  apps/web/src/store/dashboard/dashboard-store.ts
Labels: pass/signedoff, self_approved/review

#5605 chore: version 2.0.dev302
  apps/web/package.json
  package-lock.json
  package.json
Labels: pass/signedoff, pending/review

#5607 chore(data-table): solve data-table project-group filter bug
  apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardAddForm.vue
  apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardFilters.vue
Labels: pass/signedoff, self_approved/review

#5608 fix: fixed bug with missing data in event rule condition edits
  apps/web/src/services/alert-manager/components/ServiceDetailTabsSettingsEventRuleFormCard.vue
Labels: pass/signedoff, self_approved/review
