Repository cloudforet-io/console, pull requests merged in 2025-03, with the labels that each got.

#5668 feat(use-api-query-key): refactor use-api-query-key composable & create api-doc cli
  apps/web/cli/api-doc-gen.js
  apps/web/package.json
  apps/web/src/api-clients/_common/composables/use-api-query-key.ts
  apps/web/src/api-clients/_common/composables/use-query-key.ts
  apps/web/src/api-clients/_common/constants/api-doc.ts
  apps/web/src/api-clients/_common/types/query-key-type.ts
  apps/web/src/api-clients/dashboard/private-dashboard/composables/use-private-dashboard-api.ts
  apps/web/src/api-clients/dashboard/private-data-table/composables/use-private-data-table-api.ts
  apps/web/src/api-clients/dashboard/private-data-table/schema/api-verbs/add.ts
  apps/web/src/api-clients/dashboard/private-data-table/schema/api-verbs/delete.ts
  apps/web/src/api-clients/dashboard/private-data-table/schema/api-verbs/get.ts
  apps/web/src/api-clients/dashboard/private-data-table/schema/api-verbs/list.ts
  apps/web/src/api-clients/dashboard/private-data-table/schema/api-verbs/load.ts
  apps/web/src/api-clients/dashboard/private-data-table/schema/api-verbs/transform.ts
  apps/web/src/api-clients/dashboard/private-data-table/schema/api-verbs/update.ts
  apps/web/src/api-clients/dashboard/private-folder/composables/use-private-folder-api.ts
  apps/web/src/api-clients/dashboard/private-widget/composables/use-private-widget-api.ts
  apps/web/src/api-clients/dashboard/public-dashboard/composables/use-public-dashboard-api.ts
  apps/web/src/api-clients/dashboard/public-data-table/composables/use-public-data-table-api.ts
  apps/web/src/api-clients/dashboard/public-folder/composables/use-public-folder-api.ts
  apps/web/src/api-clients/dashboard/public-widget/composables/use-public-widget-api.ts
  apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardAddContents.vue
  apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformContents.vue
  apps/web/src/common/modules/widgets/_components/WidgetFormOverlay.vue
  apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2.vue
  apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2WidgetForm.vue
  apps/web/src/common/modules/widgets/_composables/use-widget-form-query.ts
  apps/web/src/services/dashboards/components/dashboard-detail/DashboardLabelsButton.vue
  apps/web/src/services/dashboards/components/dashboard-detail/DashboardManageVariableImportModal.vue
  apps/web/src/services/dashboards/components/dashboard-detail/DashboardManageVariableOverlay.vue
  apps/web/src/services/dashboards/components/dashboard-detail/DashboardNameEditModal.vue
  apps/web/src/services/dashboards/components/dashboard-detail/DashboardRefreshDropdown.vue
  apps/web/src/services/dashboards/components/dashboard-detail/DashboardReorderSidebar.vue
  apps/web/src/services/dashboards/components/dashboard-detail/DashboardToolsetDateDropdown.vue
  apps/web/src/services/dashboards/components/dashboard-detail/DashboardVariablesFormModal.vue
  apps/web/src/services/dashboards/components/dashboard-detail/DashboardVariablesMoreButton.vue
  apps/web/src/services/dashboards/components/dashboard-detail/DashboardWidgetContainerV2.vue
  apps/web/src/services/dashboards/composables/use-dashboard-detail-query.ts
  apps/web/src/services/dashboards/pages/DashboardDetailPage.vue
Labels: pass/signedoff

#5672 chore(p-dynamic-field): fix minor style (dict field)
  packages/mirinae/src/data-display/dynamic/dynamic-field/templates/dict/index.vue
Labels: pass/signedoff, self_approved/review

#5674 feat(opsflow): fix v1 minor bugs and refactor to use vue query for task apis
  apps/web/src/api-clients/opsflow/_types/task-field-type.ts
  apps/web/src/api-clients/opsflow/task-category/composables/use-task-category-api.ts
  apps/web/src/api-clients/opsflow/task-type/composables/use-task-type-api.ts
  apps/web/src/api-clients/opsflow/task/composables/use-task-api.ts
  apps/web/src/common/components/editor/text-editor-nodes.pcss
  apps/web/src/services/ops-flow/components/BoardTaskNameField.vue
  apps/web/src/services/ops-flow/components/BoardTaskTable.vue
  apps/web/src/services/ops-flow/components/TaskAssignModal.vue
  apps/web/src/services/ops-flow/components/TaskCategoryDeleteModal.vue
  apps/web/src/services/ops-flow/components/TaskContentBaseForm.vue
  apps/web/src/services/ops-flow/components/TaskStatusDeleteModal.vue
  apps/web/src/services/ops-flow/components/TaskStatusDraggableItem.vue
  apps/web/src/services/ops-flow/components/TaskStatusList.vue
  apps/web/src/services/ops-flow/components/TaskStatusSetDefaultModal.vue
  apps/web/src/services/ops-flow/components/TaskTypeDeleteModal.vue
  apps/web/src/services/ops-flow/components/TaskTypeForm.vue
  apps/web/src/services/ops-flow/composables/use-associated-tasks-query.ts
  apps/web/src/services/ops-flow/composables/use-task-api.ts
  apps/web/src/services/ops-flow/composables/use-task-status-field.ts
  apps/web/src/services/ops-flow/composables/use-task-type-field.ts
  apps/web/src/services/ops-flow/constants/task-status-label-constant.ts
  apps/web/src/services/ops-flow/pages/OpsFlowLandingPage.vue
  apps/web/src/services/ops-flow/pages/TaskCreatePage.vue
  apps/web/src/services/ops-flow/pages/TaskDetailPage.vue
  apps/web/src/services/ops-flow/stores/admin/task-category-page-store.ts
  apps/web/src/services/ops-flow/stores/admin/task-management-page-store.ts
  apps/web/src/services/ops-flow/stores/board-page-store.ts
  apps/web/src/services/ops-flow/stores/task-content-form-store.ts
  apps/web/src/services/ops-flow/task-fields-configuration/TaskFieldGenerator.vue
  apps/web/src/services/ops-flow/task-fields-configuration/TaskFieldGeneratorHeader.vue
  apps/web/src/services/ops-flow/task-fields-configuration/TaskFieldsConfiguration.vue
  apps/web/src/services/ops-flow/task-fields-configuration/composables/use-task-field-generator.ts
  apps/web/src/services/ops-flow/task-fields-configuration/composables/use-task-fields-configuration.ts
  apps/web/src/services/ops-flow/task-fields-configuration/options-generator-templates/DropdownOptionsGenerator.vue
  apps/web/src/services/ops-flow/task-fields-configuration/options-generator-templates/ParagraphOptionsGenerator.vue
  apps/web/src/services/ops-flow/task-fields-configuration/options-generator-templates/TextOptionsGenerator.vue
  apps/web/src/services/ops-flow/task-fields-configuration/stores/use-task-field-metadata-store.ts
  apps/web/src/services/ops-flow/task-fields-configuration/types/mutable-task-field-type.ts
  apps/web/src/services/ops-flow/task-fields-configuration/types/options-generator-type.ts
  apps/web/src/services/ops-flow/task-fields-configuration/types/task-field-dropdown-enum-type.ts
  apps/web/src/services/ops-flow/task-fields-configuration/types/task-field-type-metadata-type.ts
  apps/web/src/services/ops-flow/task-fields-form/TaskFieldsForm.vue
  apps/web/src/services/ops-flow/task-fields-form/composables/use-task-field-validation.ts
  apps/web/src/services/ops-flow/task-fields-form/field-templates/AssetTaskField.vue
  apps/web/src/services/ops-flow/task-fields-form/field-templates/DateTaskField.vue
  apps/web/src/services/ops-flow/task-fields-form/field-templates/DropdownTaskField.vue
  apps/web/src/services/ops-flow/task-fields-form/field-templates/LabelsTaskField.vue
  apps/web/src/services/ops-flow/task-fields-form/field-templates/ParagraphTaskField.vue
  apps/web/src/services/ops-flow/task-fields-form/field-templates/ProjectTaskField.vue
  apps/web/src/services/ops-flow/task-fields-form/field-templates/ServiceAccountTaskField.vue
  apps/web/src/services/ops-flow/task-fields-form/field-templates/TextTaskField.vue
  apps/web/src/services/ops-flow/task-fields-form/field-templates/UnknownTaskField.vue
  apps/web/src/services/ops-flow/task-fields-form/field-templates/UserTaskField.vue
  apps/web/src/services/ops-flow/task-fields-form/types/task-field-form-type.ts
  packages/mirinae/src/data-display/collapsible/collapsible-panel/composables/use-text-clamper.ts
  packages/mirinae/src/navigation/link/PLink.mdx
  packages/mirinae/src/navigation/link/PLink.stories.ts
  packages/mirinae/src/navigation/link/PLink.vue
  packages/mirinae/src/navigation/link/story-helper.ts
Labels: pass/signedoff, self_approved/review

#5675 fix(opsflow): update task-related API composables to use new useAPIQu…
  apps/web/src/api-clients/cost-analysis/data-source/schema/model.ts
  apps/web/src/api-clients/opsflow/task-category/composables/use-task-category-api.ts
  apps/web/src/api-clients/opsflow/task-type/composables/use-task-type-api.ts
  apps/web/src/api-clients/opsflow/task/composables/use-task-api.ts
  apps/web/src/common/modules/widgets/_helpers/widget-helper.ts
  apps/web/src/common/modules/widgets/_widget-field-value-manager/constant/default-value-registry.ts
Labels: pass/signedoff, self_approved/review

#5676 feat: add spec of `PCard`header color
  packages/mirinae/src/data-display/cards/card/PCard.vue
  packages/mirinae/src/data-display/cards/card/config.ts
Labels: pass/signedoff

#5678 fix(ci): add optional chaining to prevent null user login errors in PR reviewer assignment workflow
  .github/workflows/pull_request_random_reviewer_assignment.yaml
Labels: pass/signedoff, self_approved/review

#5684 chore(widget): solve dependency cycle
  apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardAddContents.vue
  apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardHeaderTitle.vue
  apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformContents.vue
  apps/web/src/common/modules/widgets/_components/WidgetFormOverlay.vue
  apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2.vue
  apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2WidgetForm.vue
  apps/web/src/common/modules/widgets/_helpers/widget-helper.ts
  apps/web/src/common/modules/widgets/_helpers/widget-options-helper.ts
  apps/web/src/common/modules/widgets/_widget-field-value-manager/constant/default-value-registry.ts
Labels: pass/signedoff, self_approved/review

#5685 chore: improve table widget loading state
  apps/web/src/common/modules/widgets/_widgets/table/Table.vue
Labels: pass/signedoff, self_approved/review

#5687 fix(widget-date-range): apply date-range api query policy
  apps/web/src/common/modules/widgets/_composables/use-widget-date-range.ts
Labels: pass/signedoff, self_approved/review

#5691 chore: remove pull request review state labeler workflow
  .github/workflows/pull_request_review_state_labeler.yaml
Labels: pass/signedoff, self_approved/review

#5677 Potential fix for code scanning alert no. 30: Incomplete string escaping or encoding
  apps/web/src/services/asset-inventory/components/CollectorHistoryJobTaskErrorList.vue
Labels: pass/signedoff

#5693 fix: fix to prevent string concatenation in data table footer totals
  apps/web/src/services/cost-explorer/components/CostAnalysisDataTable.vue
Labels: pass/signedoff

#5695 fix(widget): solve widget lazy loading bug
  apps/web/src/services/dashboards/components/dashboard-detail/DashboardWidgetContainerV2.vue
Labels: pass/signedoff, self_approved/review

#5696 fix(workflow): update storybook filter in build command
  .github/workflows/dispatch_storybook_release.yaml
Labels: pass/signedoff, self_approved/review

#5704 chore: changed schema mode name
  apps/web/src/services/alert-manager/v1/components/AlertDashboardAlertStateWidget.vue
  apps/web/src/services/alert-manager/v1/components/AlertDashboardProjectSearchWidgetAlertList.vue
  apps/web/src/services/alert-manager/v1/components/AlertDashboardTop5ProjectActivityWidgetTooltip.vue
  apps/web/src/services/alert-manager/v1/components/AlertDetailResponder.vue
  apps/web/src/services/alert-manager/v1/components/AlertMainAcknowledgeModal.vue
  apps/web/src/services/alert-manager/v1/components/AlertMainDataTableActions.vue
  apps/web/src/services/alert-manager/v1/components/AlertMainResolveModal.vue
  apps/web/src/services/project/v1/components/ProjectSummaryAlertWidget.vue
Labels: pass/signedoff, self_approved/review

#5705 feat: add composables for identity API clients
  apps/web/src/api-clients/identity/domain/composables/use-domain-api.ts
  apps/web/src/api-clients/identity/project-group/composables/use-project-group-api.ts
  apps/web/src/api-clients/identity/project/composables/use-project-api.ts
  apps/web/src/api-clients/identity/provider/composables/use-provider-api.ts
  apps/web/src/api-clients/identity/service-account/composables/use-service-account-api.ts
  apps/web/src/api-clients/identity/token/composables/use-token-api.ts
  apps/web/src/api-clients/identity/trusted-account/composables/use-trusted-account-api.ts
  apps/web/src/api-clients/identity/user-group/composables/use-user-group-api.ts
  apps/web/src/api-clients/identity/user-profile/composables/use-user-profile-api.ts
  packages/mirinae/src/controls/input/text-input/PTextInput.vue
Labels: pass/signedoff, self_approved/review

#5710 feat: change to schema-based
  apps/web/src/api-clients/api-clients-schema.json
  apps/web/src/api-clients/loader.ts
  apps/web/src/api-clients/schema.ts
  apps/web/src/services/alert-manager/configurator.ts
  apps/web/src/services/asset-inventory/configurator.ts
  apps/web/src/services/configurator.ts
  apps/web/src/services/cost-explorer/configurator.ts
  apps/web/src/services/dashboards/configurator.ts
  apps/web/src/services/featureSchema.ts
  apps/web/src/services/featureSchemaManager.ts
  apps/web/src/services/iam/configurator.ts
  apps/web/src/services/ops-flow/configurator.ts
  apps/web/src/services/project/configurator.ts
  apps/web/src/services/service-account/configurator.ts
  apps/web/src/store/config/global-config-setting-store.ts
Labels: pass/signedoff, self_approved/review

#5711 refactor: changed file name and position
  apps/web/src/api-clients/api-client-manager.ts
  apps/web/src/lib/config/global-config/api-client-schema.ts
  apps/web/src/lib/config/global-config/constants.ts
  apps/web/src/lib/config/global-config/feature-schema-manager.ts
  apps/web/src/lib/config/global-config/feature-schema.ts
  apps/web/src/lib/config/global-config/type.ts
  apps/web/src/lib/site-initializer/api-client.ts
  apps/web/src/services/alert-manager/configurator.ts
  apps/web/src/services/asset-inventory/configurator.ts
  apps/web/src/services/configurator.ts
  apps/web/src/services/cost-explorer/configurator.ts
  apps/web/src/services/dashboards/configurator.ts
  apps/web/src/services/featureSchemaManager.ts
  apps/web/src/services/iam/configurator.ts
  apps/web/src/services/ops-flow/configurator.ts
  apps/web/src/services/project/configurator.ts
  apps/web/src/services/service-account/configurator.ts
  apps/web/src/store/reference/escalation-policy-reference-store.ts
  apps/web/src/store/reference/service-reference-store.ts
  apps/web/src/store/reference/webhook-reference-store.ts
Labels: pass/signedoff, self_approved/review

#5712 feat: apply ui based on version
  apps/web/src/api-clients/api-client-manager.ts
  apps/web/src/common/modules/navigations/stores/gnb-store.ts
  apps/web/src/common/modules/navigations/top-bar/modules/top-bar-toolset/TopBarToolset.vue
  apps/web/src/lib/config/composables/use-is-alert-manager-v2-enabled.ts
  apps/web/src/lib/config/global-config/api-client-schema.ts
  apps/web/src/lib/config/global-config/constants.ts
  apps/web/src/lib/config/global-config/feature-schema-manager.ts
  apps/web/src/lib/config/global-config/feature-schema.ts
  apps/web/src/lib/config/global-config/type.ts
  apps/web/src/services/alert-manager/configurator.ts
  apps/web/src/services/asset-inventory/components/CloudServiceDetailTabs.vue
  apps/web/src/services/asset-inventory/configurator.ts
  apps/web/src/services/asset-inventory/stores/cloud-service-detail-page-store.ts
  apps/web/src/services/configurator.ts
  apps/web/src/services/cost-explorer/configurator.ts
  apps/web/src/services/cost-explorer/pages/BudgetDetailPage.vue
  apps/web/src/services/cost-explorer/stores/budget-detail-page-store.ts
  apps/web/src/services/dashboards/configurator.ts
  apps/web/src/services/iam/configurator.ts
  apps/web/src/services/my-page/components/NotificationAddForm.vue
  apps/web/src/services/my-page/components/NotificationAddFormData.vue
  apps/web/src/services/my-page/components/NotificationAddSchedule.vue
  apps/web/src/services/my-page/components/NotificationChannelItem.vue
  apps/web/src/services/my-page/components/NotificationChannelItemData.vue
  apps/web/src/services/my-page/components/NotificationChannelItemName.vue
  apps/web/src/services/my-page/components/NotificationChannelItemSchedule.vue
  apps/web/src/services/my-page/components/NotificationChannelList.vue
  apps/web/src/services/my-page/composables/notification-item.ts
  apps/web/src/services/my-page/stores/my-page-store.ts
  apps/web/src/services/ops-flow/configurator.ts
  apps/web/src/services/project/configurator.ts
  apps/web/src/services/project/v1/components/ProjectDetailTabHeader.vue
  apps/web/src/services/project/v1/pages/ProjectDetailTabPage.vue
  apps/web/src/services/project/v1/pages/ProjectSummaryPage.vue
  apps/web/src/services/project/v1/stores/project-detail-page-store.ts
  apps/web/src/services/service-account/configurator.ts
  apps/web/src/store/display/composables/use-advanced-menu-display.ts
Labels: pass/signedoff, self_approved/review

#5714 feat: hide content of disabled services
  apps/web/src/api-clients/api-client-manager.ts
  apps/web/src/common/composables/contents-accessibility/index.ts
  apps/web/src/common/modules/widgets/_components/WidgetFormDataSourcePopover.vue
  apps/web/src/services/configurator.ts
  apps/web/src/services/dashboards/components/dashboard-detail/DashboardVariablesFormDynamic.vue
  apps/web/src/services/project/v1/components/ProjectDetailTabHeader.vue
  apps/web/src/services/project/v1/components/ProjectSummaryAllSummaryWidget.vue
  apps/web/src/services/project/v1/components/ProjectSummaryAllSummaryWidgetRegionService.vue
  apps/web/src/services/project/v1/components/ProjectSummaryServiceAccountsWidget.vue
  apps/web/src/services/project/v1/pages/ProjectDetailTabPage.vue
  apps/web/src/services/project/v1/pages/ProjectSummaryPage.vue
  apps/web/src/services/workspace-home/components/Summaries.vue
  apps/web/src/store/reference/escalation-policy-reference-store.ts
  apps/web/src/store/reference/webhook-reference-store.ts
Labels: pass/signedoff, self_approved/review

#5715 feat: apply opsFlow tab at cloud service
  apps/web/src/common/modules/navigations/stores/gnb-store.ts
  apps/web/src/lib/config/global-config/feature-schema-manager.ts
  apps/web/src/lib/config/global-config/type.ts
  apps/web/src/lib/site-initializer/api-client.ts
  apps/web/src/services/asset-inventory/components/CloudServiceDetailTabs.vue
  apps/web/src/services/asset-inventory/stores/cloud-service-detail-page-store.ts
  apps/web/src/services/cost-explorer/stores/budget-detail-page-store.ts
  apps/web/src/services/my-page/stores/my-page-store.ts
  apps/web/src/services/project/v1/stores/project-detail-page-store.ts
Labels: pass/signedoff, self_approved/review

#5722 chore: add services config at default.json
  apps/web/public/config/default.json
  apps/web/public/config/development.json.sample
Labels: pass/signedoff, self_approved/review

#5723 feat: modify to allow override of setting data by domain
  apps/web/public/config/default.json
  apps/web/src/api-clients/api-client-manager.ts
  apps/web/src/api-clients/config/public-config/schema/constant.ts
  apps/web/src/lib/site-initializer/api-client.ts
  apps/web/src/lib/site-initializer/index.ts
  apps/web/src/lib/site-initializer/merge-config.ts
  apps/web/src/services/configurator.ts
  apps/web/src/store/display/composables/useAdvancedMenuDisplay.ts
  apps/web/src/store/display/display-store.ts
Labels: pass/signedoff, self_approved/review

#5724 feat: modify to allow override of setting data by domain
  apps/web/public/config/default.json
  apps/web/src/api-clients/api-client-manager.ts
  apps/web/src/api-clients/config/public-config/schema/constant.ts
  apps/web/src/lib/site-initializer/api-client.ts
  apps/web/src/lib/site-initializer/index.ts
  apps/web/src/lib/site-initializer/merge-config.ts
  apps/web/src/services/configurator.ts
  apps/web/src/store/display/composables/useAdvancedMenuDisplay.ts
  apps/web/src/store/display/display-store.ts
Labels: fail/signedoff, self_approved/review

#5726 fix: handle 404 error gracefully by setting default values
  apps/web/src/lib/site-initializer/merge-config.ts
Labels: pass/signedoff, self_approved/review

#5728 Feat: update budget create page with reactivity chart
  apps/web/src/api-clients/cost-analysis/budget/schema/type.ts
  apps/web/src/common/modules/user/UserSelectDropdown.vue
  apps/web/src/services/cost-explorer/components/BudgetCreateManagerSelect.vue
  apps/web/src/services/cost-explorer/components/BudgetCreateScopeSelect.vue
  apps/web/src/services/cost-explorer/components/BudgetCreateStep1.vue
  apps/web/src/services/cost-explorer/components/BudgetCreateStep2.vue
  apps/web/src/services/cost-explorer/components/BudgetCreateStep3.vue
  apps/web/src/services/cost-explorer/components/BudgetDeleteCheckModal.vue
  apps/web/src/services/cost-explorer/pages/BudgetCreatePage.vue
  apps/web/src/services/cost-explorer/pages/BudgetLastThreeMonthCostTrendBarChart.vue
  apps/web/src/services/cost-explorer/stores/budget-create-page-store.ts
Labels: pass/signedoff, self_approved/review
