Repository cloudforet-io/console, pull requests merged in 2025-06, with the labels that each got.

#5905 fix: incorrect policy id in adjustment creation request
  apps/web/src/services/cost-explorer/components/AdvancedSettingsCostReportConfiguration.vue
  apps/web/src/services/cost-explorer/components/AdvancedSettingsSetAdjustmentsOverlay.vue
Labels: pass/signedoff

#5914 feat: feat: load ADJUSTING and DONE items in admin mode & etc
  apps/web/src/common/modules/popup/notice/modules/NoticePopupItem.vue
  apps/web/src/services/cost-explorer/components/AdvancedSettingsAdjustmentsForm.vue
  apps/web/src/services/cost-explorer/components/CostReportReportsTab.vue
  apps/web/src/services/cost-explorer/stores/advanced-settings-page-store.ts
Labels: fail/signedoff

#5915 Hotfix cost report
  apps/web/src/common/modules/popup/notice/modules/NoticePopupItem.vue
  apps/web/src/services/cost-explorer/components/AdvancedSettingsAdjustmentsForm.vue
  apps/web/src/services/cost-explorer/components/CostReportReportsTab.vue
  apps/web/src/services/cost-explorer/stores/advanced-settings-page-store.ts
Labels: fail/signedoff

#5916 fix: handle async timing issue (adjustment) & etc
  apps/web/src/services/cost-explorer/components/AdvancedSettingsAdjustmentsForm.vue
  apps/web/src/services/cost-explorer/components/AdvancedSettingsSetAdjustmentsOverlay.vue
  apps/web/src/services/cost-explorer/stores/advanced-settings-page-store.ts
Labels: pass/signedoff

#5917 Merge develop to master
  apps/web/src/services/cost-explorer/components/AdvancedSettingsAdjustmentsForm.vue
  apps/web/src/services/cost-explorer/components/AdvancedSettingsSetAdjustmentsOverlay.vue
  apps/web/src/services/cost-explorer/stores/advanced-settings-page-store.ts
Labels: fail/signedoff

#5918 fix(release-hofix): create temporarily hotfix workflow
  .github/workflows/dispatch_release_hotfix.yaml
Labels: pass/signedoff

#5921 fix(release-hofix): create temporarily hotfix workflow
  .github/workflows/dispatch_release_hotfix.yaml
Labels: pass/signedoff, self_approved/review

#5924 chore(release-hotfix): apply changed version convention regex
  .github/workflows/dispatch_release_hotfix.yaml
Labels: pass/signedoff, self_approved/review

#5926 fix: set min value from 0 to 1 (adjustment period)
  apps/web/src/services/cost-explorer/components/AdvancedSettingsCostReportConfiguration.vue
  apps/web/src/services/cost-explorer/components/AdvancedSettingsSetAdjustmentsOverlay.vue
Labels: pass/signedoff

#5931 hotfix: delete `is_confirmed` filter from cost report analyze API
  apps/web/src/common/pages/CostReportDetailPage.vue
  apps/web/src/services/cost-explorer/components/CostReportReportsTab.vue
Labels: pass/signedoff

#5932 feat: show all provider in 'Details By Product' section
  apps/web/src/common/pages/CostReportDetailPage.vue
Labels: pass/signedoff

#5934 feat(alert-service): enhance pagination logic in service page
  apps/web/src/services/alert-manager/v2/components/ServiceList.vue
  apps/web/src/services/alert-manager/v2/components/ServiceListContent.vue
  apps/web/src/services/alert-manager/v2/stores/service-list-page-store.ts
Labels: pass/signedoff

#5933 feat: create schema for cost analysis apis
  apps/web/src/api-clients/cost-analysis/cost-query-set/composables/use-cost-query-set-api.ts
  apps/web/src/api-clients/cost-analysis/cost/composables/use-cost-api.ts
  apps/web/src/services/cost-explorer/components/AnomalyDetectionConfigurationTable.vue
  apps/web/src/services/cost-explorer/components/AnomalyDetectionHistoryTable.vue
  apps/web/src/services/cost-explorer/components/CostAnalysisContent.vue
  apps/web/src/services/cost-explorer/components/CostAnalysisHeader.vue
  apps/web/src/services/cost-explorer/composables/queries/use-cost-analysis-query.ts
  apps/web/src/services/cost-explorer/composables/queries/use-cost-query-set-query.ts
  apps/web/src/services/cost-explorer/composables/queries/use-cost-report-config-query.ts
  apps/web/src/services/cost-explorer/pages/AnomalyDetectionConfigurationPage.vue
  apps/web/src/services/cost-explorer/pages/CostAnalysisPage.vue
  apps/web/src/services/cost-explorer/pages/admin/AdminCostAnalysisPage.vue
  apps/web/src/services/cost-explorer/routes/admin/routes.ts
Labels: pass/signedoff

#5930 feat: apply vue-query to notification protocol api
  apps/web/src/api-clients/_common/constants/api-doc-constant.ts
  apps/web/src/api-clients/notification/protocol/composables/use-protocol-api.ts
  apps/web/src/api-clients/notification/protocol/schema/api-verbs/create.ts
  apps/web/src/api-clients/notification/protocol/schema/api-verbs/delete.ts
  apps/web/src/api-clients/notification/protocol/schema/api-verbs/disable.ts
  apps/web/src/api-clients/notification/protocol/schema/api-verbs/enable.ts
  apps/web/src/api-clients/notification/protocol/schema/api-verbs/get.ts
  apps/web/src/api-clients/notification/protocol/schema/api-verbs/list.ts
  apps/web/src/api-clients/notification/protocol/schema/api-verbs/update-plugin.ts
  apps/web/src/api-clients/notification/protocol/schema/api-verbs/update.ts
  apps/web/src/api-clients/notification/protocol/schema/model.ts
  apps/web/src/api-clients/notification/protocol/schema/type.ts
  apps/web/src/services/alert-manager/v2/components/NotificationsCreateForm.vue
  apps/web/src/services/alert-manager/v2/components/NotificationsCreateTypeSelector.vue
  apps/web/src/services/alert-manager/v2/components/ServiceDetailTabsNotifications.vue
  apps/web/src/services/alert-manager/v2/components/ServiceDetailTabsNotificationsDeleteModal.vue
  apps/web/src/services/alert-manager/v2/components/ServiceDetailTabsNotificationsDetail.vue
  apps/web/src/services/alert-manager/v2/components/ServiceDetailTabsNotificationsTableModal.vue
  apps/web/src/services/alert-manager/v2/components/ServiceDetailTabsNotificationsUpdateModal.vue
  apps/web/src/services/alert-manager/v2/components/ServiceDetailTabsOverviewNotification.vue
  apps/web/src/services/alert-manager/v2/components/ServiceDetailTabsSettingsEscalationPolicyFormChannelDropdown.vue
  apps/web/src/services/alert-manager/v2/composables/use-notification-protocol-list-query.ts
  apps/web/src/services/alert-manager/v2/pages/ServiceDetailPage.vue
  apps/web/src/services/alert-manager/v2/stores/service-create-form-store.ts
  apps/web/src/services/alert-manager/v2/stores/service-detail-page-store.ts
  apps/web/src/services/iam/components/UserGroupChannelAddFormData.vue
  apps/web/src/services/iam/components/UserGroupChannelSetInputForm.vue
  apps/web/src/services/iam/components/UserGroupManagementTabNotificationChannel.vue
  apps/web/src/services/iam/store/user-group-page-store.ts
  apps/web/src/services/my-page/components/NotificationAddFormData.vue
  apps/web/src/services/my-page/components/NotificationChannelList.vue
  apps/web/src/store/reference/protocol-reference-store.ts
Labels: pass/signedoff, self_approved/review

#5936 feat: update vue query pagination at service landing page
  apps/web/src/services/alert-manager/v2/components/ServiceList.vue
  apps/web/src/services/alert-manager/v2/composables/use-service-list-pagination-query.ts
Labels: pass/signedoff

#5938 fix: split link component tag
  apps/web/src/services/alert-manager/v2/components/AlertsManagementTable.vue
Labels: pass/signedoff, self_approved/review

#5942 fix(top-bar): resolve menu display issue (missing store changes)
  apps/web/src/common/modules/navigations/top-bar/TopBar.vue
  apps/web/src/common/modules/navigations/top-bar/modules/top-bar-toolset/modules/top-bar-integration/TopBarIntegration.vue
  apps/web/src/common/modules/navigations/top-bar/modules/top-bar-toolset/modules/top-bar-notice/TopBarNotice.vue
  apps/web/src/common/modules/navigations/top-bar/modules/top-bar-toolset/modules/top-bar-notifications/TopBarNotifications.vue
  apps/web/src/common/modules/portals/TopNotification.vue
Labels: pass/signedoff, self_approved/review

#5944 feat: apply vue-query to user group channel api
  apps/web/src/services/iam/components/SelectChannelCard.vue
  apps/web/src/services/iam/components/UserGroupChannelDeleteDoubleCheckModal.vue
  apps/web/src/services/iam/components/UserGroupChannelSetModal.vue
  apps/web/src/services/iam/components/UserGroupManagementTabNotificationChannel.vue
  apps/web/src/services/iam/components/UserGroupManagementTable.vue
  apps/web/src/services/iam/store/user-group-page-store.ts
Labels: pass/signedoff, self_approved/review

#5946 feat: apply vue-query to service channel api
  apps/web/src/api-clients/alert-manager/service-channel/composables/use-service-channel-api.ts
  apps/web/src/services/alert-manager/v2/components/ServiceCreateStep3.vue
  apps/web/src/services/alert-manager/v2/components/ServiceDetailMemberModal.vue
  apps/web/src/services/alert-manager/v2/components/ServiceDetailTabsNotifications.vue
  apps/web/src/services/alert-manager/v2/components/ServiceDetailTabsNotificationsDeleteModal.vue
  apps/web/src/services/alert-manager/v2/components/ServiceDetailTabsNotificationsDetail.vue
  apps/web/src/services/alert-manager/v2/components/ServiceDetailTabsNotificationsTableModal.vue
  apps/web/src/services/alert-manager/v2/components/ServiceDetailTabsNotificationsUpdateModal.vue
  apps/web/src/services/alert-manager/v2/components/ServiceDetailTabsOverviewNotification.vue
  apps/web/src/services/alert-manager/v2/components/ServiceDetailTabsSettingsEscalationPolicyFormChannelDropdown.vue
  apps/web/src/services/alert-manager/v2/composables/use-service-channel-create-mutation.ts
  apps/web/src/services/alert-manager/v2/composables/use-service-channel-list-query.ts
  apps/web/src/services/alert-manager/v2/pages/ServiceDetailNotificationsCreatePage.vue
  apps/web/src/services/alert-manager/v2/stores/service-detail-page-store.ts
Labels: pass/signedoff, self_approved/review

#5948 feat: apply vue-query to webhook api
  apps/web/src/services/alert-manager/v2/components/ServiceCreateStep2.vue
  apps/web/src/services/alert-manager/v2/components/ServiceDetailTabsOverviewWebhook.vue
  apps/web/src/services/alert-manager/v2/components/ServiceDetailTabsSettingsEventRuleScopeModal.vue
  apps/web/src/services/alert-manager/v2/components/ServiceDetailTabsWebhook.vue
  apps/web/src/services/alert-manager/v2/components/ServiceDetailTabsWebhookDeleteModal.vue
  apps/web/src/services/alert-manager/v2/components/ServiceDetailTabsWebhookDetail.vue
  apps/web/src/services/alert-manager/v2/components/ServiceDetailTabsWebhookTableModal.vue
  apps/web/src/services/alert-manager/v2/components/ServiceDetailTabsWebhookUpdateModal.vue
  apps/web/src/services/alert-manager/v2/composables/use-webhook-create-mutation.ts
  apps/web/src/services/alert-manager/v2/composables/use-webhook-list-pagination-query.ts
  apps/web/src/services/alert-manager/v2/composables/use-webhook-list-query.ts
  apps/web/src/services/alert-manager/v2/pages/ServiceDetailWebhookCreatePage.vue
Labels: pass/signedoff, self_approved/review

#5951 fix(reference-data-model): apply reference data model
  apps/web/src/common/modules/navigations/top-bar/modules/top-bar-toolset/modules/top-bar-profile/TopBarProfile.vue
  apps/web/src/common/modules/provider-list/ProviderButtonList.vue
  apps/web/src/common/modules/workspace/WorkspaceSelectDropdown.vue
  apps/web/src/lib/reference/use-reference-field-formatter.ts
  apps/web/src/services/_shared/dashboard/dashboard-detail/components/DashboardVariablesFormDynamic.vue
  apps/web/src/services/advanced/components/WorkspaceGroupTabWorkspace.vue
  apps/web/src/services/advanced/components/WorkspaceGroupUserDeleteModal.vue
  apps/web/src/services/advanced/components/WorkspaceGroupWokrspaceDeleteModal.vue
  apps/web/src/services/advanced/components/WorkspacesDeleteModal.vue
  apps/web/src/services/alert-manager/v1/components/AlertDetailInfoTableProject.vue
  apps/web/src/services/alert-manager/v1/components/AlertMainDataTableActions.vue
  apps/web/src/services/alert-manager/v1/components/EscalationPolicyDataTable.vue
  apps/web/src/services/alert-manager/v1/components/EscalationPolicyForm.vue
  apps/web/src/services/alert-manager/v2/components/ServiceDetailTabsSettingsEventRuleCard.vue
  apps/web/src/services/asset-inventory/components/CloudServiceDetail.vue
  apps/web/src/services/asset-inventory/components/CloudServiceDetailMultipleSelectedData.vue
  apps/web/src/services/asset-inventory/components/CloudServiceDetailTabs.vue
  apps/web/src/services/asset-inventory/components/CloudServiceListCard.vue
  apps/web/src/services/asset-inventory/components/CloudServiceTagsPanel.vue
  apps/web/src/services/asset-inventory/components/CollectorAdditionalRuleContent.vue
  apps/web/src/services/asset-inventory/components/CollectorDataModal.vue
  apps/web/src/services/asset-inventory/components/CollectorDetailAttachedServiceAccounts.vue
  apps/web/src/services/asset-inventory/components/CollectorHistoryJobTaskTable.vue
  apps/web/src/services/asset-inventory/components/CollectorProviderList.vue
  apps/web/src/services/asset-inventory/components/SecurityLSB.vue
  apps/web/src/services/asset-inventory/pages/CloudServiceDetailPage.vue
  apps/web/src/services/asset-inventory/pages/CloudServicePage.vue
  apps/web/src/services/asset-inventory/pages/CollectorMainPage.vue
  apps/web/src/services/asset-inventory/pages/MetricExplorerDetailPage.vue
  apps/web/src/services/asset-inventory/pages/MetricExplorerMainPage.vue
  apps/web/src/services/asset-inventory/pages/admin/AdminCollectorHistoryPage.vue
  apps/web/src/services/asset-inventory/pages/admin/AdminCollectorMainPage.vue
  apps/web/src/services/cost-explorer/components/AnomalyDetectionConfigurationInformation.vue
  apps/web/src/services/cost-explorer/components/AnomalyDetectionConfigurationTable.vue
  apps/web/src/services/cost-explorer/components/AnomalyDetectionHistoryTable.vue
  apps/web/src/services/cost-explorer/components/BudgetCreateProviderSelect.vue
  apps/web/src/services/cost-explorer/components/BudgetCreateScopeSelect.vue
  apps/web/src/services/cost-explorer/components/BudgetCreateStep2.vue
  apps/web/src/services/cost-explorer/components/BudgetDetailInfo.vue
  apps/web/src/services/cost-explorer/components/BudgetMainListCard.vue
  apps/web/src/services/cost-explorer/components/BudgetMainToolbox.vue
  apps/web/src/services/cost-explorer/components/CostAnalysisDataTable.vue
  apps/web/src/services/iam/components/AppManagementStatusModal.vue
  apps/web/src/services/iam/components/AppManagementTable.vue
  apps/web/src/services/iam/components/UserManagementTabAssignedRole.vue
  apps/web/src/services/my-page/components/NotificationAddMemberGroup.vue
  apps/web/src/services/project/v1/pages/ProjectDetailTabPage.vue
  apps/web/src/services/project/v1/pages/ProjectNotificationAddPage.vue
  apps/web/src/services/service-account/components/ServiceAccountAttachedGeneralAccounts.vue
  apps/web/src/services/service-account/components/ServiceAccountDeleteModal.vue
  apps/web/src/services/service-account/components/ServiceAccountProjectDetail.vue
  apps/web/src/services/service-account/composables/use-service-account-provider-list-query.ts
  apps/web/src/services/service-account/pages/ServiceAccountAddPage.vue
  apps/web/src/services/service-account/pages/ServiceAccountDetailPage.vue
  apps/web/src/services/service-account/pages/ServiceAccountPage.vue
  apps/web/src/services/workspace-home/shared/components/AccountSummary.vue
Labels: pass/signedoff, self_approved/review

#5950 feat: apply vue-query to service api
  apps/web/src/services/alert-manager/v2/components/AlertsManagementTable.vue
  apps/web/src/services/alert-manager/v2/components/ServiceCreateStep1.vue
  apps/web/src/services/alert-manager/v2/components/ServiceDetailDeleteModal.vue
  apps/web/src/services/alert-manager/v2/components/ServiceDetailEditModal.vue
  apps/web/src/services/alert-manager/v2/components/ServiceDetailHeader.vue
  apps/web/src/services/alert-manager/v2/components/ServiceDetailMemberModal.vue
  apps/web/src/services/alert-manager/v2/components/ServiceDetailTabsAlert.vue
  apps/web/src/services/alert-manager/v2/components/ServiceDetailTabsNotifications.vue
  apps/web/src/services/alert-manager/v2/components/ServiceDetailTabsNotificationsDeleteModal.vue
  apps/web/src/services/alert-manager/v2/components/ServiceDetailTabsNotificationsUpdateModal.vue
  apps/web/src/services/alert-manager/v2/components/ServiceDetailTabsOverviewEscalationPolicy.vue
  apps/web/src/services/alert-manager/v2/components/ServiceDetailTabsOverviewNotification.vue
  apps/web/src/services/alert-manager/v2/components/ServiceDetailTabsOverviewStatusTable.vue
  apps/web/src/services/alert-manager/v2/components/ServiceDetailTabsOverviewWebhook.vue
  apps/web/src/services/alert-manager/v2/components/ServiceDetailTabsSettings.vue
  apps/web/src/services/alert-manager/v2/components/ServiceDetailTabsSettingsEscalationPolicy.vue
  apps/web/src/services/alert-manager/v2/components/ServiceDetailTabsSettingsEscalationPolicyFormChannelDropdown.vue
  apps/web/src/services/alert-manager/v2/components/ServiceDetailTabsSettingsEscalationPolicyFormModal.vue
  apps/web/src/services/alert-manager/v2/components/ServiceDetailTabsSettingsEscalationPolicyStateModal.vue
  apps/web/src/services/alert-manager/v2/components/ServiceDetailTabsSettingsEventRule.vue
  apps/web/src/services/alert-manager/v2/components/ServiceDetailTabsSettingsEventRuleActionAlert.vue
  apps/web/src/services/alert-manager/v2/components/ServiceDetailTabsSettingsEventRuleActionService.vue
  apps/web/src/services/alert-manager/v2/components/ServiceDetailTabsSettingsEventRuleDeleteModal.vue
  apps/web/src/services/alert-manager/v2/components/ServiceDetailTabsSettingsEventRuleFormCard.vue
  apps/web/src/services/alert-manager/v2/components/ServiceDetailTabsSettingsEventRuleScopeModal.vue
  apps/web/src/services/alert-manager/v2/components/ServiceDetailTabsSettingsEventRuleSidebar.vue
  apps/web/src/services/alert-manager/v2/components/ServiceDetailTabsSettingsUpdateModal.vue
  apps/web/src/services/alert-manager/v2/components/ServiceDetailTabsWebhook.vue
  apps/web/src/services/alert-manager/v2/composables/use-event-rule-list-query.ts
  apps/web/src/services/alert-manager/v2/composables/use-service-channel-list-query.ts
  apps/web/src/services/alert-manager/v2/composables/use-service-get-query.ts
  apps/web/src/services/alert-manager/v2/composables/use-service-update-mutation.ts
  apps/web/src/services/alert-manager/v2/composables/use-webhook-list-query.ts
  apps/web/src/services/alert-manager/v2/pages/ServiceDetailPage.vue
  apps/web/src/services/alert-manager/v2/stores/service-create-form-store.ts
  apps/web/src/services/alert-manager/v2/stores/service-detail-page-store.ts
Labels: pass/signedoff, self_approved/review

#5954 refactor: move API calls from store to vue query
  apps/web/src/services/cost-explorer/CostExplorerContainer.vue
  apps/web/src/services/cost-explorer/components/CostAnalysisChart.vue
  apps/web/src/services/cost-explorer/components/CostAnalysisDataTable.vue
  apps/web/src/services/cost-explorer/components/CostAnalysisDataTypeDropdown.vue
  apps/web/src/services/cost-explorer/components/CostAnalysisFiltersAddMoreButton.vue
  apps/web/src/services/cost-explorer/components/CostAnalysisFiltersPopper.vue
  apps/web/src/services/cost-explorer/components/CostAnalysisGranularityPeriodDropdown.vue
  apps/web/src/services/cost-explorer/components/CostAnalysisGroupBy.vue
  apps/web/src/services/cost-explorer/components/CostAnalysisHeader.vue
  apps/web/src/services/cost-explorer/components/CostAnalysisLSB.vue
  apps/web/src/services/cost-explorer/components/CostAnalysisPeriodSelectDropdown.vue
  apps/web/src/services/cost-explorer/components/CostAnalysisQueryFormModal.vue
  apps/web/src/services/cost-explorer/components/CostAnalysisQuerySection.vue
  apps/web/src/services/cost-explorer/composables/queries/use-cost-query-set-query.ts
  apps/web/src/services/cost-explorer/pages/CostAnalysisPage.vue
  apps/web/src/services/cost-explorer/stores/cost-analysis-page-store.ts
  apps/web/src/services/cost-explorer/stores/cost-query-set-store.ts
Labels: pass/signedoff

#5957 chore: fixed minor issue
  apps/web/src/services/alert-manager/v2/components/ServiceDetailTabsSettingsEventRuleActionAsset.vue
  apps/web/src/services/alert-manager/v2/components/ServiceDetailTabsSettingsEventRuleCard.vue
  apps/web/src/services/alert-manager/v2/components/ServiceDetailTabsSettingsEventRuleFormCard.vue
  apps/web/src/services/cost-explorer/pages/admin/AdminAnomalyDetectionConfigurationPage.vue
  packages/language-pack/ko.json
Labels: pass/signedoff, self_approved/review

#5958 chore: apply minor issue
  apps/web/src/services/alert-manager/v2/components/ServiceDetailTabsSettingsEventRuleActionAsset.vue
  apps/web/src/services/alert-manager/v2/components/ServiceDetailTabsSettingsEventRuleCard.vue
  apps/web/src/services/alert-manager/v2/components/ServiceDetailTabsSettingsEventRuleFormCard.vue
  apps/web/src/services/cost-explorer/pages/admin/AdminAnomalyDetectionConfigurationPage.vue
  packages/language-pack/ko.json
Labels: pass/signedoff, self_approved/review

#5961 fix: prevent query filter cleared on change at cloud service page
  apps/web/src/services/asset-inventory/components/CloudServiceDetail.vue
Labels: pass/signedoff

#5962 refactor: apply vue query to cost anlaysis pages
  apps/web/src/services/cost-explorer/components/AdvancedSettingsAdjustmentGroupForm.vue
  apps/web/src/services/cost-explorer/components/AdvancedSettingsAdjustmentsForm.vue
  apps/web/src/services/cost-explorer/components/AdvancedSettingsCostReportConfiguration.vue
  apps/web/src/services/cost-explorer/components/AdvancedSettingsSetAdjustmentsOverlay.vue
  apps/web/src/services/cost-explorer/components/CostAnalysisChart.vue
  apps/web/src/services/cost-explorer/components/CostAnalysisDataTable.vue
  apps/web/src/services/cost-explorer/components/CostAnalysisFiltersPopper.vue
  apps/web/src/services/cost-explorer/components/CostAnalysisHeader.vue
  apps/web/src/services/cost-explorer/components/CostAnalysisLSB.vue
  apps/web/src/services/cost-explorer/components/CostAnalysisPeriodSelectDropdown.vue
  apps/web/src/services/cost-explorer/components/CostAnalysisQueryFormModal.vue
  apps/web/src/services/cost-explorer/components/CostAnalysisQuerySection.vue
  apps/web/src/services/cost-explorer/components/CostAnalysisStackedColumnChart.vue
  apps/web/src/services/cost-explorer/components/CostReportUpcomingReportCard.vue
  apps/web/src/services/cost-explorer/composables/use-cost-analyze-query.ts
  apps/web/src/services/cost-explorer/composables/use-cost-query-set-query.ts
  apps/web/src/services/cost-explorer/composables/use-cost-report-config-query.ts
  apps/web/src/services/cost-explorer/composables/use-report-adjustment-policy-query.ts
  apps/web/src/services/cost-explorer/composables/use-report-adjustment-query.ts
  apps/web/src/services/cost-explorer/composables/use-unified-cost-analyze-query.ts
  apps/web/src/services/cost-explorer/pages/CostAnalysisPage.vue
  apps/web/src/services/cost-explorer/stores/cost-query-set-store.ts
Labels: pass/signedoff

#5965 fix(trusted-account): solve trusted-account auto-sync additional option update bug
  apps/web/src/services/service-account/components/ServiceAccountAutoSyncForm.vue
Labels: pass/signedoff, self_approved/review

#5964 refactor: apply `useCostReportDataAnalyzeQuery` to pages
  apps/web/src/api-clients/cost-analysis/cost-report-data/composables/use-cost-report-data-api.ts
  apps/web/src/api-clients/cost-analysis/cost-report-data/schema/api-verbs/analyze.ts
  apps/web/src/api-clients/cost-analysis/cost-report-data/schema/api-verbs/list.ts
  apps/web/src/api-clients/cost-analysis/cost-report/composables/use-cost-report-api.ts
  apps/web/src/common/pages/CostReportDetailPage.vue
  apps/web/src/services/cost-explorer/components/CostReportMonthlyTotalAmountSummaryCard.vue
  apps/web/src/services/cost-explorer/components/CostReportOverviewCostTrendCard.vue
  apps/web/src/services/cost-explorer/components/CostReportReportsTab.vue
  apps/web/src/services/cost-explorer/components/CostReportResendModal.vue
  apps/web/src/services/cost-explorer/composables/use-cost-analyze-query.ts
  apps/web/src/services/cost-explorer/composables/use-cost-report-data-analyze-query.ts
  apps/web/src/services/cost-explorer/composables/use-cost-report-get-query.ts
  apps/web/src/services/cost-explorer/composables/use-cost-report-list-query.ts
  apps/web/src/services/cost-explorer/pages/CostReportPage.vue
  apps/web/src/services/cost-explorer/stores/cost-report-page-store.ts
  apps/web/src/services/cost-explorer/types/cost-report-data-type.ts
Labels: pass/signedoff
