Repository cloudforet-io/console, pull requests merged in 2025-04, with the labels that each got.

#5731 fix: fixed page access menu
  apps/web/src/lib/access-control/page-access-helper.ts
  apps/web/src/lib/config/global-config/type.ts
  apps/web/src/services/iam/components/RoleManagementTabDetail.vue
  apps/web/src/services/iam/components/RoleUpdateFormPermissionForm.vue
  apps/web/src/services/iam/constants/role-constant.ts
  apps/web/src/services/iam/helpers/role-page-access-menu-list.ts
  apps/web/src/services/iam/types/role-type.ts
Labels: pass/signedoff

#5732 Merge pull request #5731 from skdud4659/hotfix-role-bug
  apps/web/src/lib/access-control/page-access-helper.ts
  apps/web/src/lib/config/global-config/type.ts
  apps/web/src/services/iam/components/RoleManagementTabDetail.vue
  apps/web/src/services/iam/components/RoleUpdateFormPermissionForm.vue
  apps/web/src/services/iam/constants/role-constant.ts
  apps/web/src/services/iam/helpers/role-page-access-menu-list.ts
  apps/web/src/services/iam/types/role-type.ts
Labels: fail/signedoff, self_approved/review

#5716 feat: set service name at breadcrumbs
  apps/web/src/services/alert-manager/v2/components/AlertDetailTabsTimelineModal.vue
  apps/web/src/services/alert-manager/v2/pages/ServiceDetailPage.vue
Labels: pass/signedoff

#5733 chore: merge develop to master
  apps/web/package.json
  apps/web/src/services/alert-manager/v2/components/AlertDetailTabsTimelineModal.vue
  apps/web/src/services/alert-manager/v2/pages/ServiceDetailPage.vue
  package-lock.json
  packages/core-lib/package.json
  packages/mirinae/package.json
  packages/utils/package.json
  turbo.json
Labels: fail/signedoff, self_approved/review

#5734 fix(collector-job): add missing route name prefix (admin collector job page)
  apps/web/src/services/asset-inventory/routes/admin/route-constant.ts
Labels: pass/signedoff, self_approved/review

#5735 feat: add service_name, description fields at alert excel
  apps/web/src/services/alert-manager/v2/components/AlertsManagementTable.vue
  apps/web/src/services/alert-manager/v2/constants/alert-table-constant.ts
Labels: pass/signedoff, self_approved/review

#5736 chore: apply webhook/app name at alert excel
  apps/web/src/services/alert-manager/v2/components/AlertsManagementTable.vue
Labels: pass/signedoff, self_approved/review

#5737 chore(route-config): fix wrong route config usage
  apps/web/src/services/advanced/routes/admin/routes.ts
  apps/web/src/services/alert-manager/v2/routes/routes.ts
  apps/web/src/services/asset-inventory/routes/admin/routes.ts
  apps/web/src/services/asset-inventory/routes/routes.ts
Labels: pass/signedoff, self_approved/review

#5739 fix: fixed reference fields (alert excel)
  apps/web/src/services/alert-manager/v2/components/AlertsManagementTable.vue
  apps/web/src/services/alert-manager/v2/constants/alert-table-constant.ts
Labels: pass/signedoff, self_approved/review

#5740 feat: do not hide search when there're no menu
  packages/mirinae/src/controls/context-menu/PContextMenu.vue
Labels: pass/signedoff

#5738 feat: update task when its' TODO & add 'Task ID' field, filter to Ticket Board
  apps/web/src/services/ops-flow/components/BoardTaskFilters.vue
  apps/web/src/services/ops-flow/components/BoardTaskTable.vue
  apps/web/src/services/ops-flow/composables/use-task-ids-field.ts
  apps/web/src/services/ops-flow/pages/TaskDetailPage.vue
  apps/web/src/services/ops-flow/stores/task-content-form-store.ts
  apps/web/src/services/ops-flow/task-fields-form/TaskFieldsForm.vue
  apps/web/src/services/ops-flow/types/task-filters-type.ts
Labels: pass/signedoff

#5741 chore: merge develop to master
  apps/web/src/services/advanced/routes/admin/routes.ts
  apps/web/src/services/alert-manager/v2/routes/routes.ts
  apps/web/src/services/asset-inventory/routes/admin/routes.ts
  apps/web/src/services/asset-inventory/routes/routes.ts
  apps/web/src/services/ops-flow/components/BoardTaskFilters.vue
  apps/web/src/services/ops-flow/components/BoardTaskTable.vue
  apps/web/src/services/ops-flow/composables/use-task-ids-field.ts
  apps/web/src/services/ops-flow/pages/TaskDetailPage.vue
  apps/web/src/services/ops-flow/stores/task-content-form-store.ts
  apps/web/src/services/ops-flow/task-fields-form/TaskFieldsForm.vue
  apps/web/src/services/ops-flow/types/task-filters-type.ts
  packages/mirinae/src/controls/context-menu/PContextMenu.vue
Labels: fail/signedoff

#5742 chore: add type at alert excel field
  apps/web/src/services/alert-manager/v2/constants/alert-table-constant.ts
Labels: pass/signedoff, self_approved/review

#5743 fix: fixed route bug
  apps/web/src/lib/site-initializer/index.ts
  apps/web/src/lib/site-initializer/mode-setting.ts
  apps/web/src/services/configurator.ts
  apps/web/src/store/display/display-store.ts
Labels: pass/signedoff, self_approved/review

#5744 feat(mirinae): add text ellipsis detection hook and improve button components
  packages/mirinae/src/controls/buttons/button/PButton.mdx
  packages/mirinae/src/controls/buttons/button/PButton.stories.ts
  packages/mirinae/src/controls/buttons/button/PButton.vue
  packages/mirinae/src/controls/buttons/button/story-helper.ts
  packages/mirinae/src/controls/buttons/button/type.ts
  packages/mirinae/src/controls/buttons/icon-button/PIconButton.vue
  packages/mirinae/src/controls/dropdown/select-dropdown/PSelectDropdown.mdx
  packages/mirinae/src/controls/dropdown/select-dropdown/PSelectDropdown.stories.ts
  packages/mirinae/src/controls/dropdown/select-dropdown/PSelectDropdown.vue
  packages/mirinae/src/controls/dropdown/select-dropdown/components/dropdown-button.vue
  packages/mirinae/src/controls/dropdown/select-dropdown/story-helper.ts
  packages/mirinae/src/hooks/index.ts
  packages/mirinae/src/hooks/use-text-ellipsis/type.ts
  packages/mirinae/src/hooks/use-text-ellipsis/use-text-ellipsis.stories.ts
  packages/mirinae/src/hooks/use-text-ellipsis/use-text-ellipsis.ts
  packages/mirinae/src/hooks/use-text-ellipsis/useTextEllipsis.mdx
Labels: pass/signedoff, fail/signedoff

#5747 chore(dashboard-query): apply optimization (global component)
  apps/web/src/common/modules/favorites/favorite-button/FavoriteButton.vue
  apps/web/src/common/modules/navigations/top-bar/modules/top-bar-toolset/modules/top-bar-favorite/modules/TopBarFavoriteContextMenu.vue
  apps/web/src/services/workspace-home/components/UserConfigRecent.vue
Labels: pass/signedoff, self_approved/review

#5749 chore: solve job history page issue (missing var)
  apps/web/src/services/asset-inventory/components/CollectorHistoryJobTaskTable.vue
Labels: pass/signedoff, self_approved/review

#5748 chore: remove query key in api client composable
  apps/web/src/api-clients/dashboard/private-dashboard/composables/use-private-dashboard-api.ts
  apps/web/src/api-clients/dashboard/private-data-table/composables/use-private-data-table-api.ts
  apps/web/src/api-clients/dashboard/private-folder/composables/use-private-folder-api.ts
  apps/web/src/api-clients/dashboard/private-widget/composables/use-private-widget-api.ts
  apps/web/src/api-clients/dashboard/public-dashboard/composables/use-public-dashboard-api.ts
  apps/web/src/api-clients/dashboard/public-data-table/composables/use-public-data-table-api.ts
  apps/web/src/api-clients/dashboard/public-folder/composables/use-public-folder-api.ts
  apps/web/src/api-clients/dashboard/public-widget/composables/use-public-widget-api.ts
Labels: pass/signedoff, self_approved/review

#5751 fix: update useScopedQuery to handle undefined queryEnabled state and add slot props to Tab component
  apps/web/src/api-clients/_common/composables/use-scoped-query.ts
  packages/mirinae/src/navigation/tabs/tab/PTab.vue
Labels: pass/signedoff

#5758 feat: update budget main page as feedback
  apps/web/src/services/cost-explorer/components/BudgetMainList.vue
  apps/web/src/services/cost-explorer/components/BudgetMainToolset.vue
  packages/mirinae/src/foundation/icons/p-icons/index.js
Labels: pass/signedoff, self_approved/review

#5760 feat(project-dashboard): create project-dashboard actions
  apps/web/src/services/dashboard-shared/core/actions/use-dashboard-clone-action.ts
  apps/web/src/services/dashboard-shared/core/actions/use-dashboard-delete-action.ts
  apps/web/src/services/dashboard-shared/core/actions/use-dashboard-folder-delete-action.ts
  apps/web/src/services/dashboard-shared/dashboard-detail/DashboardDetailBody.vue
  apps/web/src/services/dashboards/components/dashboard-detail/DashboardCloneModal.vue
  apps/web/src/services/dashboards/components/dashboard-detail/DashboardDetailHeader.vue
  apps/web/src/services/dashboards/helpers/dashboard-tree-data-helper.ts
  apps/web/src/services/project/v2/components/ProjectDashboard.vue
  apps/web/src/services/project/v2/components/ProjectDashboardChangeFolderModal.vue
  apps/web/src/services/project/v2/components/ProjectDashboardCloneModal.vue
  apps/web/src/services/project/v2/components/ProjectDashboardDeleteModal.vue
  apps/web/src/services/project/v2/components/ProjectDashboardFolderFormModal.vue
  apps/web/src/services/project/v2/components/ProjectDashboardNameEditModal.vue
  apps/web/src/services/project/v2/components/ProjectDetailTab.vue
  apps/web/src/services/project/v2/composables/queries/use-project-dashboard-folder-query.ts
  apps/web/src/services/project/v2/composables/queries/use-project-dashboard-query.ts
  apps/web/src/services/project/v2/pages/ProjectMainPage.vue
  apps/web/src/services/project/v2/stores/project-page-modal-store.ts
Labels: pass/signedoff, self_approved/review

#5761 refactor: refactor global-config
  apps/web/src/api-clients/api-client-manager.ts
  apps/web/src/common/composables/contents-accessibility/index.ts
  apps/web/src/common/modules/navigations/stores/gnb-store.ts
  apps/web/src/common/modules/navigations/top-bar/modules/top-bar-toolset/TopBarToolset.vue
  apps/web/src/components/GlobalMenu.vue
  apps/web/src/lib/access-control/page-access-helper.ts
  apps/web/src/lib/access-control/redirect-route-helper.ts
  apps/web/src/lib/config/global-config/constants/constants.ts
  apps/web/src/lib/config/global-config/feature-schema-manager.ts
  apps/web/src/lib/config/global-config/feature-schema.ts
  apps/web/src/lib/config/global-config/generate-routes.ts
  apps/web/src/lib/config/global-config/helpers/get-feature-configurator.ts
  apps/web/src/lib/config/global-config/schema/api-client-schema.ts
  apps/web/src/lib/config/global-config/type.ts
  apps/web/src/lib/config/global-config/types/type.ts
  apps/web/src/lib/menu/config.ts
  apps/web/src/lib/menu/menu-architecture.ts
  apps/web/src/lib/site-initializer/index.ts
  apps/web/src/lib/site-initializer/merge-config.ts
  apps/web/src/lib/site-initializer/mode-setting.ts
  apps/web/src/services/alert-manager/configurator.ts
  apps/web/src/services/asset-inventory/components/CloudServiceDetailTabs.vue
  apps/web/src/services/asset-inventory/configurator.ts
  apps/web/src/services/asset-inventory/stores/cloud-service-detail-page-store.ts
  apps/web/src/services/configurator.ts
  apps/web/src/services/cost-explorer/configurator.ts
  apps/web/src/services/cost-explorer/pages/BudgetDetailPage.vue
  apps/web/src/services/cost-explorer/stores/budget-detail-page-store.ts
  apps/web/src/services/dashboards/configurator.ts
  apps/web/src/services/iam/configurator.ts
  apps/web/src/services/iam/constants/role-constant.ts
  apps/web/src/services/iam/routes/admin/routes.ts
  apps/web/src/services/iam/routes/routes.ts
  apps/web/src/services/iam/types/role-type.ts
  apps/web/src/services/my-page/components/NotificationAddForm.vue
  apps/web/src/services/my-page/components/NotificationChannelList.vue
  apps/web/src/services/my-page/composables/notification-item.ts
  apps/web/src/services/my-page/stores/my-page-store.ts
  apps/web/src/services/ops-flow/configurator.ts
  apps/web/src/services/project/configurator.ts
  apps/web/src/services/project/v1/components/ProjectDetailTabHeader.vue
  apps/web/src/services/project/v1/pages/ProjectDetailTabPage.vue
  apps/web/src/services/project/v1/pages/ProjectSummaryPage.vue
  apps/web/src/services/project/v1/stores/project-detail-page-store.ts
  apps/web/src/services/service-account/configurator.ts
  apps/web/src/store/app-context/app-context-store.ts
  apps/web/src/store/display/display-store.ts
  apps/web/src/store/global-config/global-config-store.ts
  apps/web/src/store/menu/menu-store.ts
Labels: pass/signedoff, self_approved/review

#5763 fix: fixed minor bug (global-config)
  apps/web/src/lib/config/global-config/feature-schema-manager.ts
  apps/web/src/lib/config/global-config/types/type.ts
  apps/web/src/services/iam/components/UserGroupManagementTabUsers.vue
  apps/web/src/services/iam/configurator.ts
  apps/web/src/services/ops-flow/configurator.ts
Labels: pass/signedoff, self_approved/review

#5764 refactor: refactor generate routes helper
  apps/web/src/lib/config/global-config/helpers/generate-routes.ts
  apps/web/src/lib/config/global-config/types/type.ts
  apps/web/src/lib/site-initializer/index.ts
  apps/web/src/router/alert-manager-v1-admin-routes.ts
  apps/web/src/router/alert-manager-v1-workspace-routes.ts
  apps/web/src/router/type.ts
  apps/web/src/router/workspace-routes.ts
  apps/web/src/services/alert-manager/configurator.ts
  apps/web/src/services/asset-inventory/configurator.ts
  apps/web/src/services/cost-explorer/configurator.ts
  apps/web/src/services/dashboards/configurator.ts
  apps/web/src/services/iam/configurator.ts
  apps/web/src/services/ops-flow/configurator.ts
  apps/web/src/services/project/configurator.ts
  apps/web/src/services/service-account/configurator.ts
Labels: pass/signedoff, self_approved/review

#5766 chore: add missed menu
  apps/web/src/services/asset-inventory/configurator.ts
  apps/web/src/services/cost-explorer/configurator.ts
Labels: pass/signedoff, self_approved/review

#5767 chore: remove unnecessary import (defineEmits)
  apps/web/src/common/modules/navigations/top-bar/modules/top-bar-toolset/modules/top-bar-favorite/TopBarFavorite.vue
  apps/web/src/services/cost-explorer/components/BudgetCreateFormBaseInfo.vue
  apps/web/src/services/cost-explorer/components/BudgetMainToolbox.vue
  apps/web/src/services/cost-explorer/components/CostAnalysisChartLegends.vue
  apps/web/src/services/cost-explorer/components/CostAnalysisFiltersAddMoreButton.vue
  apps/web/src/services/dashboards/components/dashboard-create/DashboardCreateStep2BundleCase.vue
  apps/web/src/services/dashboards/components/dashboard-create/DashboardCreateStep2SingleCase.vue
  apps/web/src/services/dashboards/widgets/_base-widgets/base-pie/BasePieWidget.vue
  apps/web/src/services/dashboards/widgets/_base-widgets/base-trend/BaseTrendWidget.vue
  apps/web/src/services/dashboards/widgets/asset-widgets/compliance-status/ComplianceStatusWidget.vue
  apps/web/src/services/dashboards/widgets/asset-widgets/severity-status-by-service/SeverityStatusByServiceWidget.vue
  apps/web/src/services/dashboards/widgets/asset-widgets/total-fail-findings-history/TotalFailFindingsHistoryWidget.vue
  apps/web/src/services/dashboards/widgets/asset-widgets/total-fail-findings-status/TotalFailFindingsStatusWidget.vue
  apps/web/src/services/dashboards/widgets/asset-widgets/trend-of-pass-and-fail-findings/TrendOfPassAndFailFindingsWidget.vue
  apps/web/src/services/dashboards/widgets/cost-widgets/budget-status/BudgetStatusWidget.vue
  apps/web/src/services/dashboards/widgets/cost-widgets/budget-usage-by-target/BudgetUsageByTargetWidget.vue
  apps/web/src/services/dashboards/widgets/cost-widgets/budget-usage-summary/BudgetUsageSummaryWidget.vue
  apps/web/src/services/dashboards/widgets/cost-widgets/cost-by-region-multi-fields/CostByRegionMultiFieldsWidget.vue
  apps/web/src/services/dashboards/widgets/cost-widgets/cost-by-region/CostByRegionWidget.vue
  apps/web/src/services/dashboards/widgets/cost-widgets/cost-map/CostMapWidget.vue
  apps/web/src/services/dashboards/widgets/cost-widgets/cost-summary-multi-fields/CostSummaryMultiFieldsWidget.vue
  apps/web/src/services/dashboards/widgets/cost-widgets/monthly-cost/MonthlyCostWidget.vue
  apps/web/src/services/service-account/components/ServiceAccountEditModal.vue
  packages/mirinae/src/data-display/tree/he-tree-vue/components/Tree.vue
  packages/mirinae/src/layouts/centered-layout/centered-layout-header/PCenteredLayoutHeader.vue
Labels: pass/signedoff, self_approved/review

#5768 fix: fixed minor bug
  apps/web/src/common/modules/navigations/top-bar/modules/top-bar-toolset/TopBarToolset.vue
  apps/web/src/lib/config/global-config/feature-schema-manager.ts
  apps/web/src/lib/config/global-config/types/type.ts
  apps/web/src/lib/site-initializer/index.ts
  apps/web/src/lib/site-initializer/initTaskManagementTemplate.ts
  apps/web/src/lib/site-initializer/merge-config.ts
  apps/web/src/services/alert-manager/v2/components/ServiceDetailTabsSettingsEventRuleCard.vue
  apps/web/src/services/asset-inventory/components/CloudServiceDetailTabs.vue
  apps/web/src/services/auth/authenticator/index.ts
  apps/web/src/services/cost-explorer/pages/BudgetDetailPage.vue
  apps/web/src/services/my-page/components/NotificationAddForm.vue
  apps/web/src/services/my-page/components/NotificationChannelList.vue
  apps/web/src/services/my-page/composables/notification-item.ts
  apps/web/src/services/ops-flow/configurator.ts
  apps/web/src/services/ops-flow/task-management-templates/stores/use-task-management-template-store.ts
Labels: pass/signedoff, self_approved/review

#5769 feat: update budget main page
  apps/web/src/api-clients/cost-analysis/budget/schema/api-verbs/set-notification.ts
  apps/web/src/api-clients/cost-analysis/budget/schema/api-verbs/update.ts
  apps/web/src/api-clients/cost-analysis/budget/schema/model.ts
  apps/web/src/services/cost-explorer/components/BudgetCreateStep3.vue
  apps/web/src/services/cost-explorer/components/BudgetDeleteCheckModal.vue
  apps/web/src/services/cost-explorer/components/BudgetDetailDeleteModal.vue
  apps/web/src/services/cost-explorer/components/BudgetMainList.vue
  apps/web/src/services/cost-explorer/constants/budget-constant.ts
  apps/web/src/services/cost-explorer/stores/budget-detail-page-store.ts
Labels: pass/signedoff, self_approved/review

#5770 feat: reflect additional requirements for alert period selection
  apps/web/src/services/alert-manager/v2/components/AlertsManagementTable.vue
  apps/web/src/services/alert-manager/v2/constants/alert-table-constant.ts
  apps/web/src/services/alert-manager/v2/helpers/alert-period-helper.ts
  packages/language-pack/ko.json
  packages/mirinae/src/controls/datetime-picker/PDatetimePicker.vue
Labels: pass/signedoff, self_approved/review

#5771 feat: update unifiedCost trend chart at budget create page
  apps/web/src/services/cost-explorer/components/BudgetCreateStep3.vue
  apps/web/src/services/cost-explorer/components/BudgetLastThreeMonthCostTrendBarChart.vue
Labels: pass/signedoff, self_approved/review

#5774 feat: service router applied (project)
  apps/web/src/common/modules/monitoring/Monitoring.vue
  apps/web/src/common/modules/navigations/top-bar/modules/top-bar-search/helper.ts
  apps/web/src/common/modules/navigations/top-bar/modules/top-bar-search/modules/top-bar-search-dropdown/TopBarSearchDropdown.vue
  apps/web/src/common/modules/navigations/top-bar/modules/top-bar-search/modules/top-bar-search-dropdown/modules/TopBarSearchRecentListItem.vue
  apps/web/src/common/modules/navigations/top-bar/modules/top-bar-toolset/modules/top-bar-favorite/modules/TopBarFavoriteContextMenu.vue
  apps/web/src/common/modules/project/ProjectLinkButton.vue
  apps/web/src/common/modules/project/ProjectSelectDropdown.vue
  apps/web/src/common/modules/widgets/_widgets/table/Table.vue
  apps/web/src/lib/access-control/page-access-helper.ts
  apps/web/src/lib/access-control/redirect-route-helper.ts
  apps/web/src/lib/config/global-config/feature-schema-manager.ts
  apps/web/src/lib/menu/menu-info.ts
  apps/web/src/lib/reference/referenceFieldFormatter.ts
  apps/web/src/lib/reference/referenceRouter.ts
  apps/web/src/lib/reference/use-reference-field-formatter.ts
  apps/web/src/router/composables/use-reference-router.ts
  apps/web/src/router/helpers/route-helper.ts
  apps/web/src/router/helpers/use-service-router.ts
  apps/web/src/router/types.ts
  apps/web/src/services/alert-manager/configurator.ts
  apps/web/src/services/alert-manager/v1/components/AlertDashboardTop5ProjectActivityWidget.vue
  apps/web/src/services/alert-manager/v1/components/AlertDetailInfoTableProject.vue
  apps/web/src/services/alert-manager/v1/components/AlertListItem.vue
  apps/web/src/services/alert-manager/v1/components/AlertMainDataTable.vue
  apps/web/src/services/alert-manager/v1/components/EscalationPolicyDataTable.vue
  apps/web/src/services/alert-manager/v1/components/EscalationPolicyForm.vue
  apps/web/src/services/asset-inventory/components/CloudServiceDetail.vue
  apps/web/src/services/asset-inventory/components/CloudServiceDetailMultipleSelectedData.vue
  apps/web/src/services/asset-inventory/components/CloudServiceDetailTabs.vue
  apps/web/src/services/asset-inventory/components/CloudServiceListCard.vue
  apps/web/src/services/asset-inventory/components/CollectorAdditionalRuleContent.vue
  apps/web/src/services/asset-inventory/components/CollectorDetailAttachedServiceAccounts.vue
  apps/web/src/services/asset-inventory/components/CollectorHistoryJobTaskTable.vue
  apps/web/src/services/asset-inventory/pages/CloudServiceDetailPage.vue
  apps/web/src/services/cost-explorer/components/BudgetDetailInfo.vue
  apps/web/src/services/cost-explorer/components/CostAnalysisDataTable.vue
  apps/web/src/services/dashboards/components/dashboard-main/DashboardBundleDeleteModal.vue
  apps/web/src/services/iam/components/RoleManagementTabDetail.vue
  apps/web/src/services/iam/components/RoleUpdateFormPermissionForm.vue
  apps/web/src/services/iam/components/UserManagementTabAssignedRole.vue
  apps/web/src/services/iam/components/UserManagementTabProjects.vue
  apps/web/src/services/my-page/composables/notification-item.ts
  apps/web/src/services/project/configurator.ts
  apps/web/src/services/project/v1/components/ProjectAlertEventRuleContent.vue
  apps/web/src/services/project/v1/components/ProjectSummaryPersonalHealthDashboardWidget.vue
  apps/web/src/services/project/v1/pages/ProjectDetailPageLegacy.vue
  apps/web/src/services/project/v1/pages/ProjectDetailTabPage.vue
  apps/web/src/services/project/v2/components/ProjectDashboardDeleteModal.vue
  apps/web/src/services/service-account/components/ServiceAccountAttachedGeneralAccounts.vue
  apps/web/src/services/service-account/components/ServiceAccountBaseInformationDetail.vue
  apps/web/src/services/service-account/components/ServiceAccountCredentialsDetail.vue
  apps/web/src/services/service-account/components/ServiceAccountProjectDetail.vue
  apps/web/src/services/service-account/pages/ServiceAccountPage.vue
  apps/web/src/services/workspace-home/components/UserConfigsItem.vue
  apps/web/src/services/workspace-home/constants/workspace-home-constant.ts
  apps/web/src/store/display/display-store.ts
  apps/web/src/store/user/user-store.ts
Labels: pass/signedoff, self_approved/review

#5776 fix: fix initiating service account `secret type` form
  apps/web/src/services/service-account/components/ServiceAccountCredentialsForm.vue
Labels: pass/signedoff

#5777 chore: changed default global config and fixed readMe
  README.md
  apps/web/public/config/default.json
  apps/web/public/config/development.json.sample
Labels: pass/signedoff, self_approved/review

#5779 chore: solve project-dashboard bugs
  apps/web/src/services/_shared/dashboard/core/composables/use-dashboard-control-menu-helper.ts
  apps/web/src/services/project/v2/components/ProjectDashboardBundleCloneModal.vue
  apps/web/src/services/project/v2/components/ProjectDashboardEditListOverlay.vue
  apps/web/src/services/project/v2/composables/queries/use-project-dashboard-folder-query.ts
  apps/web/src/services/project/v2/stores/Project-dashboard-modal-store.ts
Labels: pass/signedoff, self_approved/review

#5781 chore(project): apply changed UX writing
  apps/web/src/services/_shared/dashboard/dashboard-create/components/DashboardCreateBlankBoardItem.vue
  apps/web/src/services/_shared/dashboard/dashboard-create/components/DashboardCreateStep2.vue
  apps/web/src/services/_shared/dashboard/dashboard-create/contextual-components/DashboardCreateStep2SingleCase.vue
  apps/web/src/services/project/v2/pages/ProjectMainPage.vue
Labels: pass/signedoff, self_approved/review

#5782 chore: solve dashboard create bug
  apps/web/src/services/_shared/dashboard/core/composables/use-dashboard-control-menu-helper.ts
  apps/web/src/services/_shared/dashboard/dashboard-create/contextual-components/DashboardCreateScopeForm.vue
  apps/web/src/services/_shared/dashboard/dashboard-create/contextual-components/DashboardCreateStep1.vue
  apps/web/src/services/dashboards/components/dashboard-folder/DashboardFolderTree.vue
  apps/web/src/services/dashboards/components/dashboard-folder/DashboardFolderTreeItem.vue
  apps/web/src/services/project/v2/components/ProjectDashboardEditListOverlay.vue
Labels: pass/signedoff, self_approved/review

#5783 chore(dashboard-qa): small fix
  apps/web/src/query/composables/use-scoped-query.ts
  apps/web/src/services/_shared/dashboard/dashboard-detail/components/DashboardWidgetContainerV2.vue
Labels: pass/signedoff, self_approved/review

#5787 fix(dashboard-tree): apply text highlighting UI
  apps/web/src/services/dashboards/components/dashboard-folder/DashboardFolderTree.vue
  apps/web/src/services/dashboards/components/dashboard-folder/DashboardFolderTreeItem.vue
  apps/web/src/services/dashboards/components/dashboard-main/DashboardBundleDeleteModal.vue
  apps/web/src/services/dashboards/pages/DashboardsMainPage.vue
  apps/web/src/services/project/v2/components/ProjectDashboardEditListOverlay.vue
  packages/language-pack/en.json
  packages/language-pack/ja.json
  packages/language-pack/ko.json
Labels: pass/signedoff, self_approved/review

#5788 chore: minor changed
  apps/web/src/components/GlobalMenu.vue
  apps/web/src/router/composables/use-reference-router.ts
  apps/web/src/router/composables/use-service-router.ts
  apps/web/src/services/asset-inventory/components/CloudServiceDetail.vue
  apps/web/src/services/asset-inventory/components/CloudServiceDetailMultipleSelectedData.vue
  apps/web/src/services/asset-inventory/components/CloudServiceDetailTabs.vue
  apps/web/src/services/asset-inventory/pages/CloudServiceDetailPage.vue
Labels: pass/signedoff, self_approved/review

#5790 chore: fix error when copying dashboards without widgets & etc...
  apps/web/src/common/modules/widgets/_helpers/widget-load-helper.ts
  apps/web/src/services/_shared/dashboard/core/helpers/dashboard-layout-template-helper.ts
  apps/web/src/services/project/v2/components/ProjectDashboardEditListOverlay.vue
Labels: pass/signedoff

#5791 refactor: extract internal event (click tree item)
  apps/web/src/services/dashboards/components/dashboard-folder/DashboardFolderTree.vue
  apps/web/src/services/dashboards/components/dashboard-folder/DashboardFolderTreeItem.vue
  apps/web/src/services/dashboards/pages/DashboardsMainPage.vue
  apps/web/src/services/project/v2/components/ProjectDashboardEditListOverlay.vue
  apps/web/src/services/project/v2/pages/ProjectMainPage.vue
Labels: pass/signedoff, self_approved/review

#5792 refactor: refactor global-config codes
  apps/web/src/lib/config/global-config/dynamic-schema-manager.ts
  apps/web/src/lib/config/global-config/feature-schema-manager.ts
  apps/web/src/lib/config/global-config/helpers/merge-config.ts
  apps/web/src/lib/menu/config.ts
  apps/web/src/lib/site-initializer/index.ts
  apps/web/src/lib/site-initializer/initTaskManagementTemplate.ts
  apps/web/src/services/ops-flow/configurator.ts
  apps/web/src/store/display/composables/use-advanced-menu-display.ts
  apps/web/src/store/display/display-store.ts
  apps/web/src/store/global-config-schema/global-config-schema-store.ts
Labels: pass/signedoff, self_approved/review

#5793 chore: add missed api endpoint
  apps/web/src/lib/config/global-config/api-client-manager.ts
  apps/web/src/lib/config/global-config/schema/api-client-schema.ts
  apps/web/src/lib/config/global-config/types/type.ts
  apps/web/src/lib/site-initializer/index.ts
  apps/web/src/store/reference/escalation-policy-reference-store.ts
  apps/web/src/store/reference/service-reference-store.ts
  apps/web/src/store/reference/webhook-reference-store.ts
Labels: pass/signedoff, self_approved/review

#5794 chore(budget-qa): fix budget qa
  apps/web/src/api-clients/cost-analysis/budget/schema/model.ts
  apps/web/src/api-clients/cost-analysis/budget/schema/type.ts
  apps/web/src/services/cost-explorer/components/BudgetAlertsModal.vue
  apps/web/src/services/cost-explorer/components/BudgetCreateManagerSelect.vue
  apps/web/src/services/cost-explorer/components/BudgetCreateScopeSelect.vue
  apps/web/src/services/cost-explorer/components/BudgetCreateStep1.vue
  apps/web/src/services/cost-explorer/components/BudgetCreateStep2.vue
  apps/web/src/services/cost-explorer/components/BudgetCreateStep3.vue
  apps/web/src/services/cost-explorer/components/BudgetDetailBaseInformation.vue
  apps/web/src/services/cost-explorer/components/BudgetLastThreeMonthCostTrendBarChart.vue
  apps/web/src/services/cost-explorer/components/BudgetMainList.vue
  apps/web/src/services/cost-explorer/components/BudgetNameEditModal.vue
  apps/web/src/services/cost-explorer/components/BudgetUsageTrend.vue
  apps/web/src/services/cost-explorer/components/BudgetUsageTrendMonthly.vue
  apps/web/src/services/cost-explorer/components/BudgetUsageTrendMonthlyChart.vue
  apps/web/src/services/cost-explorer/components/BudgetUsageTrendMonthlyTable.vue
  apps/web/src/services/cost-explorer/components/BudgetUsageTrendTotal.vue
  apps/web/src/services/cost-explorer/components/BudgetUsageTrendTotalChart.vue
  apps/web/src/services/cost-explorer/components/BudgetUsageTrendTotalTable.vue
  apps/web/src/services/cost-explorer/constants/budget-table-constant.ts
  apps/web/src/services/cost-explorer/pages/BudgetCreatePage.vue
  apps/web/src/services/cost-explorer/pages/BudgetDetailPage.vue
  apps/web/src/services/cost-explorer/pages/admin/AdminBudgetDetailPage.vue
Labels: pass/signedoff, self_approved/review

#5798 refactor: apply merged config to service-api
  apps/web/src/lib/config/global-config/api-client-manager.ts
  apps/web/src/lib/site-initializer/api-client.ts
  apps/web/src/lib/site-initializer/index.ts
  apps/web/src/store/reference/escalation-policy-reference-store.ts
  packages/core-lib/src/space-connector/index.ts
  packages/core-lib/src/space-connector/service-api.ts
Labels: pass/signedoff, self_approved/review

#5799 chore(budget-qa): fix critical & major & minor & trivial bugs
  apps/web/src/services/cost-explorer/components/BudgetCreateStep2.vue
  apps/web/src/services/cost-explorer/components/BudgetDetailBaseInformation.vue
  apps/web/src/services/cost-explorer/components/BudgetMainList.vue
  apps/web/src/services/cost-explorer/components/BudgetMainToolset.vue
  apps/web/src/services/cost-explorer/stores/budget-detail-page-store.ts
  apps/web/src/services/service-account/components/ServiceAccountBaseInformationForm.vue
  packages/language-pack/en.json
  packages/language-pack/ja.json
  packages/language-pack/ko.json
Labels: pass/signedoff, self_approved/review

#5800 chore(budget-qa): fix critical & minor bug
  apps/web/src/services/cost-explorer/components/BudgetCreateStep2.vue
  apps/web/src/services/cost-explorer/components/BudgetCreateStep3.vue
  apps/web/src/services/cost-explorer/components/BudgetLastThreeMonthCostTrendBarChart.vue
  apps/web/src/services/cost-explorer/components/BudgetUsageTrendMonthlyChart.vue
  apps/web/src/services/cost-explorer/components/BudgetUsageTrendMonthlyTable.vue
  apps/web/src/services/cost-explorer/components/BudgetUsageTrendTotalTable.vue
  apps/web/src/services/cost-explorer/components/CostAnalysisContent.vue
  apps/web/src/services/cost-explorer/components/CostAnalysisFiltersPopper.vue
  apps/web/src/services/cost-explorer/routes/routes.ts
Labels: pass/signedoff, self_approved/review

#5802 chore(budget-qa): fix major bug of budget create error
  apps/web/src/services/cost-explorer/components/BudgetCreateStep2.vue
Labels: pass/signedoff, self_approved/review

#5801 fix(dashboard-template): edit wrong query usage
  apps/web/src/services/_shared/dashboard/dashboard-create/composables/use-dashboard-template-query.ts
  apps/web/src/services/_shared/dashboard/dashboard-create/contextual-components/DashboardCreateStep1.vue
  apps/web/src/services/_shared/dashboard/dashboard-create/contextual-components/DashboardCreateStep2BundleCase.vue
Labels: pass/signedoff, self_approved/review

#5803 chore(budget-qa): fix critical & major bugs
  apps/web/src/services/cost-explorer/components/BudgetCreateStep2.vue
  apps/web/src/services/cost-explorer/components/BudgetCreateStep3.vue
  apps/web/src/services/cost-explorer/components/BudgetDetailBaseInformation.vue
  apps/web/src/services/cost-explorer/components/BudgetLastThreeMonthCostTrendBarChart.vue
  apps/web/src/services/cost-explorer/components/BudgetMainList.vue
  apps/web/src/services/cost-explorer/components/BudgetMainToolset.vue
  apps/web/src/services/cost-explorer/components/BudgetUsageTrendMonthlyChart.vue
  apps/web/src/services/cost-explorer/components/BudgetUsageTrendMonthlyTable.vue
  apps/web/src/services/cost-explorer/components/BudgetUsageTrendTotalTable.vue
  apps/web/src/services/cost-explorer/components/CostAnalysisContent.vue
  apps/web/src/services/cost-explorer/components/CostAnalysisFiltersPopper.vue
  apps/web/src/services/cost-explorer/routes/routes.ts
  apps/web/src/services/cost-explorer/stores/budget-detail-page-store.ts
  apps/web/src/services/service-account/components/ServiceAccountBaseInformationForm.vue
  packages/language-pack/en.json
  packages/language-pack/ja.json
  packages/language-pack/ko.json
Labels: pass/signedoff, self_approved/review

#5805 chore(budget-qa): fix major & minor bug
  apps/web/src/services/cost-explorer/components/BudgetCreateStep2.vue
  apps/web/src/services/cost-explorer/components/BudgetDetailBaseInformation.vue
  apps/web/src/services/cost-explorer/routes/admin/routes.ts
Labels: pass/signedoff, self_approved/review

#5806 chore(budget-qa): fix major & minor bugs
  apps/web/src/services/cost-explorer/components/BudgetCreateStep2.vue
  apps/web/src/services/cost-explorer/components/BudgetDetailBaseInformation.vue
  apps/web/src/services/cost-explorer/routes/admin/routes.ts
Labels: pass/signedoff, self_approved/review

#5808 fix(dashboard-tree): apply shared dashboard ux writing
  apps/web/src/services/dashboards/components/dashboard-folder/DashboardFolderTreeItem.vue
Labels: pass/signedoff, self_approved/review

#5810 chore: use proper value in `useUserInfo`
  apps/web/src/services/project/v2/composables/use-user-info.ts
Labels: pass/signedoff

#5811 chore: solve dashboard minor bug
  apps/web/src/services/_shared/dashboard/core/composables/mutations/use-dashboard-folder-share-mutation.ts
  apps/web/src/services/_shared/dashboard/core/composables/mutations/use-dashboard-share-mutation.ts
  apps/web/src/services/_shared/dashboard/dashboard-detail/contextual-components/DashboardDetailHeader.vue
  apps/web/src/services/dashboards/components/dashboard-main/DashboardBundleShareModal.vue
Labels: pass/signedoff, self_approved/review

#5812 feat(release-20250423): merge to master
  apps/web/src/services/_shared/dashboard/core/composables/mutations/use-dashboard-folder-share-mutation.ts
  apps/web/src/services/_shared/dashboard/core/composables/mutations/use-dashboard-share-mutation.ts
  apps/web/src/services/_shared/dashboard/dashboard-detail/contextual-components/DashboardDetailHeader.vue
  apps/web/src/services/dashboards/components/dashboard-main/DashboardBundleShareModal.vue
Labels: fail/signedoff, self_approved/review

#5813 chore: remove unused store and vars
  apps/web/src/common/modules/navigations/top-bar/modules/top-bar-toolset/modules/top-bar-favorite/modules/TopBarFavoriteContextMenu.vue
  apps/web/src/lib/access-control/index.ts
  apps/web/src/lib/access-control/redirect-route-helper.ts
  apps/web/src/router/helpers/route-helper.ts
  apps/web/src/router/index.ts
  apps/web/src/services/ops-flow/task-management-templates/stores/use-task-management-template-store.ts
  apps/web/src/services/project/v1/pages/ProjectDetailTabPage.vue
  apps/web/src/store/authorization/authorization-store.ts
  apps/web/src/store/config/public-config-store.ts
  apps/web/src/store/dashboard/dashboard-store.ts
  apps/web/src/store/display/display-store.ts
  apps/web/src/store/error/error-store.ts
  apps/web/src/store/menu/menu-store.ts
  apps/web/src/store/user/type.ts
  apps/web/src/store/user/user-store.ts
Labels: pass/signedoff, self_approved/review

#5815 fix(widget): solve widget field data bug
  apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2.vue
Labels: pass/signedoff, self_approved/review

#5816 feat(release-20250423-4)
  apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2.vue
Labels: fail/signedoff, self_approved/review

#5817 feat(console-query-debugger): create console query debugger
  apps/web/src/App.vue
  apps/web/src/_dev-tools/vue-query-console-debug.ts
Labels: pass/signedoff

#5820 chore(budget-qa): fix major & minor bugs
  apps/web/src/services/cost-explorer/components/BudgetCreateStep1.vue
  apps/web/src/services/cost-explorer/components/BudgetCreateStep2.vue
  apps/web/src/services/cost-explorer/components/BudgetCreateStep3.vue
  apps/web/src/services/cost-explorer/components/BudgetLastThreeMonthCostTrendBarChart.vue
  apps/web/src/services/cost-explorer/components/BudgetMainList.vue
  apps/web/src/services/cost-explorer/components/BudgetMainToolset.vue
  apps/web/src/services/cost-explorer/components/BudgetUsageTrendMonthly.vue
  apps/web/src/services/cost-explorer/components/BudgetUsageTrendMonthlyChart.vue
  apps/web/src/services/service-account/helpers/dynamic-ui-schema-generator/dynamic-layout-schema-template.ts
  packages/language-pack/en.json
  packages/language-pack/ja.json
  packages/language-pack/ko.json
Labels: pass/signedoff, self_approved/review

#5821 fix: fixed calculate duration bug
  apps/web/src/services/alert-manager/v2/components/AlertsManagementTable.vue
  apps/web/src/services/alert-manager/v2/composables/alert-table-data.ts
Labels: pass/signedoff, self_approved/review

#5822 chore(budget-qa): fix major bug about budget create step2
  apps/web/src/services/cost-explorer/components/BudgetCreateStep2.vue
Labels: pass/signedoff, self_approved/review

#5824 fix(dashboard-bug): solve dashboard widget field and data table issues
  apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2.vue
  apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2WidgetForm.vue
  apps/web/src/common/modules/widgets/_composables/use-data-table-cascade-update.ts
  apps/web/src/common/modules/widgets/_composables/use-widget-data-table-list-query.ts
Labels: pass/signedoff, self_approved/review

#5828 chore(budget-qa): fix major & minor bug
  apps/web/src/services/cost-explorer/components/BudgetCreateStep1.vue
  apps/web/src/services/cost-explorer/components/BudgetCreateStep2.vue
  apps/web/src/services/cost-explorer/components/BudgetCreateStep3.vue
  apps/web/src/services/cost-explorer/components/BudgetMainList.vue
  apps/web/src/services/cost-explorer/components/BudgetMainToolset.vue
  apps/web/src/services/cost-explorer/components/BudgetUsageTrendMonthly.vue
  apps/web/src/services/cost-explorer/components/BudgetUsageTrendMonthlyChart.vue
  apps/web/src/services/cost-explorer/components/BudgetUsageTrendMonthlyTable.vue
  apps/web/src/services/cost-explorer/components/BudgetUsageTrendTotalTable.vue
  apps/web/src/services/cost-explorer/components/CostAnalysisContent.vue
  apps/web/src/services/cost-explorer/components/CostAnalysisFiltersPopper.vue
Labels: pass/signedoff, self_approved/review

#5829 fix: disableCopy not working properly in PDefinitionTable
  packages/mirinae/src/data-display/tables/definition-table/PDefinitionTable.vue
Labels: pass/signedoff
