Repository cloudforet-io/console, pull requests merged in 2025-02, with the labels that each got.

#5612 refactor: pcollapsiblepanel logic
  apps/web/src/services/ops-flow/components/BoardTaskDescriptionField.vue
  apps/web/src/services/ops-flow/components/BoardTaskNameField.vue
  packages/mirinae/src/data-display/collapsible/collapsible-list/PCollapsibleList.vue
  packages/mirinae/src/data-display/collapsible/collapsible-list/type.ts
  packages/mirinae/src/data-display/collapsible/collapsible-panel/PCollapsiblePanel.mdx
  packages/mirinae/src/data-display/collapsible/collapsible-panel/PCollapsiblePanel.stories.ts
  packages/mirinae/src/data-display/collapsible/collapsible-panel/PCollapsiblePanel.vue
  packages/mirinae/src/data-display/collapsible/collapsible-panel/composables/use-text-clamper.ts
  packages/mirinae/src/data-display/collapsible/collapsible-panel/story-helper.ts
  packages/mirinae/src/data-display/collapsible/collapsible-panel/type.ts
Labels: fail/signedoff, self_approved/review

#5611 chore: create workflows merge from master to develop and check commits
  .github/workflows/dispatch_master_to_develop.yaml
  .github/workflows/dispatch_release.yaml
  .github/workflows/pull_request_check_revert_candidate_commits.yaml
Labels: pass/signedoff, pending/review, approved/review

#5609 build: update turbo to version 2.3.4
  package-lock.json
  package.json
  turbo.json
Labels: pass/signedoff, approved/review

#5606 feat: update pairsForm & pairsInputGroup component
  apps/web/src/common/components/forms/pairs-form/PairsForm.vue
  apps/web/src/common/components/forms/pairs-input-group/PairsInputGroup.vue
  apps/web/src/services/alert-manager/components/ServiceDetailTabsWebhookDetailMessageOverlay.vue
Labels: pass/signedoff, self_approved/review

#5613 fix(dockerfile): add missing console log path
  apps/web/Dockerfile
Labels: pass/signedoff, pending/review, self_approved/review

#5615 Revert "chore: create workflows merge from master to develop and check commits (#5611)"
  .github/workflows/dispatch_master_to_develop.yaml
  .github/workflows/dispatch_release.yaml
  .github/workflows/pull_request_check_revert_candidate_commits.yaml
Labels: fail/signedoff, self_approved/review

#5616 chore: create workflows merge from master to develop and check commits
  .github/workflows/dispatch_master_to_develop.yaml
  .github/workflows/dispatch_release.yaml
  .github/workflows/pull_request_check_revert_candidate_commits.yaml
Labels: pass/signedoff, self_approved/review

#5618 chore: merge master into develop after dev2.0.dev307 version tagging
  apps/web/Dockerfile
  apps/web/package.json
  package-lock.json
  package.json
Labels: fail/signedoff, pending/review

#5619 chore(vercel): remove specific app option from vercel.json
  apps/web-storybook/.gitignore
  vercel.json
Labels: pass/signedoff, self_approved/review

#5622 fix(widget): solve widget link bug
  apps/web/src/common/modules/widgets/_composables/use-widget-frame.ts
Labels: pass/signedoff, self_approved/review

#5623 chore(build): add a GitHub Actions workflow to deploy unified-storybook
  .github/workflows/dispatch_deploy_unfied_storybook.yaml
  turbo.json
Labels: pass/signedoff, self_approved/review

#5624 fix(menu): add ops flow menu items to alertV2MenuList
  apps/web/src/lib/menu/menu-architecture.ts
Labels: pass/signedoff, pending/review

#5625 feat: add header slot at overlay layout
  packages/mirinae/src/layouts/overlay-layout/POverlayLayout.vue
  packages/mirinae/src/layouts/overlay-layout/story-helper.ts
Labels: pass/signedoff, pending/review

#5626 chore: changed style section
  packages/mirinae/src/layouts/overlay-layout/POverlayLayout.vue
Labels: pass/signedoff, self_approved/review

#5627 ci: update PR review labeler workflow token name
  .github/workflows/pull_request_review_state_labeler.yaml
Labels: pass/signedoff, self_approved/review

#5629 fix: add task management tab to cloud service detail view
  apps/web/src/services/asset-inventory-v1/components/CloudServiceDetailTabs.vue
Labels: pass/signedoff, approved/review

#5630 fix(data-source): apply changed CostDataSource model (state)
  apps/web/src/schema/cost-analysis/data-source/model.ts
  apps/web/src/schema/cost-analysis/data-source/type.ts
  apps/web/src/services/cost-explorer/components/DataSourceManagementTable.vue
Labels: pass/signedoff, self_approved/review

#5631 feat: apply changed event rule design
  apps/web/src/services/alert-manager/components/ServiceDetailHeader.vue
  apps/web/src/services/alert-manager/components/ServiceDetailTabs.vue
  apps/web/src/services/alert-manager/components/ServiceDetailTabsSettings.vue
  apps/web/src/services/alert-manager/components/ServiceDetailTabsSettingsContainer.vue
  apps/web/src/services/alert-manager/components/ServiceDetailTabsSettingsEventRule.vue
  apps/web/src/services/alert-manager/components/ServiceDetailTabsSettingsEventRuleCard.vue
  apps/web/src/services/alert-manager/components/ServiceDetailTabsSettingsEventRuleOverlay.vue
  apps/web/src/services/alert-manager/components/ServiceDetailTabsSettingsEventRuleSidebar.vue
  apps/web/src/services/alert-manager/stores/service-detail-page-store.ts
Labels: pass/signedoff, self_approved/review

#5633 fix(metric-explorer): solve widget metric link bug & refactor metric page
  apps/web/src/common/modules/widgets/_composables/use-widget-frame.ts
  apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/ClusteredColumnChart.vue
  apps/web/src/common/modules/widgets/_widgets/color-coded-heatmap/ColorCodedHeatmap.vue
  apps/web/src/common/modules/widgets/_widgets/color-coded-table-heatmap/ColorCodedTableHeatmap.vue
  apps/web/src/common/modules/widgets/_widgets/gauge/Gauge.vue
  apps/web/src/common/modules/widgets/_widgets/geo-map/GeoMap.vue
  apps/web/src/common/modules/widgets/_widgets/heatmap/Heatmap.vue
  apps/web/src/common/modules/widgets/_widgets/line-chart/LineChart.vue
  apps/web/src/common/modules/widgets/_widgets/number-card/NumberCard.vue
  apps/web/src/common/modules/widgets/_widgets/pie-chart/PieChart.vue
  apps/web/src/common/modules/widgets/_widgets/sankey-chart/SankeyChart.vue
  apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/StackedColumnChart.vue
  apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/StackedHorizontalBarChart.vue
  apps/web/src/common/modules/widgets/_widgets/table/Table.vue
  apps/web/src/common/modules/widgets/_widgets/treemap/Treemap.vue
  apps/web/src/services/asset-inventory-v1/components/MetricExplorerPeriodDropdown.vue
  apps/web/src/services/asset-inventory-v1/components/MetricExplorerQuerySection.vue
  apps/web/src/services/asset-inventory-v1/pages/MetricExplorerDetailPage.vue
  apps/web/src/services/asset-inventory-v1/stores/metric-explorer-page-store.ts
Labels: pass/signedoff, self_approved/review

#5634 fix(cost-analysis): apply project/service-account link to cost data table
  apps/web/src/services/cost-explorer/components/CostAnalysisDataTable.vue
Labels: pass/signedoff, self_approved/review

#5640 feat(indoor-account): merge to master
  .github/workflows/dispatch_deploy_unfied_storybook.yaml
  .github/workflows/pull_request_review_state_labeler.yaml
  apps/unified-storybook/.storybook/main.ts
  apps/web-storybook/.gitignore
  apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardAddContents.vue
  apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardAddForm.vue
  apps/web/src/common/modules/widgets/_composables/use-widget-frame.ts
  apps/web/src/common/modules/widgets/_constants/data-table-constant.ts
  apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/ClusteredColumnChart.vue
  apps/web/src/common/modules/widgets/_widgets/color-coded-heatmap/ColorCodedHeatmap.vue
  apps/web/src/common/modules/widgets/_widgets/color-coded-table-heatmap/ColorCodedTableHeatmap.vue
  apps/web/src/common/modules/widgets/_widgets/gauge/Gauge.vue
  apps/web/src/common/modules/widgets/_widgets/geo-map/GeoMap.vue
  apps/web/src/common/modules/widgets/_widgets/heatmap/Heatmap.vue
  apps/web/src/common/modules/widgets/_widgets/line-chart/LineChart.vue
  apps/web/src/common/modules/widgets/_widgets/number-card/NumberCard.vue
  apps/web/src/common/modules/widgets/_widgets/pie-chart/PieChart.vue
  apps/web/src/common/modules/widgets/_widgets/sankey-chart/SankeyChart.vue
  apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/StackedColumnChart.vue
  apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/StackedHorizontalBarChart.vue
  apps/web/src/common/modules/widgets/_widgets/table/Table.vue
  apps/web/src/common/modules/widgets/_widgets/treemap/Treemap.vue
  apps/web/src/common/modules/widgets/types/widget-model.ts
  apps/web/src/services/asset-inventory-v1/components/MetricExplorerPeriodDropdown.vue
  apps/web/src/services/asset-inventory-v1/components/MetricExplorerQuerySection.vue
  apps/web/src/services/asset-inventory-v1/pages/MetricExplorerDetailPage.vue
  apps/web/src/services/asset-inventory-v1/stores/metric-explorer-page-store.ts
  apps/web/src/services/cost-explorer/components/CostAnalysisDataTable.vue
  packages/core-lib/src/component-util/query-search/index.ts
  packages/mirinae/src/layouts/overlay-layout/POverlayLayout.vue
  packages/mirinae/src/layouts/overlay-layout/story-helper.ts
  turbo.json
  vercel.json
Labels: fail/signedoff, self_approved/review

#5641 fix(data-table-tags): remove tags item (project)
  apps/web/src/common/modules/widgets/_constants/data-table-constant.ts
Labels: pass/signedoff, self_approved/review

#5635 chore: changed z-index at custom overlay
  apps/web/src/common/components/forms/pairs-form/PairsForm.vue
  apps/web/src/services/asset-inventory-v1/components/CloudServiceHistoryDetailOverlay.vue
  apps/web/src/services/asset-inventory/components/CloudServiceHistoryDetailOverlay.vue
Labels: pass/signedoff

#5643 chore(cost-analysis): solve usage unit total issue
  apps/web/src/services/cost-explorer/components/CostAnalysisDataTable.vue
Labels: pass/signedoff, self_approved/review

#5644 chore: apply no limit query to service account tags
  apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardAddForm.vue
Labels: pass/signedoff, self_approved/review

#5642 fix: fixed bookmark name edit bug
  apps/web/src/services/workspace-home/components/Bookmark.vue
Labels: pass/signedoff

#5648 feat(vue-query): create global useQuery composable (`use-scoped-query`) & refactor dashboard
  apps/web/src/api-clients/_common/composables/use-scoped-query.ts
  apps/web/src/common/modules/widgets/_composables/use-widget-form-query.ts
  apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/ClusteredColumnChart.vue
  apps/web/src/common/modules/widgets/_widgets/color-coded-heatmap/ColorCodedHeatmap.vue
  apps/web/src/common/modules/widgets/_widgets/color-coded-table-heatmap/ColorCodedTableHeatmap.vue
  apps/web/src/common/modules/widgets/_widgets/gauge/Gauge.vue
  apps/web/src/common/modules/widgets/_widgets/geo-map/GeoMap.vue
  apps/web/src/common/modules/widgets/_widgets/heatmap/Heatmap.vue
  apps/web/src/common/modules/widgets/_widgets/line-chart/LineChart.vue
  apps/web/src/common/modules/widgets/_widgets/number-card/NumberCard.vue
  apps/web/src/common/modules/widgets/_widgets/pie-chart/PieChart.vue
  apps/web/src/common/modules/widgets/_widgets/sankey-chart/SankeyChart.vue
  apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/StackedColumnChart.vue
  apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/StackedHorizontalBarChart.vue
  apps/web/src/common/modules/widgets/_widgets/table/Table.vue
  apps/web/src/common/modules/widgets/_widgets/treemap/Treemap.vue
  apps/web/src/services/dashboards/components/dashboard-detail/DashboardLabelsButton.vue
  apps/web/src/services/dashboards/components/dashboard-detail/DashboardRefreshDropdown.vue
  apps/web/src/services/dashboards/components/dashboard-detail/DashboardWidgetContainerV2.vue
  apps/web/src/services/dashboards/composables/use-dashboard-detail-query.ts
  apps/web/src/services/dashboards/composables/use-dashboard-query.ts
  apps/web/src/services/dashboards/stores/dashboard-detail-info-store.ts
  apps/web/src/services/project-v1/pages/ProjectDashboardPage.vue
Labels: pass/signedoff, self_approved/review

#5649 fix(asset-data-source): temporarily remove dataSourceDomain filter
  apps/web/src/common/modules/widgets/_components/WidgetFormAssetSecurityDataSourcePopper.vue
Labels: self_approved/review

#5651 feat(widget-options-architecture): apply advanced architecture
  apps/web/src/api-clients/_common/composables/use-scoped-query.ts
  apps/web/src/api-clients/dashboard/public-widget/schema/model.ts
  apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardAddContents.vue
  apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformContents.vue
  apps/web/src/common/modules/widgets/_components/WidgetFormOverlay.vue
  apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2.vue
  apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2WidgetForm.vue
  apps/web/src/common/modules/widgets/_composables/use-widget-frame.ts
  apps/web/src/common/modules/widgets/_helpers/widget-helper.ts
  apps/web/src/common/modules/widgets/_widget-field-value-manager/constant/default-value-registry.ts
  apps/web/src/common/modules/widgets/_widget-field-value-manager/constant/validator-registry.ts
  apps/web/src/common/modules/widgets/_widget-field-value-manager/index.ts
  apps/web/src/common/modules/widgets/_widget-field-value-manager/type.ts
  apps/web/src/common/modules/widgets/_widget-fields/data-field/WidgetFieldDataField.vue
  apps/web/src/common/modules/widgets/_widget-fields/format-rules/WidgetFieldFormatRules.vue
  apps/web/src/common/modules/widgets/_widget-fields/group-by/WidgetFieldGroupBy.vue
  apps/web/src/common/modules/widgets/_widget-fields/sankey-dimensions/WidgetFieldSankeyDimensions.vue
  apps/web/src/common/modules/widgets/_widget-fields/sankey-dimensions/type.ts
  apps/web/src/common/modules/widgets/_widgets/sankey-chart/widget-config.ts
Labels: pass/signedoff, self_approved/review

#5652 feat(widget-form): solve widget form bugs
  apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2WidgetForm.vue
  apps/web/src/common/modules/widgets/_helpers/widget-helper.ts
  apps/web/src/common/modules/widgets/_widget-field-value-manager/index.ts
  apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/ClusteredColumnChart.vue
  apps/web/src/common/modules/widgets/_widgets/gauge/Gauge.vue
  apps/web/src/common/modules/widgets/_widgets/geo-map/GeoMap.vue
  apps/web/src/common/modules/widgets/_widgets/heatmap/Heatmap.vue
  apps/web/src/common/modules/widgets/_widgets/line-chart/LineChart.vue
  apps/web/src/common/modules/widgets/_widgets/pie-chart/PieChart.vue
  apps/web/src/common/modules/widgets/_widgets/sankey-chart/SankeyChart.vue
  apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/StackedColumnChart.vue
  apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/StackedHorizontalBarChart.vue
  apps/web/src/common/modules/widgets/_widgets/treemap/Treemap.vue
Labels: pass/signedoff, self_approved/review

#5655 fix(alert-manager): solve alert-manager empty page issue
  apps/web/src/services/alert-manager/components/AlertDetailInfoTable.vue
  apps/web/src/services/alert-manager/components/AlertsManagementTable.vue
  apps/web/src/services/alert-manager/components/ServiceListContent.vue
  apps/web/src/services/asset-inventory-v1/components/CloudServiceAlertsTab.vue
Labels: pass/signedoff, self_approved/review

#5656 fix(dashboard): solve dashboard list bug & refactor dataTable updating ux
  apps/web/src/common/modules/widgets/_components/WidgetFormDataSourcePopover.vue
  apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCard.vue
  apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardAddContents.vue
  apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformContents.vue
  apps/web/src/common/modules/widgets/_components/WidgetFormOverlay.vue
  apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep1.vue
  apps/web/src/common/modules/widgets/_composables/use-data-table-cascade-update.ts
  apps/web/src/common/modules/widgets/_helpers/widget-data-table-helper.ts
  apps/web/src/common/modules/widgets/_helpers/widget-helper.ts
  apps/web/src/services/dashboards/components/dashboard-detail/DashboardWidgetContainerV2.vue
  apps/web/src/services/dashboards/composables/use-dashboard-query.ts
  apps/web/src/services/dashboards/pages/DashboardsMainPage.vue
Labels: pass/signedoff, self_approved/review

#5657 chore(data-table): solve transform data-table update bug
  apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardAddContents.vue
  apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardFooter.vue
  apps/web/src/common/modules/widgets/_components/WidgetFormDataTableCardTransformContents.vue
  apps/web/src/common/modules/widgets/_composables/use-data-table-cascade-update.ts
  apps/web/src/common/modules/widgets/_store/widget-generate-store.ts
Labels: pass/signedoff, self_approved/review

#5658 fix(dashboard): solve dashboard toolset dropdown issue & small fix
  apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep1.vue
  apps/web/src/common/modules/widgets/_components/WidgetFormOverlayStep2.vue
  apps/web/src/services/dashboards/components/dashboard-detail/DashboardDetailHeader.vue
  apps/web/src/services/dashboards/composables/use-dashboard-control-menu-items.ts
  apps/web/src/services/dashboards/stores/dashboard-detail-info-store.ts
Labels: pass/signedoff, self_approved/review

#5659 fix(alert-v2): solve service store bug
  apps/web/src/lib/config/composables/use-is-alert-manager-v2-enabled.ts
  apps/web/src/services/project-v1/components/ProjectDetailTabHeader.vue
  apps/web/src/services/project-v1/pages/ProjectDetailTabPage.vue
  apps/web/src/services/project-v1/pages/ProjectSummaryPage.vue
  apps/web/src/store/reference/escalation-policy-reference-store.ts
  apps/web/src/store/reference/service-reference-store.ts
  apps/web/src/store/reference/webhook-reference-store.ts
Labels: pass/signedoff, self_approved/review

#5664 fix(dashboard-clone): solve dashboard clone bug
  apps/web/src/common/modules/widgets/_widgets/clustered-column-chart/ClusteredColumnChart.vue
  apps/web/src/common/modules/widgets/_widgets/color-coded-heatmap/ColorCodedHeatmap.vue
  apps/web/src/common/modules/widgets/_widgets/color-coded-table-heatmap/ColorCodedTableHeatmap.vue
  apps/web/src/common/modules/widgets/_widgets/gauge/Gauge.vue
  apps/web/src/common/modules/widgets/_widgets/geo-map/GeoMap.vue
  apps/web/src/common/modules/widgets/_widgets/heatmap/Heatmap.vue
  apps/web/src/common/modules/widgets/_widgets/line-chart/LineChart.vue
  apps/web/src/common/modules/widgets/_widgets/number-card/NumberCard.vue
  apps/web/src/common/modules/widgets/_widgets/pie-chart/PieChart.vue
  apps/web/src/common/modules/widgets/_widgets/sankey-chart/SankeyChart.vue
  apps/web/src/common/modules/widgets/_widgets/stacked-column-chart/StackedColumnChart.vue
  apps/web/src/common/modules/widgets/_widgets/stacked-horizontal-bar-chart/StackedHorizontalBarChart.vue
  apps/web/src/common/modules/widgets/_widgets/table/Table.vue
  apps/web/src/common/modules/widgets/types/widget-display-type.ts
  apps/web/src/services/dashboards/components/dashboard-detail/DashboardWidgetContainerV2.vue
  apps/web/src/services/dashboards/helpers/dashboard-share-helper.ts
Labels: pass/signedoff, self_approved/review

#5665 chore(dashboard): solve dashboard call issue (detail page)
  apps/web/src/services/dashboards/pages/DashboardDetailPage.vue
Labels: pass/signedoff, self_approved/review

#5647 chore(workflow): improve random reviewer assignment logic
  .github/workflows/pull_request_random_reviewer_assignment.yaml
Labels: pass/signedoff

#5667 chore(lsb-tree): apply default indent (project, dashboard)
  apps/web/src/services/dashboards/components/dashboard-main/DashboardLSBTree.vue
  apps/web/src/services/project-v1/components/ProjectMainTree.vue
Labels: pass/signedoff, self_approved/review

#5669 chore: edit dashboard tree item layout
  apps/web/src/services/dashboards/components/dashboard-folder/DashboardFolderTreeItem.vue
Labels: pass/signedoff, self_approved/review
